// Auto-generated by Supabase — do not edit manually.
// Regenerate: supabase gen types --linked > supabase/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" }
  public: {
    Tables: {
      achievements: {
        Row: { active: boolean; category: string | null; code: string; created_at: string; description: string | null; icon_key: string | null; id: string; name: string; requirement: Json | null }
        Insert: { active?: boolean; category?: string | null; code: string; created_at?: string; description?: string | null; icon_key?: string | null; id?: string; name: string; requirement?: Json | null }
        Update: { active?: boolean; category?: string | null; code?: string; created_at?: string; description?: string | null; icon_key?: string | null; id?: string; name?: string; requirement?: Json | null }
        Relationships: []
      }
      auction_bids: {
        Row: { amount_units: number; auction_pool_id: string; client_request_id: string | null; created_at: string; id: string; player_id: string; room_id: string; sequence: number | null; team_id: string; user_id: string }
        Insert: { amount_units: number; auction_pool_id: string; client_request_id?: string | null; created_at?: string; id?: string; player_id: string; room_id: string; sequence?: number | null; team_id: string; user_id: string }
        Update: { amount_units?: number; auction_pool_id?: string; client_request_id?: string | null; created_at?: string; id?: string; player_id?: string; room_id?: string; sequence?: number | null; team_id?: string; user_id?: string }
        Relationships: []
      }
      auction_events: {
        Row: { created_at: string; event_type: string; id: number; payload: Json | null; player_id: string | null; room_id: string; sequence: number; team_id: string | null; user_id: string | null }
        Insert: { created_at?: string; event_type: string; id?: number; payload?: Json | null; player_id?: string | null; room_id: string; sequence: number; team_id?: string | null; user_id?: string | null }
        Update: { created_at?: string; event_type?: string; id?: number; payload?: Json | null; player_id?: string | null; room_id?: string; sequence?: number; team_id?: string | null; user_id?: string | null }
        Relationships: []
      }
      auction_pool: {
        Row: { auctioned_at: string | null; base_price_units: number; created_at: string; final_price_units: number | null; id: string; player_id: string; pot_id: string | null; queue_order: number; room_id: string; status: string; updated_at: string; winning_team_id: string | null }
        Insert: { auctioned_at?: string | null; base_price_units: number; created_at?: string; final_price_units?: number | null; id?: string; player_id: string; pot_id?: string | null; queue_order: number; room_id: string; status?: string; updated_at?: string; winning_team_id?: string | null }
        Update: { auctioned_at?: string | null; base_price_units?: number; created_at?: string; final_price_units?: number | null; id?: string; player_id?: string; pot_id?: string | null; queue_order?: number; room_id?: string; status?: string; updated_at?: string; winning_team_id?: string | null }
        Relationships: []
      }
      auction_pots: {
        Row: { created_at: string; id: string; name: string; room_id: string; sort_order: number }
        Insert: { created_at?: string; id?: string; name: string; room_id: string; sort_order?: number }
        Update: { created_at?: string; id?: string; name?: string; room_id?: string; sort_order?: number }
        Relationships: []
      }
      auction_result_snapshots: {
        Row: { generated_at: string; room_id: string; summary: Json }
        Insert: { generated_at?: string; room_id: string; summary: Json }
        Update: { generated_at?: string; room_id?: string; summary?: Json }
        Relationships: []
      }
      auction_rooms: {
        Row: { allow_custom_bids: boolean; anti_sniping_enabled: boolean; anti_sniping_reset_seconds: number | null; anti_sniping_threshold_seconds: number | null; code: string; completed_at: string | null; created_at: string; host_user_id: string; id: string; maximum_squad_size: number; minimum_base_price_units: number; minimum_squad_size: number; name: string; number_of_teams: number; player_timer_seconds: number; started_at: string | null; starting_budget_units: number; status: string; updated_at: string }
        Insert: { allow_custom_bids?: boolean; anti_sniping_enabled?: boolean; anti_sniping_reset_seconds?: number | null; anti_sniping_threshold_seconds?: number | null; code: string; completed_at?: string | null; created_at?: string; host_user_id: string; id?: string; maximum_squad_size: number; minimum_base_price_units?: number; minimum_squad_size?: number; name: string; number_of_teams: number; player_timer_seconds?: number; started_at?: string | null; starting_budget_units: number; status?: string; updated_at?: string }
        Update: { allow_custom_bids?: boolean; anti_sniping_enabled?: boolean; anti_sniping_reset_seconds?: number | null; anti_sniping_threshold_seconds?: number | null; code?: string; completed_at?: string | null; created_at?: string; host_user_id?: string; id?: string; maximum_squad_size?: number; minimum_base_price_units?: number; minimum_squad_size?: number; name?: string; number_of_teams?: number; player_timer_seconds?: number; started_at?: string | null; starting_budget_units?: number; status?: string; updated_at?: string }
        Relationships: []
      }
      auction_runtime_snapshots: {
        Row: { active_pool_item_id: string | null; current_bid_units: number | null; ends_at: string | null; highest_bidder_team_id: string | null; remaining_time_ms: number | null; room_id: string; sequence: number; started_at: string | null; state: Json | null; updated_at: string }
        Insert: { active_pool_item_id?: string | null; current_bid_units?: number | null; ends_at?: string | null; highest_bidder_team_id?: string | null; remaining_time_ms?: number | null; room_id: string; sequence?: number; started_at?: string | null; state?: Json | null; updated_at?: string }
        Update: { active_pool_item_id?: string | null; current_bid_units?: number | null; ends_at?: string | null; highest_bidder_team_id?: string | null; remaining_time_ms?: number | null; room_id?: string; sequence?: number; started_at?: string | null; state?: Json | null; updated_at?: string }
        Relationships: []
      }
      football_players: {
        Row: { active: boolean; age: number | null; base_price_units: number; club: string | null; created_at: string; defending: number | null; dribbling: number | null; external_id: string | null; id: string; image_url: string | null; league: string | null; metadata: Json | null; name: string; nationality: string | null; overall: number; pace: number | null; passing: number | null; physical: number | null; position: string; preferred_foot: string | null; secondary_positions: string[] | null; shooting: number | null; updated_at: string }
        Insert: { active?: boolean; age?: number | null; base_price_units?: number; club?: string | null; created_at?: string; defending?: number | null; dribbling?: number | null; external_id?: string | null; id?: string; image_url?: string | null; league?: string | null; metadata?: Json | null; name: string; nationality?: string | null; overall: number; pace?: number | null; passing?: number | null; physical?: number | null; position: string; preferred_foot?: string | null; secondary_positions?: string[] | null; shooting?: number | null; updated_at?: string }
        Update: { active?: boolean; age?: number | null; base_price_units?: number; club?: string | null; created_at?: string; defending?: number | null; dribbling?: number | null; external_id?: string | null; id?: string; image_url?: string | null; league?: string | null; metadata?: Json | null; name?: string; nationality?: string | null; overall?: number; pace?: number | null; passing?: number | null; physical?: number | null; position?: string; preferred_foot?: string | null; secondary_positions?: string[] | null; shooting?: number | null; updated_at?: string }
        Relationships: []
      }
      // ── Manager Mode tables ─────────────────────────────────────────────────
      manager_tournaments: {
        Row: { created_at: string; fixture_format: string; host_user_id: string; id: string; name: string; source_auction_id: string; starting_transfer_budget_units: number; status: string; updated_at: string }
        Insert: { created_at?: string; fixture_format?: string; host_user_id: string; id?: string; name: string; source_auction_id: string; starting_transfer_budget_units?: number; status?: string; updated_at?: string }
        Update: { created_at?: string; fixture_format?: string; host_user_id?: string; id?: string; name?: string; source_auction_id?: string; starting_transfer_budget_units?: number; status?: string; updated_at?: string }
        Relationships: [
          { foreignKeyName: "manager_tournaments_host_user_id_fkey"; columns: ["host_user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournaments_source_auction_id_fkey"; columns: ["source_auction_id"]; isOneToOne: true; referencedRelation: "auction_rooms"; referencedColumns: ["id"] },
        ]
      }
      manager_tournament_teams: {
        Row: { created_at: string; current_transfer_budget_units: number; id: string; manager_user_id: string; source_auction_team_id: string | null; starting_transfer_budget_units: number; team_logo_url: string | null; team_name: string; tournament_id: string; updated_at: string }
        Insert: { created_at?: string; current_transfer_budget_units?: number; id?: string; manager_user_id: string; source_auction_team_id?: string | null; starting_transfer_budget_units?: number; team_logo_url?: string | null; team_name: string; tournament_id: string; updated_at?: string }
        Update: { created_at?: string; current_transfer_budget_units?: number; id?: string; manager_user_id?: string; source_auction_team_id?: string | null; starting_transfer_budget_units?: number; team_logo_url?: string | null; team_name?: string; tournament_id?: string; updated_at?: string }
        Relationships: [
          { foreignKeyName: "manager_tournament_teams_manager_user_id_fkey"; columns: ["manager_user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_teams_source_auction_team_id_fkey"; columns: ["source_auction_team_id"]; isOneToOne: false; referencedRelation: "room_members"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_teams_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_tournament_members: {
        Row: { created_at: string; id: string; joined_at: string; role: string; status: string; team_id: string | null; tournament_id: string; user_id: string }
        Insert: { created_at?: string; id?: string; joined_at?: string; role?: string; status?: string; team_id?: string | null; tournament_id: string; user_id: string }
        Update: { created_at?: string; id?: string; joined_at?: string; role?: string; status?: string; team_id?: string | null; tournament_id?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "manager_tournament_members_team_id_fkey"; columns: ["team_id"]; isOneToOne: false; referencedRelation: "manager_tournament_teams"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_members_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_members_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      manager_tournament_invitations: {
        Row: { created_at: string; id: string; invited_by: string; responded_at: string | null; status: string; team_id: string | null; tournament_id: string; user_id: string }
        Insert: { created_at?: string; id?: string; invited_by: string; responded_at?: string | null; status?: string; team_id?: string | null; tournament_id: string; user_id: string }
        Update: { created_at?: string; id?: string; invited_by?: string; responded_at?: string | null; status?: string; team_id?: string | null; tournament_id?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "manager_tournament_invitations_invited_by_fkey"; columns: ["invited_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_invitations_team_id_fkey"; columns: ["team_id"]; isOneToOne: false; referencedRelation: "manager_tournament_teams"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_invitations_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_invitations_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      manager_tournament_players: {
        Row: { age: number | null; auction_category: string; auction_purchase_price_units: number | null; club: string | null; created_at: string; current_team_id: string | null; defending: number | null; dribbling: number | null; external_source_key: string | null; id: string; image_url: string | null; manager_mode_acquisition_price_units: number | null; name: string; nationality: string | null; overall: number; ownership_status: string; pace: number | null; passing: number | null; physical: number | null; primary_position: string; secondary_positions: string[] | null; shooting: number | null; source: string; source_auction_player_id: string | null; source_player_id: string | null; tier: string | null; tournament_id: string; updated_at: string }
        Insert: { age?: number | null; auction_category: string; auction_purchase_price_units?: number | null; club?: string | null; created_at?: string; current_team_id?: string | null; defending?: number | null; dribbling?: number | null; external_source_key?: string | null; id?: string; image_url?: string | null; manager_mode_acquisition_price_units?: number | null; name: string; nationality?: string | null; overall: number; ownership_status?: string; pace?: number | null; passing?: number | null; physical?: number | null; primary_position: string; secondary_positions?: string[] | null; shooting?: number | null; source: string; source_auction_player_id?: string | null; source_player_id?: string | null; tier?: string | null; tournament_id: string; updated_at?: string }
        Update: { age?: number | null; auction_category?: string; auction_purchase_price_units?: number | null; club?: string | null; created_at?: string; current_team_id?: string | null; defending?: number | null; dribbling?: number | null; external_source_key?: string | null; id?: string; image_url?: string | null; manager_mode_acquisition_price_units?: number | null; name?: string; nationality?: string | null; overall?: number; ownership_status?: string; pace?: number | null; passing?: number | null; physical?: number | null; primary_position?: string; secondary_positions?: string[] | null; shooting?: number | null; source?: string; source_auction_player_id?: string | null; source_player_id?: string | null; tier?: string | null; tournament_id?: string; updated_at?: string }
        Relationships: [
          { foreignKeyName: "manager_tournament_players_current_team_id_fkey"; columns: ["current_team_id"]; isOneToOne: false; referencedRelation: "manager_tournament_teams"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_players_source_auction_player_id_fkey"; columns: ["source_auction_player_id"]; isOneToOne: false; referencedRelation: "auction_pool"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_players_source_player_id_fkey"; columns: ["source_player_id"]; isOneToOne: false; referencedRelation: "football_players"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_tournament_players_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_fixtures: {
        Row: { away_score: number | null; away_team_id: string; completed_at: string | null; created_at: string; home_score: number | null; home_team_id: string; id: string; matchday: number; status: string; tournament_id: string; updated_at: string }
        Insert: { away_score?: number | null; away_team_id: string; completed_at?: string | null; created_at?: string; home_score?: number | null; home_team_id: string; id?: string; matchday: number; status?: string; tournament_id: string; updated_at?: string }
        Update: { away_score?: number | null; away_team_id?: string; completed_at?: string | null; created_at?: string; home_score?: number | null; home_team_id?: string; id?: string; matchday?: number; status?: string; tournament_id?: string; updated_at?: string }
        Relationships: [
          { foreignKeyName: "manager_fixtures_away_team_id_fkey"; columns: ["away_team_id"]; isOneToOne: false; referencedRelation: "manager_tournament_teams"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_fixtures_home_team_id_fkey"; columns: ["home_team_id"]; isOneToOne: false; referencedRelation: "manager_tournament_teams"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_fixtures_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_transfer_windows: {
        Row: { closed_at: string | null; closed_by: string | null; created_at: string; id: string; opened_at: string; opened_by: string; status: string; tournament_id: string }
        Insert: { closed_at?: string | null; closed_by?: string | null; created_at?: string; id?: string; opened_at?: string; opened_by: string; status?: string; tournament_id: string }
        Update: { closed_at?: string | null; closed_by?: string | null; created_at?: string; id?: string; opened_at?: string; opened_by?: string; status?: string; tournament_id?: string }
        Relationships: [
          { foreignKeyName: "manager_transfer_windows_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_trade_offers: {
        Row: { created_at: string; created_by: string; from_team_id: string; id: string; offered_player_id: string; parent_trade_id: string | null; requested_player_id: string; resolved_at: string | null; status: string; to_team_id: string; tournament_id: string; updated_at: string }
        Insert: { created_at?: string; created_by: string; from_team_id: string; id?: string; offered_player_id: string; parent_trade_id?: string | null; requested_player_id: string; resolved_at?: string | null; status?: string; to_team_id: string; tournament_id: string; updated_at?: string }
        Update: { created_at?: string; created_by?: string; from_team_id?: string; id?: string; offered_player_id?: string; parent_trade_id?: string | null; requested_player_id?: string; resolved_at?: string | null; status?: string; to_team_id?: string; tournament_id?: string; updated_at?: string }
        Relationships: [
          { foreignKeyName: "manager_trade_offers_offered_player_id_fkey"; columns: ["offered_player_id"]; isOneToOne: false; referencedRelation: "manager_tournament_players"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_trade_offers_requested_player_id_fkey"; columns: ["requested_player_id"]; isOneToOne: false; referencedRelation: "manager_tournament_players"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_trade_offers_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_transfer_transactions: {
        Row: { amount_units: number | null; created_at: string; from_team_id: string | null; id: string; player_id: string; related_trade_id: string | null; to_team_id: string | null; tournament_id: string; transaction_group_id: string | null; type: string }
        Insert: { amount_units?: number | null; created_at?: string; from_team_id?: string | null; id?: string; player_id: string; related_trade_id?: string | null; to_team_id?: string | null; tournament_id: string; transaction_group_id?: string | null; type: string }
        Update: { amount_units?: number | null; created_at?: string; from_team_id?: string | null; id?: string; player_id?: string; related_trade_id?: string | null; to_team_id?: string | null; tournament_id?: string; transaction_group_id?: string | null; type?: string }
        Relationships: [
          { foreignKeyName: "manager_transfer_transactions_player_id_fkey"; columns: ["player_id"]; isOneToOne: false; referencedRelation: "manager_tournament_players"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_transfer_transactions_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_notifications: {
        Row: { created_at: string; id: string; message: string; metadata: Json | null; read_at: string | null; title: string; tournament_id: string | null; type: string; user_id: string }
        Insert: { created_at?: string; id?: string; message: string; metadata?: Json | null; read_at?: string | null; title: string; tournament_id?: string | null; type: string; user_id: string }
        Update: { created_at?: string; id?: string; message?: string; metadata?: Json | null; read_at?: string | null; title?: string; tournament_id?: string | null; type?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "manager_notifications_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
          { foreignKeyName: "manager_notifications_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      manager_tournament_events: {
        Row: { actor_user_id: string | null; created_at: string; event_type: string; id: number; metadata: Json | null; player_id: string | null; team_id: string | null; tournament_id: string }
        Insert: { actor_user_id?: string | null; created_at?: string; event_type: string; id?: number; metadata?: Json | null; player_id?: string | null; team_id?: string | null; tournament_id: string }
        Update: { actor_user_id?: string | null; created_at?: string; event_type?: string; id?: number; metadata?: Json | null; player_id?: string | null; team_id?: string | null; tournament_id?: string }
        Relationships: [
          { foreignKeyName: "manager_tournament_events_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_external_player_imports: {
        Row: { created_at: string; duplicate_rows: number; filename: string; id: string; invalid_rows: number; status: string; total_rows: number; tournament_id: string; uploaded_by: string; valid_rows: number }
        Insert: { created_at?: string; duplicate_rows?: number; filename: string; id?: string; invalid_rows?: number; status?: string; total_rows?: number; tournament_id: string; uploaded_by: string; valid_rows?: number }
        Update: { created_at?: string; duplicate_rows?: number; filename?: string; id?: string; invalid_rows?: number; status?: string; total_rows?: number; tournament_id?: string; uploaded_by?: string; valid_rows?: number }
        Relationships: [
          { foreignKeyName: "manager_external_player_imports_tournament_id_fkey"; columns: ["tournament_id"]; isOneToOne: false; referencedRelation: "manager_tournaments"; referencedColumns: ["id"] },
        ]
      }
      manager_external_player_import_rows: {
        Row: { created_at: string; error_message: string | null; external_player_id: string | null; id: string; import_id: string; player_name: string | null; row_number: number; status: string }
        Insert: { created_at?: string; error_message?: string | null; external_player_id?: string | null; id?: string; import_id: string; player_name?: string | null; row_number: number; status?: string }
        Update: { created_at?: string; error_message?: string | null; external_player_id?: string | null; id?: string; import_id?: string; player_name?: string | null; row_number?: number; status?: string }
        Relationships: [
          { foreignKeyName: "manager_external_player_import_rows_import_id_fkey"; columns: ["import_id"]; isOneToOne: false; referencedRelation: "manager_external_player_imports"; referencedColumns: ["id"] },
        ]
      }
      player_purchases: {
        Row: { auction_pool_id: string; created_at: string; id: string; player_id: string; price_units: number; purchased_at: string; room_id: string; team_id: string; user_id: string }
        Insert: { auction_pool_id: string; created_at?: string; id?: string; player_id: string; price_units: number; purchased_at?: string; room_id: string; team_id: string; user_id: string }
        Update: { auction_pool_id?: string; created_at?: string; id?: string; player_id?: string; price_units?: number; purchased_at?: string; room_id?: string; team_id?: string; user_id?: string }
        Relationships: []
      }
      profiles: {
        Row: { avatar_url: string | null; bio: string | null; created_at: string; default_team_logo_url: string | null; default_team_name: string | null; display_name: string | null; id: string; updated_at: string; username: string }
        Insert: { avatar_url?: string | null; bio?: string | null; created_at?: string; default_team_logo_url?: string | null; default_team_name?: string | null; display_name?: string | null; id: string; updated_at?: string; username: string }
        Update: { avatar_url?: string | null; bio?: string | null; created_at?: string; default_team_logo_url?: string | null; default_team_name?: string | null; display_name?: string | null; id?: string; updated_at?: string; username?: string }
        Relationships: []
      }
      room_members: {
        Row: { id: string; joined_at: string; players_owned: number; remaining_budget_units: number; role: string; room_id: string; spent_units: number; starting_budget_units: number; status: string; team_logo_url: string | null; team_name: string; updated_at: string; user_id: string }
        Insert: { id?: string; joined_at?: string; players_owned?: number; remaining_budget_units: number; role?: string; room_id: string; spent_units?: number; starting_budget_units: number; status?: string; team_logo_url?: string | null; team_name: string; updated_at?: string; user_id: string }
        Update: { id?: string; joined_at?: string; players_owned?: number; remaining_budget_units?: number; role?: string; room_id?: string; spent_units?: number; starting_budget_units?: number; status?: string; team_logo_url?: string | null; team_name?: string; updated_at?: string; user_id?: string }
        Relationships: []
      }
      user_achievements: {
        Row: { achievement_id: string; context: Json | null; id: string; unlocked_at: string; user_id: string }
        Insert: { achievement_id: string; context?: Json | null; id?: string; unlocked_at?: string; user_id: string }
        Update: { achievement_id?: string; context?: Json | null; id?: string; unlocked_at?: string; user_id?: string }
        Relationships: []
      }
      user_stats: {
        Row: { auctions_played: number; auctions_won: number; created_at: string; highest_purchase_units: number; players_purchased: number; rooms_hosted: number; total_spend_units: number; updated_at: string; user_id: string }
        Insert: { auctions_played?: number; auctions_won?: number; created_at?: string; highest_purchase_units?: number; players_purchased?: number; rooms_hosted?: number; total_spend_units?: number; updated_at?: string; user_id: string }
        Update: { auctions_played?: number; auctions_won?: number; created_at?: string; highest_purchase_units?: number; players_purchased?: number; rooms_hosted?: number; total_spend_units?: number; updated_at?: string; user_id?: string }
        Relationships: []
      }
    }
    Views: {
      player_sale_history_v: { Row: { auction_name: string | null; club: string | null; overall: number | null; player_id: string | null; player_name: string | null; position: string | null; price_units: number | null; purchase_id: string | null; purchased_at: string | null; room_id: string | null; team_id: string | null; team_name: string | null; user_id: string | null }; Relationships: [] }
      room_results_v: { Row: { auction_name: string | null; avg_sale_units: number | null; completed_at: string | null; highest_sale_units: number | null; players_skipped: number | null; players_sold: number | null; players_unsold: number | null; room_id: string | null; started_at: string | null; status: string | null; teams_count: number | null; total_spend_units: number | null }; Relationships: [] }
      room_team_summary_v: { Row: { avg_purchase_units: number | null; highest_purchase_units: number | null; players_owned: number | null; remaining_budget_units: number | null; role: string | null; room_id: string | null; spent_units: number | null; starting_budget_units: number | null; team_id: string | null; team_logo_url: string | null; team_name: string | null; user_id: string | null }; Relationships: [] }
      user_auction_history_v: { Row: { auction_name: string | null; completed_at: string | null; players_purchased: number | null; remaining_budget_units: number | null; role: string | null; room_id: string | null; started_at: string | null; team_name: string | null; total_spend_units: number | null; user_id: string | null }; Relationships: [] }
    }
    Functions: {
      accept_manager_trade: { Args: { p_actor_user_id: string; p_trade_id: string }; Returns: Json }
      change_player_ownership: { Args: { p_actor_user_id: string; p_amount_units: number; p_player_id: string; p_to_team_id: string; p_transaction_type: string }; Returns: Json }
      is_tournament_member: { Args: { p_tournament_id: string }; Returns: boolean }
      persist_sale: { Args: { p_player_id: string; p_pool_item_id: string; p_price_units: number; p_room_id: string; p_sequence: number; p_team_id: string; p_user_id: string }; Returns: Json }
      persist_unsold: { Args: { p_player_id: string; p_pool_item_id: string; p_room_id: string; p_sequence: number }; Returns: undefined }
      save_fixture_result: { Args: { p_actor_user_id: string; p_away_score: number; p_fixture_id: string; p_home_score: number }; Returns: Json }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals }
    ? keyof (DatabaseWithoutInternals[T["schema"]]["Tables"] & DatabaseWithoutInternals[T["schema"]]["Views"])
    : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[T["schema"]]["Tables"] & DatabaseWithoutInternals[T["schema"]]["Views"])[N] extends { Row: infer R } ? R : never
  : T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[T] extends { Row: infer R } ? R : never
  : never

export type TablesInsert<
  T extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals }
    ? keyof DatabaseWithoutInternals[T["schema"]]["Tables"] : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[T["schema"]]["Tables"][N] extends { Insert: infer I } ? I : never
  : T extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][T] extends { Insert: infer I } ? I : never
  : never

export type TablesUpdate<
  T extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals }
    ? keyof DatabaseWithoutInternals[T["schema"]]["Tables"] : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[T["schema"]]["Tables"][N] extends { Update: infer U } ? U : never
  : T extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][T] extends { Update: infer U } ? U : never
  : never

export type Enums<
  T extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals }
    ? keyof DatabaseWithoutInternals[T["schema"]]["Enums"] : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[T["schema"]]["Enums"][N]
  : T extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][T]
  : never

// ── Convenience aliases (Manager Mode) ───────────────────────────────────────
export type ManagerTournament        = Tables<"manager_tournaments">
export type ManagerTournamentTeam    = Tables<"manager_tournament_teams">
export type ManagerTournamentMember  = Tables<"manager_tournament_members">
export type ManagerInvitation        = Tables<"manager_tournament_invitations">
export type ManagerPlayer            = Tables<"manager_tournament_players">
export type ManagerFixture           = Tables<"manager_fixtures">
export type ManagerTransferWindow    = Tables<"manager_transfer_windows">
export type ManagerTradeOffer        = Tables<"manager_trade_offers">
export type ManagerTransferTx        = Tables<"manager_transfer_transactions">
export type ManagerNotification      = Tables<"manager_notifications">
export type ManagerTournamentEvent   = Tables<"manager_tournament_events">
export type ManagerImport            = Tables<"manager_external_player_imports">
export type ManagerImportRow         = Tables<"manager_external_player_import_rows">

// ── Status literal unions ─────────────────────────────────────────────────────
export type TournamentStatus   = "SETUP" | "INVITING" | "ACTIVE" | "COMPLETED" | "ARCHIVED"
export type FixtureFormat      = "SINGLE_ROUND_ROBIN" | "DOUBLE_ROUND_ROBIN"
export type MemberRole         = "HOST" | "MANAGER"
export type MemberStatus       = "INVITED" | "JOINED" | "DECLINED"
export type InvitationStatus   = "PENDING" | "JOINED" | "DECLINED"
export type PlayerSource       = "AUCTION_SQUAD" | "AUCTION_UNSOLD" | "EXTERNAL_POOL"
export type OwnershipStatus    = "OWNED" | "FREE_AGENT" | "LOCKED"
export type FixtureStatus      = "SCHEDULED" | "COMPLETED" | "POSTPONED" | "CANCELLED"
export type TransferWindowStatus = "OPEN" | "CLOSED"
export type TradeStatus        = "PENDING" | "ACCEPTED" | "REJECTED" | "COUNTERED" | "CANCELLED" | "EXPIRED"
export type TransactionType    = "AUCTION_IMPORT" | "FREE_AGENT_SIGNING" | "TRADE" | "RELEASE"
export type ImportStatus       = "PROCESSING" | "COMPLETED" | "FAILED"
export type NotificationType   =
  | "TOURNAMENT_INVITE" | "MANAGER_JOINED" | "FIXTURES_GENERATED" | "RESULT_UPDATED"
  | "TRANSFER_WINDOW_OPENED" | "TRANSFER_WINDOW_CLOSED"
  | "TRADE_RECEIVED" | "TRADE_ACCEPTED" | "TRADE_REJECTED" | "TRADE_CANCELLED"
  | "PLAYER_TRANSFERRED" | "TOURNAMENT_ANNOUNCEMENT"

export const Constants = { public: { Enums: {} } } as const
