// Auto-generated by Supabase — do not edit manually.
// Regenerate with: supabase gen types --linked > supabase/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      achievements: {
        Row: {
          active: boolean
          category: string | null
          code: string
          created_at: string
          description: string | null
          icon_key: string | null
          id: string
          name: string
          requirement: Json | null
        }
        Insert: {
          active?: boolean
          category?: string | null
          code: string
          created_at?: string
          description?: string | null
          icon_key?: string | null
          id?: string
          name: string
          requirement?: Json | null
        }
        Update: {
          active?: boolean
          category?: string | null
          code?: string
          created_at?: string
          description?: string | null
          icon_key?: string | null
          id?: string
          name?: string
          requirement?: Json | null
        }
        Relationships: []
      }
      auction_bids: {
        Row: {
          amount_units: number
          auction_pool_id: string
          client_request_id: string | null
          created_at: string
          id: string
          player_id: string
          room_id: string
          sequence: number | null
          team_id: string
          user_id: string
        }
        Insert: {
          amount_units: number
          auction_pool_id: string
          client_request_id?: string | null
          created_at?: string
          id?: string
          player_id: string
          room_id: string
          sequence?: number | null
          team_id: string
          user_id: string
        }
        Update: {
          amount_units?: number
          auction_pool_id?: string
          client_request_id?: string | null
          created_at?: string
          id?: string
          player_id?: string
          room_id?: string
          sequence?: number | null
          team_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "auction_bids_auction_pool_id_fkey"
            columns: ["auction_pool_id"]
            isOneToOne: false
            referencedRelation: "auction_pool"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_bids_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "football_players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_bids_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_bids_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "room_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_bids_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_events: {
        Row: {
          created_at: string
          event_type: string
          id: number
          payload: Json | null
          player_id: string | null
          room_id: string
          sequence: number
          team_id: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          event_type: string
          id?: number
          payload?: Json | null
          player_id?: string | null
          room_id: string
          sequence: number
          team_id?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          event_type?: string
          id?: number
          payload?: Json | null
          player_id?: string | null
          room_id?: string
          sequence?: number
          team_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "auction_events_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "football_players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_events_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_events_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "room_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_pool: {
        Row: {
          auctioned_at: string | null
          base_price_units: number
          created_at: string
          final_price_units: number | null
          id: string
          player_id: string
          pot_id: string | null
          queue_order: number
          room_id: string
          status: string
          updated_at: string
          winning_team_id: string | null
        }
        Insert: {
          auctioned_at?: string | null
          base_price_units: number
          created_at?: string
          final_price_units?: number | null
          id?: string
          player_id: string
          pot_id?: string | null
          queue_order: number
          room_id: string
          status?: string
          updated_at?: string
          winning_team_id?: string | null
        }
        Update: {
          auctioned_at?: string | null
          base_price_units?: number
          created_at?: string
          final_price_units?: number | null
          id?: string
          player_id?: string
          pot_id?: string | null
          queue_order?: number
          room_id?: string
          status?: string
          updated_at?: string
          winning_team_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "auction_pool_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "football_players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_pool_pot_id_fkey"
            columns: ["pot_id"]
            isOneToOne: false
            referencedRelation: "auction_pots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_pool_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_pool_winning_team_id_fkey"
            columns: ["winning_team_id"]
            isOneToOne: false
            referencedRelation: "room_members"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_pots: {
        Row: {
          created_at: string
          id: string
          name: string
          room_id: string
          sort_order: number
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          room_id: string
          sort_order?: number
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          room_id?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "auction_pots_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_result_snapshots: {
        Row: {
          generated_at: string
          room_id: string
          summary: Json
        }
        Insert: {
          generated_at?: string
          room_id: string
          summary: Json
        }
        Update: {
          generated_at?: string
          room_id?: string
          summary?: Json
        }
        Relationships: [
          {
            foreignKeyName: "auction_result_snapshots_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: true
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_rooms: {
        Row: {
          allow_custom_bids: boolean
          anti_sniping_enabled: boolean
          anti_sniping_reset_seconds: number | null
          anti_sniping_threshold_seconds: number | null
          code: string
          completed_at: string | null
          created_at: string
          host_user_id: string
          id: string
          maximum_squad_size: number
          minimum_base_price_units: number
          minimum_squad_size: number
          name: string
          number_of_teams: number
          player_timer_seconds: number
          started_at: string | null
          starting_budget_units: number
          status: string
          updated_at: string
        }
        Insert: {
          allow_custom_bids?: boolean
          anti_sniping_enabled?: boolean
          anti_sniping_reset_seconds?: number | null
          anti_sniping_threshold_seconds?: number | null
          code: string
          completed_at?: string | null
          created_at?: string
          host_user_id: string
          id?: string
          maximum_squad_size: number
          minimum_base_price_units?: number
          minimum_squad_size?: number
          name: string
          number_of_teams: number
          player_timer_seconds?: number
          started_at?: string | null
          starting_budget_units: number
          status?: string
          updated_at?: string
        }
        Update: {
          allow_custom_bids?: boolean
          anti_sniping_enabled?: boolean
          anti_sniping_reset_seconds?: number | null
          anti_sniping_threshold_seconds?: number | null
          code?: string
          completed_at?: string | null
          created_at?: string
          host_user_id?: string
          id?: string
          maximum_squad_size?: number
          minimum_base_price_units?: number
          minimum_squad_size?: number
          name?: string
          number_of_teams?: number
          player_timer_seconds?: number
          started_at?: string | null
          starting_budget_units?: number
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "auction_rooms_host_user_id_fkey"
            columns: ["host_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_runtime_snapshots: {
        Row: {
          active_pool_item_id: string | null
          current_bid_units: number | null
          ends_at: string | null
          highest_bidder_team_id: string | null
          remaining_time_ms: number | null
          room_id: string
          sequence: number
          started_at: string | null
          state: Json | null
          updated_at: string
        }
        Insert: {
          active_pool_item_id?: string | null
          current_bid_units?: number | null
          ends_at?: string | null
          highest_bidder_team_id?: string | null
          remaining_time_ms?: number | null
          room_id: string
          sequence?: number
          started_at?: string | null
          state?: Json | null
          updated_at?: string
        }
        Update: {
          active_pool_item_id?: string | null
          current_bid_units?: number | null
          ends_at?: string | null
          highest_bidder_team_id?: string | null
          remaining_time_ms?: number | null
          room_id?: string
          sequence?: number
          started_at?: string | null
          state?: Json | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "auction_runtime_snapshots_active_pool_item_id_fkey"
            columns: ["active_pool_item_id"]
            isOneToOne: false
            referencedRelation: "auction_pool"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_runtime_snapshots_highest_bidder_team_id_fkey"
            columns: ["highest_bidder_team_id"]
            isOneToOne: false
            referencedRelation: "room_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_runtime_snapshots_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: true
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      football_players: {
        Row: {
          active: boolean
          age: number | null
          base_price_units: number
          club: string | null
          created_at: string
          defending: number | null
          dribbling: number | null
          external_id: string | null
          id: string
          image_url: string | null
          league: string | null
          metadata: Json | null
          name: string
          nationality: string | null
          overall: number
          pace: number | null
          passing: number | null
          physical: number | null
          position: string
          preferred_foot: string | null
          secondary_positions: string[] | null
          shooting: number | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          age?: number | null
          base_price_units?: number
          club?: string | null
          created_at?: string
          defending?: number | null
          dribbling?: number | null
          external_id?: string | null
          id?: string
          image_url?: string | null
          league?: string | null
          metadata?: Json | null
          name: string
          nationality?: string | null
          overall: number
          pace?: number | null
          passing?: number | null
          physical?: number | null
          position: string
          preferred_foot?: string | null
          secondary_positions?: string[] | null
          shooting?: number | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          age?: number | null
          base_price_units?: number
          club?: string | null
          created_at?: string
          defending?: number | null
          dribbling?: number | null
          external_id?: string | null
          id?: string
          image_url?: string | null
          league?: string | null
          metadata?: Json | null
          name?: string
          nationality?: string | null
          overall?: number
          pace?: number | null
          passing?: number | null
          physical?: number | null
          position?: string
          preferred_foot?: string | null
          secondary_positions?: string[] | null
          shooting?: number | null
          updated_at?: string
        }
        Relationships: []
      }
      player_purchases: {
        Row: {
          auction_pool_id: string
          created_at: string
          id: string
          player_id: string
          price_units: number
          purchased_at: string
          room_id: string
          team_id: string
          user_id: string
        }
        Insert: {
          auction_pool_id: string
          created_at?: string
          id?: string
          player_id: string
          price_units: number
          purchased_at?: string
          room_id: string
          team_id: string
          user_id: string
        }
        Update: {
          auction_pool_id?: string
          created_at?: string
          id?: string
          player_id?: string
          price_units?: number
          purchased_at?: string
          room_id?: string
          team_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "player_purchases_auction_pool_id_fkey"
            columns: ["auction_pool_id"]
            isOneToOne: false
            referencedRelation: "auction_pool"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "player_purchases_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "football_players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "player_purchases_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "player_purchases_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "room_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "player_purchases_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string
          default_team_logo_url: string | null
          default_team_name: string | null
          display_name: string | null
          id: string
          updated_at: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          default_team_logo_url?: string | null
          default_team_name?: string | null
          display_name?: string | null
          id: string
          updated_at?: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          default_team_logo_url?: string | null
          default_team_name?: string | null
          display_name?: string | null
          id?: string
          updated_at?: string
          username?: string
        }
        Relationships: []
      }
      room_members: {
        Row: {
          id: string
          joined_at: string
          players_owned: number
          remaining_budget_units: number
          role: string
          room_id: string
          spent_units: number
          starting_budget_units: number
          status: string
          team_logo_url: string | null
          team_name: string
          updated_at: string
          user_id: string
        }
        Insert: {
          id?: string
          joined_at?: string
          players_owned?: number
          remaining_budget_units: number
          role?: string
          room_id: string
          spent_units?: number
          starting_budget_units: number
          status?: string
          team_logo_url?: string | null
          team_name: string
          updated_at?: string
          user_id: string
        }
        Update: {
          id?: string
          joined_at?: string
          players_owned?: number
          remaining_budget_units?: number
          role?: string
          room_id?: string
          spent_units?: number
          starting_budget_units?: number
          status?: string
          team_logo_url?: string | null
          team_name?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_members_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "auction_rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_achievements: {
        Row: {
          achievement_id: string
          context: Json | null
          id: string
          unlocked_at: string
          user_id: string
        }
        Insert: {
          achievement_id: string
          context?: Json | null
          id?: string
          unlocked_at?: string
          user_id: string
        }
        Update: {
          achievement_id?: string
          context?: Json | null
          id?: string
          unlocked_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_achievements_achievement_id_fkey"
            columns: ["achievement_id"]
            isOneToOne: false
            referencedRelation: "achievements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_achievements_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_stats: {
        Row: {
          auctions_played: number
          auctions_won: number
          created_at: string
          highest_purchase_units: number
          players_purchased: number
          rooms_hosted: number
          total_spend_units: number
          updated_at: string
          user_id: string
        }
        Insert: {
          auctions_played?: number
          auctions_won?: number
          created_at?: string
          highest_purchase_units?: number
          players_purchased?: number
          rooms_hosted?: number
          total_spend_units?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          auctions_played?: number
          auctions_won?: number
          created_at?: string
          highest_purchase_units?: number
          players_purchased?: number
          rooms_hosted?: number
          total_spend_units?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_stats_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      player_sale_history_v: {
        Row: {
          auction_name: string | null
          club: string | null
          overall: number | null
          player_id: string | null
          player_name: string | null
          position: string | null
          price_units: number | null
          purchase_id: string | null
          purchased_at: string | null
          room_id: string | null
          team_id: string | null
          team_name: string | null
          user_id: string | null
        }
        Relationships: []
      }
      room_results_v: {
        Row: {
          auction_name: string | null
          avg_sale_units: number | null
          completed_at: string | null
          highest_sale_units: number | null
          players_skipped: number | null
          players_sold: number | null
          players_unsold: number | null
          room_id: string | null
          started_at: string | null
          status: string | null
          teams_count: number | null
          total_spend_units: number | null
        }
        Relationships: []
      }
      room_team_summary_v: {
        Row: {
          avg_purchase_units: number | null
          highest_purchase_units: number | null
          players_owned: number | null
          remaining_budget_units: number | null
          role: string | null
          room_id: string | null
          spent_units: number | null
          starting_budget_units: number | null
          team_id: string | null
          team_logo_url: string | null
          team_name: string | null
          user_id: string | null
        }
        Relationships: []
      }
      user_auction_history_v: {
        Row: {
          auction_name: string | null
          completed_at: string | null
          players_purchased: number | null
          remaining_budget_units: number | null
          role: string | null
          room_id: string | null
          started_at: string | null
          team_name: string | null
          total_spend_units: number | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      persist_sale: {
        Args: {
          p_player_id: string
          p_pool_item_id: string
          p_price_units: number
          p_room_id: string
          p_sequence: number
          p_team_id: string
          p_user_id: string
        }
        Returns: Json
      }
      persist_unsold: {
        Args: {
          p_player_id: string
          p_pool_item_id: string
          p_room_id: string
          p_sequence: number
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// -------------------------------------------------------
// Convenience type aliases for common usage patterns
// -------------------------------------------------------

/** A row from any public table */
export type Profile            = Tables<"profiles">
export type UserStats          = Tables<"user_stats">
export type AuctionRoom        = Tables<"auction_rooms">
export type RoomMember         = Tables<"room_members">
export type FootballPlayer     = Tables<"football_players">
export type AuctionPot         = Tables<"auction_pots">
export type AuctionPoolItem    = Tables<"auction_pool">
export type AuctionBid         = Tables<"auction_bids">
export type PlayerPurchase     = Tables<"player_purchases">
export type AuctionEvent       = Tables<"auction_events">
export type Achievement        = Tables<"achievements">
export type UserAchievement    = Tables<"user_achievements">
export type RuntimeSnapshot    = Tables<"auction_runtime_snapshots">
export type ResultSnapshot     = Tables<"auction_result_snapshots">

/** View row types */
export type RoomTeamSummary    = Tables<"room_team_summary_v">
export type RoomResult         = Tables<"room_results_v">
export type UserAuctionHistory = Tables<"user_auction_history_v">
export type PlayerSaleHistory  = Tables<"player_sale_history_v">

/** Status literal unions (mirrors CHECK constraints) */
export type RoomStatus       = "LOBBY" | "STARTING" | "RUNNING" | "PAUSED" | "COMPLETED" | "CLOSED"
export type MemberRole       = "HOST" | "PLAYER"
export type MemberStatus     = "JOINED" | "READY" | "DISCONNECTED" | "LEFT" | "KICKED"
export type PoolItemStatus   = "WAITING" | "ACTIVE" | "SOLD" | "UNSOLD" | "SKIPPED"
export type PlayerPosition   = "GK" | "CB" | "LB" | "RB" | "LWB" | "RWB" | "CDM" | "CM" | "CAM" | "LM" | "RM" | "LW" | "RW" | "CF" | "ST"
export type AuctionEventType =
  | "ROOM_CREATED" | "TEAM_JOINED" | "TEAM_LEFT" | "TEAM_KICKED"
  | "AUCTION_STARTED" | "AUCTION_PAUSED" | "AUCTION_RESUMED" | "AUCTION_COMPLETED"
  | "PLAYER_STARTED" | "BID_ACCEPTED" | "PLAYER_SOLD" | "PLAYER_UNSOLD" | "PLAYER_SKIPPED"
  | "ROOM_CLOSED"

/**
 * Money utility — converts between display crores and storage units.
 * Storage: integer half-crore units (₹0.5 Cr = 1 unit, ₹1 Cr = 2 units)
 */
export const Money = {
  /** Convert ₹X Cr display value to storage integer units */
  crToUnits: (cr: number): number => Math.round(cr * 2),
  /** Convert storage integer units to ₹X Cr display value */
  unitsToCr: (units: number): number => units / 2,
  /** Format units as display string: "₹10.5 Cr" */
  display: (units: number): string => `₹${units / 2} Cr`,
} as const
