import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {connectDatabase} from '../src/repositories/postgres.js';
import {PostgresManagerTournamentRepository} from '../src/modules/manager-mode/postgres-manager.repository.js';
import {ManagerModeService} from '../src/modules/manager-mode/manager.service.js';
import {archiveCompletedAuction} from '../src/modules/manager-mode/completed-auction-archive.js';
import {readCompletedAuction} from '../src/modules/manager-mode/auction-snapshot.repository.js';
import {settingsSchema} from '../src/schemas/settings.js';
import type {Room} from '../src/domain/types.js';
if(process.env.MANAGER_DB_TEST_ALLOW_WRITES!=='1'&&!process.argv.includes('--write-fixtures'))throw Error('Set MANAGER_DB_TEST_ALLOW_WRITES=1 to create and remove isolated integration fixtures.');
const db=connectDatabase(process.env.DATABASE_URL!);const run=randomUUID(),users=Array.from({length:8},()=>randomUUID()),teamIds=users.map(()=>randomUUID());const sourceId=randomUUID();let tournamentId:string|undefined;
const room:Room={id:sourceId,code:run.replace(/[^A-F2-9]/gi,'').toUpperCase().padEnd(6,'A').slice(0,6),hostUserId:users[0]!,auctionName:'Manager persistence integration '+run,status:'COMPLETED',createdAt:Date.now(),settings:settingsSchema.parse({numberOfTeams:8,startingBudgetCr:200,minSquadSize:1,maxSquadSize:24}),teams:users.map((userId,i)=>({id:teamIds[i]!,userId,name:'Test Team '+i,startingBudgetUnits:400,spentUnits:48,playerIds:Array.from({length:24},(_,j)=>run+'-p'+(i*24+j))})),players:Array.from({length:212},(_,i)=>({id:run+'-p'+i,name:'Test Player '+i,ovr:82,position:'MID',subPosition:'CM',stats:{passing:80},basePriceUnits:2,potId:'test',status:i<192?'SOLD':'UNSOLD',round:1})),purchases:[],bids:[],active:null,playerQueue:[],sequence:5,nextPlayerAt:null,receipts:{}};
room.purchases=room.teams.flatMap(t=>t.playerIds.map(id=>({id:randomUUID(),playerId:id,teamId:t.id,priceUnits:2,bidCount:1,at:Date.now(),durationMs:1})));
let phase='fixture users';
try{
 await db.begin(async tx=>{for(let i=0;i<users.length;i++)await tx`insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_user_meta_data,created_at,updated_at) values(${users[i]!},'00000000-0000-0000-0000-000000000000','authenticated','authenticated',${'mm-test-'+run+'-'+i+'@example.invalid'},now(),${tx.json({username:'mmtest_'+run.slice(0,8)+'_'+i})},now(),now())`;});
 phase='archive completed snapshot';await archiveCompletedAuction(db,room,users[0]!);const persisted=(await readCompletedAuction(db,sourceId))!;assert.equal(persisted.players.length,212);
 const service=new ManagerModeService(new PostgresManagerTournamentRepository(db),id=>readCompletedAuction(db,id));
 phase='create';let t=await service.create(sourceId,users[0]!,{addUnusedAuctionPurse:false,name:'Integration tournament',csv:'player_id,name,overall,position\n'+Array.from({length:50},(_,i)=>run+'-external'+i+',External '+i+',82,CB').join('\n')});tournamentId=t.id;assert.equal(t.players.filter(p=>p.currentTeamId).length,192);assert.equal(t.players.filter(p=>!p.currentTeamId).length,427);
 assert.equal((await service.create(sourceId,users[0]!,{addUnusedAuctionPurse:false,name:'Duplicate'})).id,t.id);
 const act=(user:string,action:Parameters<typeof service.mutate>[3],request=randomUUID())=>service.mutate(t.id,user,request,action);
 const imports=await db`select id,valid_rows from public.manager_external_player_imports where tournament_id=${t.id}`;assert.equal(imports.length,1);assert.equal(imports[0]!.valid_rows,407);const imported=await db`select count(*)::int as count from public.manager_external_player_import_rows where import_id=${imports[0]!.id}`;assert.equal(imported[0]!.count,407);
 if(process.argv.includes('--squad-only')){
 phase='squad activation';await db`update public.manager_tournament_members set status='JOINED' where tournament_id=${t.id}`;t=await act(users[0]!,{type:'GENERATE_FIXTURES'});
 const owned=t.players.filter(p=>p.currentTeamId===teamIds[0]);const slots=[...owned.slice(0,10).map(p=>p.id),null];
 phase='team sheet';t=await act(users[0]!,{type:'SAVE_TEAM_SHEET',formation:'4-3-3',slots,bench:[owned[10]!.id],captainId:owned[0]!.id});assert.equal(t.squadData!.sheets[0]!.slots.filter(Boolean).length,10);
 phase='contract';t=await act(users[0]!,{type:'RENEW_CONTRACT',playerId:owned[0]!.id});assert.equal(t.squadData!.contracts[0]!.renewalCount,1);
 const match=t.fixtures.find(f=>f.homeTeamId===teamIds[0]||f.awayTeamId===teamIds[0])!,home=match.homeTeamId===teamIds[0];
 phase='score snapshots';t=await act(users[0]!,{type:'SCORE',fixtureId:match.id,homeScore:home?3:0,awayScore:home?0:3,scorers:{[teamIds[0]!]:[{playerId:owned[0]!.id,goals:3}]}});assert.equal(t.playerStats![owned[0]!.id]!.matchesPlayed,1);assert.equal(t.playerStats![owned[0]!.id]!.goals,3);
 phase='sheet changes preserve history';await act(users[0]!,{type:'SAVE_TEAM_SHEET',formation:'4-4-2',slots:[owned[11]!.id,...slots.slice(1)],bench:[],captainId:null});
 phase='correct score';t=await act(users[0]!,{type:'SCORE',fixtureId:match.id,homeScore:home?2:0,awayScore:home?0:2,scorers:{[teamIds[0]!]:[{playerId:owned[0]!.id,goals:2}]}});assert.equal(t.playerStats![owned[0]!.id]!.matchesPlayed,1);assert.equal(t.playerStats![owned[0]!.id]!.goals,2);
 phase='fresh squad connection';const other=connectDatabase(process.env.DATABASE_URL!);try{const fresh=new ManagerModeService(new PostgresManagerTournamentRepository(other),id=>readCompletedAuction(other,id));const recovered=await fresh.state(t.id,users[0]!);assert.equal(recovered.squadData!.sheets[0]!.formation,'4-4-2');assert.equal(recovered.squadData!.contracts[0]!.renewalCount,1);assert.equal(recovered.playerStats![owned[0]!.id]!.goals,2);}finally{await other.end();}
 phase='reset match';t=await act(users[0]!,{type:'RESET_SCORE',fixtureId:match.id});assert.equal(t.squadData!.lineups.length,0);assert.equal(t.playerStats![owned[0]!.id],undefined);
 phase='released player';t=await act(users[0]!,{type:'WINDOW',open:true});const releasedId=owned[0]!.id,quote=t.saleQuotes![releasedId]!;const budget=t.teams.find(x=>x.id===teamIds[0])!.transferBudgetUnits;
 const outcomes=await Promise.allSettled([act(users[0]!,{type:'SELL_PLAYER',playerId:releasedId,ownershipToken:quote.ownershipToken,expectedSaleUnits:quote.saleValueUnits}),act(users[0]!,{type:'SELL_PLAYER',playerId:releasedId,ownershipToken:quote.ownershipToken,expectedSaleUnits:quote.saleValueUnits})]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);
 phase='release recovery';t=await service.state(t.id,users[0]!);assert.equal(t.players.find(p=>p.id===releasedId)!.currentTeamId,null);assert.equal(t.players.find(p=>p.id===releasedId)!.metadata.freeAgentReason,'TEAM_RELEASE');assert.equal(t.teams.find(x=>x.id===teamIds[0])!.transferBudgetUnits,budget+quote.saleValueUnits);await assert.rejects(act(users[0]!,{type:'START_NEGOTIATION',playerId:releasedId}),{code:'RELEASE_RESIGN_COOLDOWN'});
 phase='released player signing';let receiver=await act(users[1]!,{type:'START_NEGOTIATION',playerId:releasedId});const session=receiver.negotiation.sessions.find(s=>s.playerId===releasedId)!;receiver=await act(users[1]!,{type:'OFFER_FREE_AGENT',sessionId:session.id,amountUnits:100});assert.equal(receiver.negotiation.sessions.find(s=>s.id===session.id)!.status,'ACCEPTED');receiver=await act(users[1]!,{type:'CONFIRM_SIGNING',sessionId:session.id});assert.equal(receiver.players.find(p=>p.id===releasedId)!.currentTeamId,teamIds[1]);assert.equal(receiver.transactions.filter(x=>x.playerId===releasedId&&x.type==='RELEASE').length,1);
 phase='notification reads and summary';const summary=(await service.list(users[1]!)).find(x=>x.id===t.id)!;assert.equal(summary.unread,receiver.notificationUnread);const cleared=await act(users[1]!,{type:'READ_ALL_NOTIFICATIONS'});assert.equal(cleared.notificationUnread,0);assert.ok((await service.notifications(t.id,users[1]!)).items.every(n=>n.userId===users[1]));
 phase='squad deletion';await service.delete(t.id,users[0]!);assert.equal((await db`select team_id from public.manager_team_sheets where tournament_id=${t.id}`).length,0);
 console.log('PASS: Postgres team sheets, contracts, starter snapshots, scorer correction, fresh connection, reset, release/re-sign cooldown, default pool, signing, notifications, summary and cascade deletion.');
 }
 if(process.argv.includes('--pricing-only')){
 phase='pricing activation';await db`update public.manager_tournaments set status='ACTIVE' where id=${t.id}`;await db`update public.manager_tournament_members set status='JOINED' where tournament_id=${t.id}`;
 const player=t.players.find(p=>p.source==='EXTERNAL_POOL'&&String(p.metadata.externalSourceKey).startsWith(run))!;
 phase='legacy profile seed';await db`update public.manager_player_negotiation_profiles set market_value_units=40,minimum_value_units=30,preferred_value_units=40,ideal_value_units=52 where player_id=${player.id}`;
 phase='repricing commit';t=await act(users[0]!,{type:'WINDOW',open:true});const [profile]=await db`select preferred_value_units,ideal_value_units from public.manager_player_negotiation_profiles where player_id=${player.id}`;assert.ok(Number(profile!.preferred_value_units)<=10);assert.ok(Number(profile!.ideal_value_units)<=12);
 phase='accepted offer';t=await act(users[0]!,{type:'START_NEGOTIATION',playerId:player.id});const session=t.negotiation.sessions.find(s=>s.playerId===player.id)!;t=await act(users[0]!,{type:'OFFER_FREE_AGENT',sessionId:session.id,amountUnits:20});assert.equal(t.negotiation.sessions.find(s=>s.id===session.id)!.status,'ACCEPTED');
 phase='preserved acceptance';t=await act(users[0]!,{type:'WINDOW',open:false});t=await act(users[0]!,{type:'WINDOW',open:true});assert.equal(t.negotiation.sessions.find(s=>s.id===session.id)!.lastOfferUnits,20);
 phase='trade dependencies';const a=t.players.find(p=>p.currentTeamId===teamIds[0])!,b=t.players.find(p=>p.currentTeamId===teamIds[1])!;await act(users[0]!,{type:'TRADE',offeredPlayerId:a.id,requestedPlayerId:b.id});await act(users[0]!,{type:'BUYOUT',targetPlayerId:b.id,offerType:'CASH',cashAmountUnits:10});
 phase='host deletion';await service.delete(t.id,users[0]!);assert.equal((await db`select id from public.manager_tournaments where id=${t.id}`).length,0);assert.equal((await db`select id from public.auction_rooms where id=${sourceId}`).length,1);
 console.log('PASS: persisted legacy repricing, practical external values, preserved accepted offer, transactional deletion with negotiations/trades/buyouts, source auction intact.');
 }
 if(process.argv.includes('--buyouts-only')){
 await db`update public.manager_tournaments set status='ACTIVE' where id=${t.id}`;
 await db`update public.manager_tournament_members set status='JOINED' where tournament_id=${t.id}`;
 await act(users[0]!,{type:'WINDOW',open:true});
 const target=t.players.find(p=>p.currentTeamId===teamIds[1])!,included=t.players.find(p=>p.currentTeamId===teamIds[0])!;
 let state=await act(users[0]!,{type:'BUYOUT',targetPlayerId:target.id,offerType:'CASH_PLUS_PLAYER',cashAmountUnits:40,includedPlayerId:included.id});
 state=await act(users[1]!,{type:'BUYOUT_COUNTER',buyoutId:state.buyouts![0]!.id,offerType:'CASH_PLUS_PLAYER',cashAmountUnits:56,includedPlayerId:included.id});
 const counter=state.buyouts!.at(-1)!;const same=await Promise.allSettled([act(users[0]!,{type:'BUYOUT_RESPONSE',buyoutId:counter.id,response:'ACCEPT'}),act(users[0]!,{type:'BUYOUT_RESPONSE',buyoutId:counter.id,response:'ACCEPT'})]);assert.equal(same.filter(x=>x.status==='fulfilled').length,1);
 const fresh=new ManagerModeService(new PostgresManagerTournamentRepository(db),id=>readCompletedAuction(db,id));state=await fresh.state(t.id,users[0]!);
 assert.equal(state.teams.find(x=>x.id===teamIds[0])!.transferBudgetUnits,144);assert.equal(state.teams.find(x=>x.id===teamIds[1])!.transferBudgetUnits,256);assert.equal(state.players.find(x=>x.id===target.id)!.currentTeamId,teamIds[0]);assert.equal(state.players.find(x=>x.id===included.id)!.currentTeamId,teamIds[1]);assert.equal(state.transactions.filter(x=>x.buyoutId===counter.id).length,2);
 const cash=await db`select * from public.manager_buyout_cash_movements where buyout_id=${counter.id}`;assert.equal(cash.length,1);assert.equal(Number(cash[0]!.amount_units),56);
 const privileges=await db`select has_table_privilege('authenticated','public.manager_buyout_offers','UPDATE') as write`;assert.equal(privileges[0]!.write,false);
 console.log('PASS: real Postgres linked buyout counter, competing acceptance, both budget balances, atomic player swap, two ledger entries, one cash movement, recovery and browser-role denial.');
 }
 if(process.argv.includes('--seasons-only')){
 phase='season activation';await db`update public.manager_tournament_members set status='JOINED' where tournament_id=${t.id}`;
 t=await act(users[0]!,{type:'GENERATE_FIXTURES'});const firstId=t.seasonData!.currentSeasonId;const fixture=t.fixtures[0]!;
 phase='season score';t=await act(users[0]!,{type:'SCORE',fixtureId:fixture.id,homeScore:3,awayScore:1});
 phase='concurrent season completion';const outcomes=await Promise.allSettled([act(users[0]!,{type:'END_CURRENT_SEASON',confirmation:'END SEASON'}),act(users[0]!,{type:'END_CURRENT_SEASON',confirmation:'END SEASON'})]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);
 t=await service.state(t.id,users[0]!);assert.equal(t.seasonData!.bonuses.length,8);assert.equal(t.teams.reduce((n,x)=>n+x.transferBudgetUnits,0),1852);const budgets=t.teams.map(x=>x.transferBudgetUnits);
 phase='next season';t=await act(users[0]!,{type:'START_NEXT_SEASON'});assert.deepEqual(t.teams.map(x=>x.transferBudgetUnits),budgets);assert.equal(t.fixtures.length,28);assert.ok(t.standings.every(x=>x.played===0));assert.equal(t.seasonFixturesById![firstId]!.length,28);
 phase='atomic release';await act(users[0]!,{type:'WINDOW',open:true});const player=t.players.find(x=>x.currentTeamId===teamIds[0])!;const quote=t.saleQuotes![player.id]!;const sale={type:'SELL_PLAYER',playerId:player.id,ownershipToken:quote.ownershipToken,expectedSaleUnits:quote.saleValueUnits} as const;const sales=await Promise.allSettled([act(users[0]!,sale),act(users[0]!,sale)]);assert.equal(sales.filter(x=>x.status==='fulfilled').length,1);
 phase='released player negotiation';t=await act(users[1]!,{type:'START_NEGOTIATION',playerId:player.id});assert.ok(t.negotiation.sessions.some(x=>x.playerId===player.id));
 phase='end and recovery';await act(users[0]!,{type:'END_MANAGER_MODE',confirmation:'END MANAGER MODE'});const other=connectDatabase(process.env.DATABASE_URL!);try{const fresh=new ManagerModeService(new PostgresManagerTournamentRepository(other),id=>readCompletedAuction(other,id));t=await fresh.state(t.id,users[0]!);assert.equal(t.modeStatus,'ENDED');assert.equal(t.seasonData!.bonuses.length,8);assert.equal(t.seasonData!.seasons[1]!.status,'ARCHIVED');assert.equal(t.seasonData!.seasons[1]!.championTeamId,null);assert.equal(t.transactions.filter(x=>x.type==='RELEASE').length,1);assert.equal(t.players.find(x=>x.id===player.id)!.currentTeamId,null);assert.equal(t.teams.reduce((n,x)=>n+x.transferBudgetUnits,0),1853);assert.equal(t.seasonFixturesById![firstId]!.find(x=>x.id===fixture.id)!.homeScore,3);}finally{await other.end();}
 console.log('PASS: real Postgres seasons, concurrent reward protection, new schedule, retained history, atomic release, reopened negotiation, read-only archive and fresh-connection recovery.');
 }
 if(!process.argv.includes('--imports-only')&&!process.argv.includes('--buyouts-only')&&!process.argv.includes('--seasons-only')&&!process.argv.includes('--pricing-only')&&!process.argv.includes('--squad-only')){
 phase='join and fixtures';for(const user of users.slice(1))await act(user,{type:'INVITATION',accept:true});t=await act(users[0]!,{type:'GENERATE_FIXTURES'});assert.equal(t.fixtures.length,28);
 phase='score RPC';t=await act(users[0]!,{type:'SCORE',fixtureId:t.fixtures[0]!.id,homeScore:3,awayScore:1});t=await act(users[0]!,{type:'SCORE',fixtureId:t.fixtures[0]!.id,homeScore:2,awayScore:2});assert.equal(t.standings.find(s=>s.teamId===t.fixtures[0]!.homeTeamId)!.points,1);
 const audits=await db`select event_type from public.manager_tournament_events where tournament_id=${t.id} and event_type in ('RESULT_CREATED','RESULT_EDITED')`;assert.equal(audits.length,2);
 phase='trade RPC';await act(users[0]!,{type:'WINDOW',open:true});const a=t.players.find(p=>p.currentTeamId===teamIds[0])!,b=t.players.find(p=>p.currentTeamId===teamIds[1])!;t=await act(users[0]!,{type:'TRADE',offeredPlayerId:a.id,requestedPlayerId:b.id});const request=randomUUID();t=await act(users[1]!,{type:'TRADE_RESPONSE',tradeId:t.trades[0]!.id,response:'ACCEPT'},request);assert.equal(t.players.find(p=>p.id===a.id)!.currentTeamId,teamIds[1]);assert.equal(t.transactions.filter(x=>x.type==='TRADE').length,2);assert.equal((await act(users[1]!,{type:'TRADE_RESPONSE',tradeId:t.trades[0]!.id,response:'ACCEPT'},request)).sequence,t.sequence);
 phase='negotiation signing';const free=t.players.find(p=>!p.currentTeamId)!;t=await act(users[0]!,{type:'START_NEGOTIATION',playerId:free.id});const session=t.negotiation.sessions[0]!;t=await act(users[0]!,{type:'OFFER_FREE_AGENT',sessionId:session.id,amountUnits:80});assert.equal(t.negotiation.sessions[0]!.status,'ACCEPTED');const rivalState=await act(users[1]!,{type:'START_NEGOTIATION',playerId:free.id});const rival=rivalState.negotiation.sessions.find(s=>s.playerId===free.id)!;await act(users[1]!,{type:'OFFER_FREE_AGENT',sessionId:rival.id,amountUnits:80});
 const confirmations=await Promise.allSettled([act(users[0]!,{type:'CONFIRM_SIGNING',sessionId:session.id}),act(users[1]!,{type:'CONFIRM_SIGNING',sessionId:rival.id})]);assert.equal(confirmations.filter(x=>x.status==='fulfilled').length,1);t=await service.state(t.id,users[0]!);
 const winner=t.players.find(p=>p.id===free.id)!.currentTeamId!;assert.equal(t.teams.find(x=>x.id===winner)!.transferBudgetUnits,120);assert.equal(t.teams.filter(x=>x.transferBudgetUnits===120).length,1);
assert.equal(t.transactions.filter(x=>x.type==='FREE_AGENT_SIGNING').length,1);
 phase='fresh connection restart';const other=connectDatabase(process.env.DATABASE_URL!);try{const restarted=new ManagerModeService(new PostgresManagerTournamentRepository(other),id=>readCompletedAuction(other,id));const state=await restarted.state(t.id,users[0]!);assert.equal(state.fixtures.length,28);assert.equal(state.fixtures[0]!.homeScore,2);assert.equal(state.teams.find(x=>x.id===winner)!.transferBudgetUnits,120);assert.equal(state.negotiation.sessions[0]!.status,winner===teamIds[0]?'SIGNED':'CLOSED_LOST_PLAYER');assert.ok(state.notifications.length);assert.ok(!JSON.stringify(state).includes('minimumValueUnits'));}finally{await other.end();}
 const privateEvents=await db`select metadata from public.manager_tournament_events where tournament_id=${t.id} and metadata->'action'->>'type'='OFFER_FREE_AGENT'`;assert.ok(privateEvents.length);for(const e of privateEvents){assert.deepEqual(Object.keys(e.metadata.action),['type']);assert.match(e.metadata.receipt.fingerprint,/^[a-f0-9]{64}$/);}
 phase='RLS';const permissions=await db`select has_table_privilege('authenticated','public.manager_negotiation_sessions','UPDATE') as write,has_table_privilege('authenticated','public.manager_player_negotiation_profiles','SELECT') as secrets,has_function_privilege('authenticated','public.accept_manager_trade(uuid,uuid)','EXECUTE') as rpc`;assert.equal(permissions[0]!.write,false);assert.equal(permissions[0]!.secrets,false);assert.equal(permissions[0]!.rpc,false);
 }
 if(!process.argv.includes('--buyouts-only')&&!process.argv.includes('--seasons-only')&&!process.argv.includes('--pricing-only')&&!process.argv.includes('--squad-only'))console.log(process.argv.includes('--imports-only')?'PASS: completed snapshot, duplicate creation, 192 owned/70 free, persisted import batch and 50 audit rows.':'PASS: real Postgres snapshot, duplicate creation, 8 memberships, 192 owned/70 free, 28 fixtures, score RPC correction, atomic trade RPC, competing signings, fresh-connection recovery, hidden-profile and RPC permissions.');
}catch(error){const e=error as {code?:string;message?:string};console.error(JSON.stringify({phase,code:e.code??'TEST_FAILED',message:e.message?.includes('postgres://')?'Redacted database error':e.message}));process.exitCode=1;}
finally{
 try{await db.begin(async tx=>{if(tournamentId){await tx`delete from public.manager_free_agent_offers where session_id in (select id from public.manager_negotiation_sessions where tournament_id=${tournamentId})`;await tx`delete from public.manager_negotiation_sessions where tournament_id=${tournamentId}`;await tx`delete from public.manager_tournaments where id=${tournamentId}`;};await tx`delete from public.auction_rooms where id=${sourceId}`;await tx`delete from public.football_players where external_id like ${run+'-%'}`;await tx`delete from auth.users where id in ${tx(users)}`;});console.log('Isolated integration fixtures removed.');}catch{console.error('Fixture cleanup failed; run ID '+run);process.exitCode=1;}await db.end();
}
