import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {connectDatabase} from '../src/repositories/postgres.js';
import {PostgresManagerTournamentRepository} from '../src/modules/manager-mode/postgres-manager.repository.js';
import {ManagerModeService} from '../src/modules/manager-mode/manager.service.js';
import {archiveCompletedAuction} from '../src/modules/manager-mode/completed-auction-archive.js';
import {readCompletedAuction} from '../src/modules/manager-mode/auction-snapshot.repository.js';
import {settingsSchema} from '../src/schemas/settings.js';
import type {Room} from '../src/domain/types.js';
if(process.env.MANAGER_DB_TEST_ALLOW_WRITES!=='1'&&!process.argv.includes('--write-fixtures'))throw Error('Set MANAGER_DB_TEST_ALLOW_WRITES=1 to create and remove isolated integration fixtures.');
const db=connectDatabase(process.env.DATABASE_URL!);const run=randomUUID(),users=Array.from({length:8},()=>randomUUID()),teamIds=users.map(()=>randomUUID());const sourceId=randomUUID();let tournamentId:string|undefined;
const room:Room={id:sourceId,code:run.replace(/[^A-F2-9]/gi,'').toUpperCase().padEnd(6,'A').slice(0,6),hostUserId:users[0]!,auctionName:'Manager persistence integration '+run,status:'COMPLETED',createdAt:Date.now(),settings:settingsSchema.parse({numberOfTeams:8,startingBudgetCr:200,minSquadSize:1,maxSquadSize:24}),teams:users.map((userId,i)=>({id:teamIds[i]!,userId,name:'Test Team '+i,startingBudgetUnits:400,spentUnits:48,playerIds:Array.from({length:24},(_,j)=>run+'-p'+(i*24+j))})),players:Array.from({length:212},(_,i)=>({id:run+'-p'+i,name:'Test Player '+i,ovr:82,position:'MID',subPosition:'CM',stats:{passing:80},basePriceUnits:2,potId:'test',status:i<192?'SOLD':'UNSOLD',round:1})),purchases:[],bids:[],active:null,playerQueue:[],sequence:5,nextPlayerAt:null,receipts:{}};
room.purchases=room.teams.flatMap(t=>t.playerIds.map(id=>({id:randomUUID(),playerId:id,teamId:t.id,priceUnits:2,bidCount:1,at:Date.now(),durationMs:1})));
let phase='fixture users';
try{
 await db.begin(async tx=>{for(let i=0;i<users.length;i++)await tx`insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_user_meta_data,created_at,updated_at) values(${users[i]!},'00000000-0000-0000-0000-000000000000','authenticated','authenticated',${'mm-test-'+run+'-'+i+'@example.invalid'},now(),${tx.json({username:'mmtest_'+run.slice(0,8)+'_'+i})},now(),now())`;});
 phase='archive completed snapshot';await archiveCompletedAuction(db,room,users[0]!);const persisted=(await readCompletedAuction(db,sourceId))!;assert.equal(persisted.players.length,212);
 const service=new ManagerModeService(new PostgresManagerTournamentRepository(db),id=>readCompletedAuction(db,id));
 phase='create';let t=await service.create(sourceId,users[0]!,{name:'Integration tournament',csv:'player_id,name,overall,position\n'+Array.from({length:50},(_,i)=>run+'-external'+i+',External '+i+',82,CB').join('\n')});tournamentId=t.id;assert.equal(t.players.filter(p=>p.currentTeamId).length,192);assert.equal(t.players.filter(p=>!p.currentTeamId).length,70);
 assert.equal((await service.create(sourceId,users[0]!,{name:'Duplicate'})).id,t.id);
 const act=(user:string,action:Parameters<typeof service.mutate>[3],request=randomUUID())=>service.mutate(t.id,user,request,action);
 const imports=await db`select id,valid_rows from public.manager_external_player_imports where tournament_id=${t.id}`;assert.equal(imports.length,1);assert.equal(imports[0]!.valid_rows,50);const imported=await db`select count(*)::int as count from public.manager_external_player_import_rows where import_id=${imports[0]!.id}`;assert.equal(imported[0]!.count,50);
 if(!process.argv.includes('--imports-only')){
 phase='join and fixtures';for(const user of users.slice(1))await act(user,{type:'INVITATION',accept:true});t=await act(users[0]!,{type:'GENERATE_FIXTURES'});assert.equal(t.fixtures.length,28);
 phase='score RPC';t=await act(users[0]!,{type:'SCORE',fixtureId:t.fixtures[0]!.id,homeScore:3,awayScore:1});t=await act(users[0]!,{type:'SCORE',fixtureId:t.fixtures[0]!.id,homeScore:2,awayScore:2});assert.equal(t.standings.find(s=>s.teamId===t.fixtures[0]!.homeTeamId)!.points,1);
 const audits=await db`select event_type from public.manager_tournament_events where tournament_id=${t.id} and event_type in ('RESULT_CREATED','RESULT_EDITED')`;assert.equal(audits.length,2);
 phase='trade RPC';await act(users[0]!,{type:'WINDOW',open:true});const a=t.players.find(p=>p.currentTeamId===teamIds[0])!,b=t.players.find(p=>p.currentTeamId===teamIds[1])!;t=await act(users[0]!,{type:'TRADE',offeredPlayerId:a.id,requestedPlayerId:b.id});const request=randomUUID();t=await act(users[1]!,{type:'TRADE_RESPONSE',tradeId:t.trades[0]!.id,response:'ACCEPT'},request);assert.equal(t.players.find(p=>p.id===a.id)!.currentTeamId,teamIds[1]);assert.equal(t.transactions.filter(x=>x.type==='TRADE').length,2);assert.equal((await act(users[1]!,{type:'TRADE_RESPONSE',tradeId:t.trades[0]!.id,response:'ACCEPT'},request)).sequence,t.sequence);
 phase='negotiation signing';const free=t.players.find(p=>!p.currentTeamId)!;t=await act(users[0]!,{type:'START_NEGOTIATION',playerId:free.id});const session=t.negotiation.sessions[0]!;t=await act(users[0]!,{type:'OFFER_FREE_AGENT',sessionId:session.id,amountUnits:80});assert.equal(t.negotiation.sessions[0]!.status,'ACCEPTED');const rivalState=await act(users[1]!,{type:'START_NEGOTIATION',playerId:free.id});const rival=rivalState.negotiation.sessions.find(s=>s.playerId===free.id)!;await act(users[1]!,{type:'OFFER_FREE_AGENT',sessionId:rival.id,amountUnits:80});
 const confirmations=await Promise.allSettled([act(users[0]!,{type:'CONFIRM_SIGNING',sessionId:session.id}),act(users[1]!,{type:'CONFIRM_SIGNING',sessionId:rival.id})]);assert.equal(confirmations.filter(x=>x.status==='fulfilled').length,1);t=await service.state(t.id,users[0]!);
 const winner=t.players.find(p=>p.id===free.id)!.currentTeamId!;assert.equal(t.teams.find(x=>x.id===winner)!.transferBudgetUnits,120);assert.equal(t.teams.filter(x=>x.transferBudgetUnits===120).length,1);
assert.equal(t.transactions.filter(x=>x.type==='FREE_AGENT_SIGNING').length,1);
 phase='fresh connection restart';const other=connectDatabase(process.env.DATABASE_URL!);try{const restarted=new ManagerModeService(new PostgresManagerTournamentRepository(other),id=>readCompletedAuction(other,id));const state=await restarted.state(t.id,users[0]!);assert.equal(state.fixtures.length,28);assert.equal(state.fixtures[0]!.homeScore,2);assert.equal(state.teams.find(x=>x.id===winner)!.transferBudgetUnits,120);assert.equal(state.negotiation.sessions[0]!.status,winner===teamIds[0]?'SIGNED':'CLOSED_LOST_PLAYER');assert.ok(state.notifications.length);assert.ok(!JSON.stringify(state).includes('minimumValueUnits'));}finally{await other.end();}
 const privateEvents=await db`select metadata from public.manager_tournament_events where tournament_id=${t.id} and metadata->'action'->>'type'='OFFER_FREE_AGENT'`;assert.ok(privateEvents.length);for(const e of privateEvents){assert.deepEqual(Object.keys(e.metadata.action),['type']);assert.match(e.metadata.receipt.fingerprint,/^[a-f0-9]{64}$/);}
 phase='RLS';const permissions=await db`select has_table_privilege('authenticated','public.manager_negotiation_sessions','UPDATE') as write,has_table_privilege('authenticated','public.manager_player_negotiation_profiles','SELECT') as secrets,has_function_privilege('authenticated','public.accept_manager_trade(uuid,uuid)','EXECUTE') as rpc`;assert.equal(permissions[0]!.write,false);assert.equal(permissions[0]!.secrets,false);assert.equal(permissions[0]!.rpc,false);
 }
 console.log(process.argv.includes('--imports-only')?'PASS: completed snapshot, duplicate creation, 192 owned/70 free, persisted import batch and 50 audit rows.':'PASS: real Postgres snapshot, duplicate creation, 8 memberships, 192 owned/70 free, 28 fixtures, score RPC correction, atomic trade RPC, competing signings, fresh-connection recovery, hidden-profile and RPC permissions.');
}catch(error){const e=error as {code?:string;message?:string};console.error(JSON.stringify({phase,code:e.code??'TEST_FAILED',message:e.message?.includes('postgres://')?'Redacted database error':e.message}));process.exitCode=1;}
finally{
 try{await db.begin(async tx=>{if(tournamentId){await tx`delete from public.manager_free_agent_offers where session_id in (select id from public.manager_negotiation_sessions where tournament_id=${tournamentId})`;await tx`delete from public.manager_negotiation_sessions where tournament_id=${tournamentId}`;await tx`delete from public.manager_tournaments where id=${tournamentId}`;};await tx`delete from public.auction_rooms where id=${sourceId}`;await tx`delete from public.football_players where external_id like ${run+'-%'}`;await tx`delete from auth.users where id in ${tx(users)}`;});console.log('Isolated integration fixtures removed.');}catch{console.error('Fixture cleanup failed; run ID '+run);process.exitCode=1;}await db.end();
}
