import {createHash,randomUUID} from 'node:crypto';
import {requireThat} from '../../../domain/errors.js';
import {standings} from '../fixture.service.js';
import type {Tournament,ManagerPlayer} from '../manager.types.js';
import {archetypes,type NegotiationData,type NegotiationProfile,type NegotiationSession,type Decision,type Emotion,type NegotiationView} from './negotiation.types.js';
export const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
export function profileFor(tournamentId:string,p:ManagerPlayer):NegotiationProfile{
 const bytes=createHash('sha256').update(tournamentId+':'+p.id).digest();const archetype=archetypes[bytes[0]!%archetypes.length]!;const base=.35+bytes[1]!/255*.3;
 const value=Math.max(4,Math.round((p.overall-60)*1.5+(p.age&&p.age<25?4:0)+(['ST','RW','LW'].includes(p.position)?3:0)+(p.source==='EXTERNAL_POOL'?1:0)+(p.tier==='elite'?3:0)));
 const profile:NegotiationProfile={playerId:p.id,archetype,moneyImportance:base,prestigeImportance:base,playingTimeImportance:base,squadStrengthImportance:base,patience:base,ego:base,loyalty:base,competitiveness:base,negotiationAggression:base,compromiseWillingness:base,marketValueUnits:value,minimumValueUnits:Math.round(value*.75),preferredValueUnits:value,idealValueUnits:Math.round(value*1.3)};
 const patches:Record<typeof archetype,Partial<NegotiationProfile>>={BALANCED:{},MONEY_DRIVEN:{moneyImportance:1,prestigeImportance:.15,playingTimeImportance:.2},AMBITIOUS:{prestigeImportance:.9,squadStrengthImportance:.9,competitiveness:.9},PLAYING_TIME_FOCUSED:{playingTimeImportance:1,moneyImportance:.35},PRESTIGE_DRIVEN:{prestigeImportance:1,ego:.8},LOYAL:{loyalty:1,compromiseWillingness:.8},STUBBORN:{patience:.2,ego:.9,negotiationAggression:.9,compromiseWillingness:.15},OPPORTUNISTIC:{moneyImportance:.85,competitiveness:.9,loyalty:.1},COMPETITIVE:{competitiveness:1,squadStrengthImportance:.9},RELAXED:{patience:.95,compromiseWillingness:.95,ego:.2,negotiationAggression:.2}};
 return {...profile,...patches[archetype]};
}
export function ensureNegotiations(t:Tournament):NegotiationData{const data=t.negotiation??={rules:{difficulty:'NORMAL',visibility:'SEMI_TRANSPARENT',offerCooldownMs:3000,walkAwayCooldownMs:180000},profiles:[],sessions:[],offers:[],messages:[]};for(const p of t.players)if(p.source!=='AUCTION_SQUAD'&&!data.profiles.some(x=>x.playerId===p.id))data.profiles.push(profileFor(t.id,p));return data;}
export function mood(s:NegotiationSession):Emotion{if(s.status==='SIGNED')return 'SATISFIED';if(s.status==='ACCEPTED')return 'READY_TO_SIGN';if(s.frustration>=85)return 'OFFENDED';if(s.frustration>=70)return 'ANNOYED';if(s.frustration>=50)return 'FRUSTRATED';if(s.patienceRemaining<20)return 'IMPATIENT';if(s.excitement>=85)return 'EXCITED';if(s.interest>=85)return 'IMPRESSED';if(s.interest>=65)return 'INTERESTED';if(s.confidence>=80)return 'CONFIDENT';if(s.trust<30)return 'DISAPPOINTED';if(s.interest<35)return 'HESITANT';if(s.interest>50)return 'CURIOUS';return 'NEUTRAL';}
export function competition(t:Tournament,s:NegotiationSession){return (t.negotiation?.sessions??[]).filter(x=>x.playerId===s.playerId&&x.teamId!==s.teamId&&['ACTIVE','ACCEPTED'].includes(x.status)&&x.lastOfferUnits!==null&&(t.teams.find(team=>team.id===x.teamId)?.transferBudgetUnits??0)>=x.lastOfferUnits);}
export function publicNegotiations(t:Tournament,teamId:string):NegotiationView{const data=ensureNegotiations(t);return {rules:data.rules,sessions:data.sessions.filter(s=>s.teamId===teamId).map(s=>{const rivals=competition(t,s),highest=Math.max(0,...rivals.map(x=>x.lastOfferUnits??0));return {id:s.id,playerId:s.playerId,teamId:s.teamId,status:s.status,mood:mood(s),lastOfferUnits:s.lastOfferUnits,lastCounterUnits:s.lastCounterUnits,cooldownUntil:s.cooldownUntil,nextOfferAt:s.lastOfferAt===null?null:s.lastOfferAt+data.rules.offerCooldownMs,messages:data.messages.filter(m=>m.sessionId===s.id),offers:data.offers.filter(o=>o.sessionId===s.id),competition:{count:rivals.length,...(data.rules.visibility!=='PRIVATE'?{higherOffer:highest>(s.lastOfferUnits??0)}:{}),...(data.rules.visibility==='TRANSPARENT'?{highestOfferUnits:highest}:{})}};}),market:Object.fromEntries(data.profiles.map(p=>{const player=t.players.find(x=>x.id===p.playerId)!;const count=data.sessions.filter(s=>s.playerId===p.playerId&&['ACTIVE','ACCEPTED'].includes(s.status)).length;return [p.playerId,{estimatedMinUnits:Math.max(1,Math.round(p.marketValueUnits*.85)),estimatedMaxUnits:Math.round(p.marketValueUnits*1.2),interestedClubs:count,availability:player.currentTeamId?'SIGNED':count?'NEGOTIATING':'AVAILABLE'}];}))};}
export function evaluate(t:Tournament,s:NegotiationSession,p:NegotiationProfile,amount:number){const player=t.players.find(x=>x.id===s.playerId)!;const data=ensureNegotiations(t),old=s.lastOfferUnits??0,low=amount<p.minimumValueUnits;
 s.patienceRemaining=clamp(s.patienceRemaining-(low?20:amount>old+4?2:5));s.frustration=clamp(s.frustration+(low?20:amount>old+4?-15:3));s.trust=clamp(s.trust+(low?-10:amount>old+4?5:0));s.interest=clamp(amount/p.preferredValueUnits*70);s.excitement=clamp(s.excitement+(amount>old+4?12:0));
 const squad=t.players.filter(x=>x.currentTeamId===s.teamId);const top=[...squad].sort((a,b)=>b.overall-a.overall).slice(0,11);const strength=top.length?top.reduce((n,p)=>n+p.overall,0)/top.length:50;
 const table=standings(t.teams,t.fixtures),row=table.find(x=>x.teamId===s.teamId)!;const league=row.played?100-(row.position-1)*80/Math.max(1,t.teams.length-1):50;
 const prestige=clamp(strength*.6+league*.25+Math.min(10,row.won*2)+Math.max(-5,Math.min(5,row.gd)));
 const playing=clamp(100-squad.filter(x=>x.position===player.position&&x.overall>=player.overall).length*30);
 const financial=clamp(amount/p.preferredValueUnits*85);const weights=[p.moneyImportance*3,p.prestigeImportance,p.playingTimeImportance,p.squadStrengthImportance,p.loyalty*.5];const score=clamp((financial*weights[0]!+prestige*weights[1]!+playing*weights[2]!+strength*weights[3]!+s.trust*weights[4]!)/weights.reduce((a,b)=>a+b,0));
 const rivals=competition(t,s),highest=Math.max(0,...rivals.map(x=>x.lastOfferUnits??0));const threshold=70+(data.rules.difficulty==='HARD'?6:data.rules.difficulty==='RELAXED'?-6:0)+Math.round(p.negotiationAggression*5-p.compromiseWillingness*5);
 let decision:Decision=low?'REJECT':score>=threshold?'ACCEPT':score>=55?'COUNTER':'REJECT';
 if(s.patienceRemaining<=0||s.frustration>=95)decision='WALK_AWAY';else if(!low&&highest>amount){decision=p.competitiveness>.7?'CONSIDER':'WAIT';}else if(low&&amount>=p.minimumValueUnits*.85)decision='COUNTER';
 const counter=decision==='COUNTER'?Math.min(p.idealValueUnits,Math.max(p.preferredValueUnits,amount+Math.ceil(p.negotiationAggression*4))):null;
 return {decision,counter,score};
}
export const phrase=(d:Decision,counter:number|null)=>({REJECT:'That proposal does not meet my expectations.',COUNTER:`We are getting closer. I would need ₹${(counter??0)/2} Cr to move this forward.`,CONSIDER:'This is a serious proposal. I want to compare my options.',ACCEPT:'I am happy with this proposal. Confirm the signing when you are ready.',WAIT:'I have other interest to consider before committing.',WALK_AWAY:'I do not think we can reach an agreement right now.'}[d]);
export function playerMessage(data:NegotiationData,s:NegotiationSession,message:string,decision:Decision|null,now:number){data.messages.push({id:randomUUID(),sessionId:s.id,sender:'PLAYER',message,emotion:mood(s),decision,provider:'TEMPLATE',createdAt:now});}
export type NegotiationAction={type:'START_NEGOTIATION';playerId:string}|{type:'OFFER_FREE_AGENT';sessionId:string;amountUnits:number}|{type:'END_NEGOTIATION';sessionId:string}|{type:'CONFIRM_SIGNING';sessionId:string}|{type:'TRANSFER_RULES';difficulty:'RELAXED'|'NORMAL'|'HARD';visibility:'PRIVATE'|'SEMI_TRANSPARENT'|'TRANSPARENT';walkAwayCooldownMs:number};
export function negotiationAction(t:Tournament,user:string,a:NegotiationAction,now=Date.now()){
 const data=ensureNegotiations(t),team=t.teams.find(x=>x.managerUserId===user)!;requireThat(team?.invitation==='JOINED','NOT_TOURNAMENT_MEMBER','Joined tournament membership required.',403);
 if(a.type==='TRANSFER_RULES'){requireThat(t.hostUserId===user,'HOST_ONLY','Only the host may change transfer rules.',403);data.rules={...data.rules,difficulty:a.difficulty,visibility:a.visibility,walkAwayCooldownMs:a.walkAwayCooldownMs};return;}
 requireThat(t.status==='ACTIVE','INVALID_STATE','Tournament must be active.');
 if(a.type!=='END_NEGOTIATION')requireThat(t.transferWindowOpen,'TRANSFER_WINDOW_CLOSED','The transfer window is closed.');
 if(a.type==='START_NEGOTIATION'){
 const p=t.players.find(p=>p.id===a.playerId);requireThat(p,'PLAYER_NOT_FOUND','Player not found.',404);requireThat(!p.currentTeamId&&p.ownershipStatus==='FREE_AGENT','PLAYER_ALREADY_SIGNED','This player has already signed.',409);
 let s=data.sessions.find(s=>s.playerId===p.id&&s.teamId===team.id);if(s&&['ACTIVE','ACCEPTED'].includes(s.status))return;
 requireThat(!s?.cooldownUntil||s.cooldownUntil<=now,'NEGOTIATION_COOLDOWN','This player needs time before reopening talks.',429);
 const profile=data.profiles.find(x=>x.playerId===p.id)!;const base={status:'ACTIVE' as const,resumeStatus:null,interest:50,trust:50,frustration:10,excitement:20,patienceRemaining:clamp(40+profile.patience*50+(data.rules.difficulty==='RELAXED'?10:data.rules.difficulty==='HARD'?-10:0)),confidence:50,lastOfferUnits:null,lastCounterUnits:null,lastOfferAt:null,cooldownUntil:null,updatedAt:now,closedAt:null};
 if(s)Object.assign(s,base);else{ s={id:randomUUID(),playerId:p.id,teamId:team.id,managerUserId:user,createdAt:now,...base};data.sessions.push(s); }playerMessage(data,s,'I am open to hearing your proposal.',null,now);return;
 }
 const s=data.sessions.find(x=>x.id===a.sessionId);requireThat(s&&s.managerUserId===user&&s.teamId===team.id,'NEGOTIATION_PERMISSION','You do not control this negotiation.',403);const player=t.players.find(p=>p.id===s.playerId)!;
 if(a.type==='END_NEGOTIATION'){requireThat(['ACTIVE','ACCEPTED','PAUSED_WINDOW_CLOSED'].includes(s.status),'SESSION_CLOSED','Negotiation is closed.',409);s.status='WALKED_AWAY';s.closedAt=now;s.cooldownUntil=now+data.rules.walkAwayCooldownMs;playerMessage(data,s,'We can revisit this after some time apart.','WALK_AWAY',now);return;}
 requireThat(!player.currentTeamId&&player.ownershipStatus==='FREE_AGENT','PLAYER_ALREADY_SIGNED','This player has signed elsewhere.',409);
 if(a.type==='CONFIRM_SIGNING'){
 requireThat(s.status==='ACCEPTED'&&s.lastOfferUnits!==null,'OFFER_NOT_ACCEPTED','The player must accept your offer first.',409);requireThat(team.transferBudgetUnits>=s.lastOfferUnits,'INSUFFICIENT_BUDGET','Your current transfer budget is too low.',409);
 team.transferBudgetUnits-=s.lastOfferUnits;player.currentTeamId=team.id;player.ownershipStatus='OWNED';player.availability='SIGNED';player.acquisitionType='FREE_AGENT_SIGNING';player.acquisitionPriceUnits=s.lastOfferUnits;s.status='SIGNED';s.closedAt=now;s.updatedAt=now;
 t.transactions.push({id:randomUUID(),playerId:player.id,fromTeamId:null,toTeamId:team.id,type:'FREE_AGENT_SIGNING',amountUnits:s.lastOfferUnits,tradeId:null,at:now});
 for(const other of data.sessions.filter(x=>x.playerId===player.id&&x.id!==s.id&&['ACTIVE','ACCEPTED','PAUSED_WINDOW_CLOSED'].includes(x.status))){other.status='CLOSED_LOST_PLAYER';other.closedAt=now;other.updatedAt=now;playerMessage(data,other,`${player.name} has signed for ${team.name}.`,null,now);}
 playerMessage(data,s,'The signing is complete. I look forward to joining the squad.','ACCEPT',now);return;
 }
 requireThat(s.status==='ACTIVE','SESSION_CLOSED','Negotiation is not accepting offers.',409);requireThat(Number.isSafeInteger(a.amountUnits)&&a.amountUnits>0,'INVALID_OFFER','Use a positive whole number of half-crore units.');requireThat(a.amountUnits<=team.transferBudgetUnits,'INSUFFICIENT_BUDGET','Offer exceeds your available budget.');requireThat(s.lastOfferAt===null||now-s.lastOfferAt>=data.rules.offerCooldownMs,'OFFER_COOLDOWN','Wait a few seconds between offers.',429);
 const result=evaluate(t,s,data.profiles.find(p=>p.playerId===s.playerId)!,a.amountUnits);s.lastOfferUnits=a.amountUnits;s.lastCounterUnits=result.counter;s.lastOfferAt=now;s.updatedAt=now;
 if(result.decision==='ACCEPT')s.status='ACCEPTED';if(result.decision==='WALK_AWAY'){s.status='WALKED_AWAY';s.closedAt=now;s.cooldownUntil=now+data.rules.walkAwayCooldownMs;}
 data.offers.push({id:randomUUID(),sessionId:s.id,playerId:s.playerId,teamId:s.teamId,offerUnits:a.amountUnits,decision:result.decision,counterUnits:result.counter,emotion:mood(s),createdAt:now});data.messages.push({id:randomUUID(),sessionId:s.id,sender:'MANAGER',message:`I offer ₹${a.amountUnits/2} Cr.`,emotion:null,decision:null,provider:'TEMPLATE',createdAt:now});playerMessage(data,s,phrase(result.decision,result.counter),result.decision,now);
}
export function synchronizeWindow(t:Tournament){const data=ensureNegotiations(t);for(const s of data.sessions){if(!t.transferWindowOpen&&['ACTIVE','ACCEPTED'].includes(s.status)){s.resumeStatus=s.status as 'ACTIVE'|'ACCEPTED';s.status='PAUSED_WINDOW_CLOSED';}else if(t.transferWindowOpen&&s.status==='PAUSED_WINDOW_CLOSED'){const p=t.players.find(p=>p.id===s.playerId);s.status=p?.currentTeamId?'CLOSED_LOST_PLAYER':s.resumeStatus??'ACTIVE';s.resumeStatus=null;}}}
