export const archetypes=['BALANCED','MONEY_DRIVEN','AMBITIOUS','PLAYING_TIME_FOCUSED','PRESTIGE_DRIVEN','LOYAL','STUBBORN','OPPORTUNISTIC','COMPETITIVE','RELAXED'] as const;
export type Archetype=typeof archetypes[number];
export type Decision='REJECT'|'COUNTER'|'CONSIDER'|'ACCEPT'|'WAIT'|'WALK_AWAY';
export type Emotion='NEUTRAL'|'CURIOUS'|'INTERESTED'|'IMPRESSED'|'EXCITED'|'HESITANT'|'DISAPPOINTED'|'FRUSTRATED'|'ANNOYED'|'OFFENDED'|'IMPATIENT'|'CONFIDENT'|'SATISFIED'|'READY_TO_SIGN';
export interface NegotiationProfile{playerId:string;archetype:Archetype;moneyImportance:number;prestigeImportance:number;playingTimeImportance:number;squadStrengthImportance:number;patience:number;ego:number;loyalty:number;competitiveness:number;negotiationAggression:number;compromiseWillingness:number;marketValueUnits:number;minimumValueUnits:number;preferredValueUnits:number;idealValueUnits:number;}
export interface TransferRules{difficulty:'RELAXED'|'NORMAL'|'HARD';visibility:'PRIVATE'|'SEMI_TRANSPARENT'|'TRANSPARENT';offerCooldownMs:number;walkAwayCooldownMs:number}
export interface NegotiationSession{id:string;playerId:string;teamId:string;managerUserId:string;status:'ACTIVE'|'ACCEPTED'|'REJECTED'|'WALKED_AWAY'|'SIGNED'|'CLOSED_LOST_PLAYER'|'PAUSED_WINDOW_CLOSED';resumeStatus:'ACTIVE'|'ACCEPTED'|null;interest:number;trust:number;frustration:number;excitement:number;patienceRemaining:number;confidence:number;lastOfferUnits:number|null;lastCounterUnits:number|null;lastOfferAt:number|null;cooldownUntil:number|null;createdAt:number;updatedAt:number;closedAt:number|null;}
export interface NegotiationOffer{id:string;sessionId:string;playerId:string;teamId:string;offerUnits:number;decision:Decision;counterUnits:number|null;emotion:Emotion;createdAt:number;}
export interface NegotiationMessage{id:string;sessionId:string;sender:'PLAYER'|'MANAGER'|'SYSTEM';message:string;emotion:Emotion|null;decision:Decision|null;provider:'TEMPLATE'|'LLM';createdAt:number}
export interface NegotiationData{rules:TransferRules;profiles:NegotiationProfile[];sessions:NegotiationSession[];offers:NegotiationOffer[];messages:NegotiationMessage[]}
export interface PublicNegotiationSession{ id:string;playerId:string;teamId:string;status:NegotiationSession['status'];mood:Emotion;lastOfferUnits:number|null;lastCounterUnits:number|null;cooldownUntil:number|null;nextOfferAt:number|null;messages:NegotiationMessage[];offers:NegotiationOffer[];competition:{count:number;higherOffer?:boolean;highestOfferUnits?:number};}
export interface NegotiationView{rules:TransferRules;sessions:PublicNegotiationSession[];market:Record<string,{estimatedMinUnits:number;estimatedMaxUnits:number;interestedClubs:number;availability:'AVAILABLE'|'NEGOTIATING'|'SIGNED'}>}
