import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import type {Room} from '../src/domain/types.js';
import {settingsSchema} from '../src/schemas/settings.js';
import {MemoryManagerRepository} from '../src/modules/manager-mode/manager.repository.js';
import {ManagerModeService} from '../src/modules/manager-mode/manager.service.js';
export function source(): Room { const teams = Array.from({ length: 8 }, (_, i) => ({ id: 'team' + i, userId: 'user' + i, name: 'Team ' + i, startingBudgetUnits: 400, spentUnits: 48, playerIds: Array.from({ length: 24 }, (_, j) => 'p' + (i * 24 + j)) })); return { id: 'auction-id', code: 'ABC234', hostUserId: 'user0', auctionName: 'Acceptance League', status: 'COMPLETED', createdAt: 1, settings: settingsSchema.parse({ numberOfTeams: 8, startingBudgetCr: 200, maxSquadSize: 24 }), teams, players: Array.from({ length: 212 }, (_, i) => ({ id: 'p' + i, name: 'Player ' + i, position: 'MID', subPosition: 'CM', ovr: 80, stats: { passing: 80 }, basePriceUnits: 2, potId: 'gold', status: i < 192 ? 'SOLD' : 'UNSOLD', round: 1 })), purchases: teams.flatMap(t => t.playerIds.map(playerId => ({ id: randomUUID(), playerId, teamId: t.id, priceUnits: 2, bidCount: 1, at: 1, durationMs: 1000 }))), active: null, playerQueue: [], bids: [], sequence: 50, nextPlayerAt: null, receipts: {} }; }
async function setup(){const repo=new MemoryManagerRepository(),room=source(),service=new ManagerModeService(repo,async()=>room);const state=await service.create(room.id,'user0',{addUnusedAuctionPurse:false,name:'Buyout test'});await repo.mutate(state.id,t=>{t.status='ACTIVE';t.transferWindowOpen=true;for(const x of t.teams)x.invitation='JOINED';});const act=(user:string,a:Parameters<typeof service.mutate>[3],id=randomUUID())=>service.mutate(state.id,user,id,a);return {repo,service,state,act};}
it('cash buyout credits seller, debits buyer, persists ownership and deduplicates acceptance',async()=>{const f=await setup(),created=await f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH',cashAmountUnits:70});const offer=created.buyouts![0]!,id=randomUUID();const result=await f.act('user1',{type:'BUYOUT_RESPONSE',buyoutId:offer.id,response:'ACCEPT'},id);expect(result.teams[0]!.transferBudgetUnits).toBe(130);expect(result.teams[1]!.transferBudgetUnits).toBe(270);expect(result.players.find(p=>p.id==='p24')!.currentTeamId).toBe('team0');expect(result.transactions.filter(x=>x.type==='BUYOUT')).toHaveLength(1);expect((await f.act('user1',{type:'BUYOUT_RESPONSE',buyoutId:offer.id,response:'ACCEPT'},id)).sequence).toBe(result.sequence);});
it('linked seller counter changes terms and buyer must accept; cash and both players move together',async()=>{const f=await setup(),original=await f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH_PLUS_PLAYER',cashAmountUnits:40,includedPlayerId:'p0'});const response=await f.act('user1',{type:'BUYOUT_COUNTER',buyoutId:original.buyouts![0]!.id,offerType:'CASH_PLUS_PLAYER',cashAmountUnits:56,includedPlayerId:'p1'});expect(response.buyouts![0]!.status).toBe('COUNTERED');const counter=response.buyouts![1]!;expect(counter.parentBuyoutId).toBe(original.buyouts![0]!.id);await expect(f.act('user1',{type:'BUYOUT_RESPONSE',buyoutId:counter.id,response:'ACCEPT'})).rejects.toMatchObject({code:'BUYOUT_PERMISSION'});const result=await f.act('user0',{type:'BUYOUT_RESPONSE',buyoutId:counter.id,response:'ACCEPT'});expect(result.teams[0]!.transferBudgetUnits).toBe(144);expect(result.teams[1]!.transferBudgetUnits).toBe(256);expect(result.players.find(p=>p.id==='p1')!.currentTeamId).toBe('team1');expect(result.players.find(p=>p.id==='p24')!.currentTeamId).toBe('team0');expect(result.transactions.filter(x=>x.buyoutId===counter.id)).toHaveLength(2);});
it('competing acceptances cannot double spend and failed transaction leaves both sides unchanged',async()=>{const f=await setup();const a=await f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH',cashAmountUnits:150});const b=await f.act('user0',{type:'BUYOUT',targetPlayerId:'p48',offerType:'CASH',cashAmountUnits:150});const results=await Promise.allSettled([f.act('user1',{type:'BUYOUT_RESPONSE',buyoutId:a.buyouts![0]!.id,response:'ACCEPT'}),f.act('user2',{type:'BUYOUT_RESPONSE',buyoutId:b.buyouts!.at(-1)!.id,response:'ACCEPT'})]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const t=(await f.repo.find(f.state.id))!;expect(t.teams[0]!.transferBudgetUnits).toBe(50);expect(t.teams.reduce((n,x)=>n+x.transferBudgetUnits,0)).toBe(1600);expect(t.transactions.filter(x=>x.type==='BUYOUT')).toHaveLength(1);});
it('enforces ownership, permission, window and terms; expires stale offers after a pure trade',async()=>{const f=await setup();await expect(f.act('user0',{type:'BUYOUT',targetPlayerId:'p0',offerType:'CASH',cashAmountUnits:5})).rejects.toThrow();await expect(f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH',cashAmountUnits:0})).rejects.toThrow();await expect(f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH_PLUS_PLAYER',cashAmountUnits:1,includedPlayerId:'p48'})).rejects.toThrow();const offer=(await f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH',cashAmountUnits:5})).buyouts![0]!;expect((await f.service.state(f.state.id,'user2')).buyouts).toHaveLength(0);await expect(f.act('user2',{type:'BUYOUT_RESPONSE',buyoutId:offer.id,response:'ACCEPT'})).rejects.toMatchObject({code:'BUYOUT_PERMISSION'});const trade=await f.act('user1',{type:'TRADE',offeredPlayerId:'p24',requestedPlayerId:'p48'});await f.act('user2',{type:'TRADE_RESPONSE',tradeId:trade.trades[0]!.id,response:'ACCEPT'});expect((await f.service.state(f.state.id,'user0')).buyouts![0]!.status).toBe('EXPIRED');await f.act('user0',{type:'WINDOW',open:false});await expect(f.act('user0',{type:'BUYOUT',targetPlayerId:'p25',offerType:'CASH',cashAmountUnits:5})).rejects.toMatchObject({code:'TRANSFER_WINDOW_CLOSED'});});
it('supports rejection and creator cancellation without changing budgets',async()=>{const f=await setup();let t=await f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH',cashAmountUnits:5});t=await f.act('user1',{type:'BUYOUT_RESPONSE',buyoutId:t.buyouts![0]!.id,response:'REJECT'});expect(t.buyouts![0]!.status).toBe('REJECTED');t=await f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH',cashAmountUnits:5});t=await f.act('user0',{type:'BUYOUT_RESPONSE',buyoutId:t.buyouts!.at(-1)!.id,response:'CANCEL'});expect(t.buyouts!.at(-1)!.status).toBe('CANCELLED');expect(t.teams.every(x=>x.transferBudgetUnits===200)).toBe(true);});
