import {afterEach,describe,it,expect,vi} from 'vitest';
import {GroqNegotiationDialogueProvider,SafeDialogueProvider,TemplateNegotiationDialogueProvider,compactContext,validateDialogue,type DialogueContext} from '../src/modules/manager-mode/negotiation/dialogue.provider.js';
import {describeOffer,type OfferBehavior} from '../src/modules/manager-mode/negotiation/offer-reaction.js';
import type {Tournament} from '../src/modules/manager-mode/manager.types.js';
const context:DialogueContext={player:{name:'Test Player',position:'CM',overall:82},personality:'AMBITIOUS',emotion:'INTERESTED',decision:'COUNTER',offerUnits:32,counterUnits:38,club:{name:'Test Club'},competition:{count:2,higherOffer:true},fallback:'Original template',reaction:{previousOfferUnits:24,offerBehavior:'STRONG_IMPROVEMENT',offerQuality:'BELOW_PREFERRED',lowballCount:1,consecutiveImprovementCount:2,playingTime:'HIGH',clubStrength:'STRONG'}};
const valid={message:'That is a stronger proposal, but I would need ₹19 Cr.',tone:'INTERESTED',decisionAcknowledged:'COUNTER'};
const completion=(value:unknown)=>Response.json({choices:[{message:{content:typeof value==='string'?value:JSON.stringify(value)}}]});
afterEach(()=>{vi.unstubAllGlobals();vi.useRealTimers();});
it('calls Groq with compact context and validates success without mutating the context',async()=>{const original=structuredClone(context);const fetchMock=vi.fn().mockResolvedValue(completion(valid));vi.stubGlobal('fetch',fetchMock);const log=vi.fn();const result=await new SafeDialogueProvider(new GroqNegotiationDialogueProvider('test-key','test-model'),{provider:'groq',model:'test-model',log}).generateResponse(context);expect(result).toMatchObject({...valid,provider:'LLM'});expect(context).toEqual(original);const [url,options]=fetchMock.mock.calls[0]!;expect(url).toBe('https://api.groq.com/openai/v1/chat/completions');expect(options.headers.Authorization).toBe('Bearer test-key');const body=JSON.parse(options.body);expect(body.response_format).toEqual({type:'json_object'});const sent=JSON.parse(body.messages[1].content);expect(sent).toMatchObject({decision:'COUNTER',currentOfferCr:16,previousOfferCr:12,counterOfferCr:19,offerBehavior:'STRONG_IMPROVEMENT'});expect(JSON.stringify(sent)).not.toMatch(/minimumValue|preferredValue|apiKey|test-key/);expect(log).toHaveBeenCalledWith({provider:'groq',model:'test-model',latency:expect.any(Number),fallbackUsed:false});});
describe.each([429,500,503])('Groq HTTP %s',status=>{it('uses behavior-aware fallback',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('',{status})));const log=vi.fn();const result=await new SafeDialogueProvider(new GroqNegotiationDialogueProvider('test-key'),{provider:'groq',model:'test-model',log}).generateResponse(context);expect(result.provider).toBe('TEMPLATE');expect(result.message).toContain('much better proposal');expect(result.message).toContain('₹19 Cr');expect(result.decisionAcknowledged).toBe('COUNTER');expect(log.mock.calls[0]![0].fallbackUsed).toBe(true);expect(JSON.stringify(log.mock.calls)).not.toContain('test-key');});});
it.each(['not JSON',JSON.stringify({...valid,decisionAcknowledged:'ACCEPT'}),JSON.stringify({...valid,tone:'MADE_UP'}),JSON.stringify({...valid,message:' '}),JSON.stringify({...valid,message:'I need ₹99 Cr.'}),JSON.stringify({...valid,message:'I accept this proposal.'}),JSON.stringify({...valid,message:'I would need ₹16 Cr.'}),JSON.stringify({...valid,message:'The signing is complete.'}),JSON.stringify({...valid,message:'I appreciate the offer of ₹19 Cr. I am still aiming higher.'})])('falls back on invalid or contradictory output: %s',async output=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(completion(output)));const result=await new SafeDialogueProvider(new GroqNegotiationDialogueProvider('test-key')).generateResponse(context);expect(result.provider).toBe('TEMPLATE');expect(result.decisionAcknowledged).toBe('COUNTER');});
it('falls back at the deadline even if a provider ignores cancellation',async()=>{vi.useFakeTimers();const promise=new SafeDialogueProvider({generateResponse:()=>new Promise(()=>{})},{timeoutMs:3000}).generateResponse(context);await vi.advanceTimersByTimeAsync(3000);expect((await promise).provider).toBe('TEMPLATE');});
it('keeps PRIVATE competition details out of the outbound request',()=>{const c={...context,competition:{count:2}};expect(compactContext(c)).not.toHaveProperty('higherRivalOfferExists');expect(compactContext(c)).not.toHaveProperty('highestRivalOfferCr');expect(()=>validateDialogue({...valid,message:'Another club has made a higher offer.'},c)).toThrow();});
it('templates reflect repeated low offers, regression and matching a counter',async()=>{const provider=new TemplateNegotiationDialogueProvider();const text=async(behavior:OfferBehavior,decision=context.decision,emotion=context.emotion)=>(await provider.generateResponse({...context,decision,emotion,reaction:{...context.reaction!,offerBehavior:behavior}})).message;expect(await text('REPEATED_LOW_OFFER','REJECT','ANNOYED')).toContain('Repeating offers');expect(await text('WORSE_THAN_PREVIOUS')).toContain('step backwards');expect(await text('MATCHED_COUNTER','ACCEPT','READY_TO_SIGN')).toContain('figure I was looking for');expect(await text('MATCHED_COUNTER','WAIT')).not.toContain('I accept');});
function reaction(amounts:number[],counter:number|null=null){const player={id:'p',position:'CM',overall:82,currentTeamId:null};const t={players:[player],negotiation:{profiles:[{playerId:'p',minimumValueUnits:20,preferredValueUnits:40,idealValueUnits:60}],offers:amounts.map((offerUnits,i)=>({sessionId:'s',offerUnits,counterUnits:i===amounts.length-2?counter:null}))}} as Tournament;const before=structuredClone(t);const result=describeOffer(t,{id:'s',playerId:'p',teamId:'team'} as Parameters<typeof describeOffer>[1]);expect(t).toEqual(before);return result;}
it.each<[number[],number|null,OfferBehavior]>([[[25],null,'FIRST_OFFER'],[[1],null,'VERY_LOW_OFFER'],[[15],null,'LOWBALL'],[[40],null,'FAIR_OFFER'],[[60],null,'STRONG_OFFER'],[[20,30],null,'STRONG_IMPROVEMENT'],[[20,22],null,'SMALL_IMPROVEMENT'],[[10,12],null,'REPEATED_LOW_OFFER'],[[20,38],38,'MATCHED_COUNTER'],[[20,40],38,'EXCEEDED_COUNTER'],[[30,20],null,'WORSE_THAN_PREVIOUS']])('classifies %j read-only as %s', (amounts,counter,expected)=>{expect(reaction(amounts,counter).offerBehavior).toBe(expected);});
