import {it,expect,vi,afterEach} from 'vitest';
import {randomUUID} from 'node:crypto';
import type {Room} from '../src/domain/types.js';
import {settingsSchema} from '../src/schemas/settings.js';
import {ManagerModeService} from '../src/modules/manager-mode/manager.service.js';
import {MemoryManagerRepository} from '../src/modules/manager-mode/manager.repository.js';
import {negotiationAction,ensureNegotiations,publicNegotiations,synchronizeWindow,profileFor} from '../src/modules/manager-mode/negotiation/negotiation.engine.js';
import {SafeDialogueProvider,LLMNegotiationDialogueProvider,type DialogueContext} from '../src/modules/manager-mode/negotiation/dialogue.provider.js';
export function source(): Room { const teams = Array.from({ length: 8 }, (_, i) => ({ id: 'team' + i, userId: 'user' + i, name: 'Team ' + i, startingBudgetUnits: 400, spentUnits: 48, playerIds: Array.from({ length: 24 }, (_, j) => 'p' + (i * 24 + j)) })); return { id: 'auction-id', code: 'ABC234', hostUserId: 'user0', auctionName: 'Acceptance League', status: 'COMPLETED', createdAt: 1, settings: settingsSchema.parse({ numberOfTeams: 8, startingBudgetCr: 200, maxSquadSize: 24 }), teams, players: Array.from({ length: 212 }, (_, i) => ({ id: 'p' + i, name: 'Player ' + i, position: 'MID', subPosition: 'CM', ovr: 80, stats: { passing: 80 }, basePriceUnits: 2, potId: 'gold', status: i < 192 ? 'SOLD' : 'UNSOLD', round: 1 })), purchases: teams.flatMap(t => t.playerIds.map(playerId => ({ id: randomUUID(), playerId, teamId: t.id, priceUnits: 2, bidCount: 1, at: 1, durationMs: 1000 }))), active: null, playerQueue: [], bids: [], sequence: 50, nextPlayerAt: null, receipts: {} }; }
async function setup(){const repo=new MemoryManagerRepository(),room=source(),service=new ManagerModeService(repo,async()=>room);for(const p of room.players.filter(p=>p.status==='UNSOLD'))p.subPosition='CB';const state=await service.create(room.id,'user0',{addUnusedAuctionPurse:false,name:'Negotiation test'});const t=(await repo.find(state.id))!;t.status='ACTIVE';t.transferWindowOpen=true;for(const team of t.teams)team.invitation='JOINED';ensureNegotiations(t);return t;}
function start(t:Awaited<ReturnType<typeof setup>>,user='user0',playerId='p192'){negotiationAction(t,user,{type:'START_NEGOTIATION',playerId},1000);return t.negotiation!.sessions.find(s=>s.managerUserId===user&&s.playerId===playerId)!;}
afterEach(()=>vi.unstubAllGlobals());
it('stable profiles vary by player and keep hard minimum private',async()=>{const t=await setup();const p=t.players.find(p=>p.id==='p192')!;expect(profileFor(t.id,p)).toEqual(profileFor(t.id,p));expect(new Set(t.negotiation!.profiles.map(p=>p.archetype)).size).toBeGreaterThan(1);const s=start(t);negotiationAction(t,'user0',{type:'OFFER_FREE_AGENT',sessionId:s.id,amountUnits:1},5000);expect(s.status).not.toBe('ACCEPTED');expect(s.frustration).toBeGreaterThan(10);expect(JSON.stringify(publicNegotiations(t,'team0'))).not.toMatch(/minimumValueUnits|moneyImportance|patienceRemaining/);});
it('enforces offer spam, budget, membership, ownership and walk-away cooldown',async()=>{const t=await setup(),s=start(t);expect(()=>negotiationAction(t,'user0',{type:'OFFER_FREE_AGENT',sessionId:s.id,amountUnits:201},5000)).toThrow();expect(()=>negotiationAction(t,'user1',{type:'OFFER_FREE_AGENT',sessionId:s.id,amountUnits:10},5000)).toThrow();negotiationAction(t,'user0',{type:'OFFER_FREE_AGENT',sessionId:s.id,amountUnits:1},5000);expect(()=>negotiationAction(t,'user0',{type:'OFFER_FREE_AGENT',sessionId:s.id,amountUnits:2},5001)).toThrow();negotiationAction(t,'user0',{type:'END_NEGOTIATION',sessionId:s.id},6000);expect(()=>start(t)).toThrow();expect(()=>start(t,'user0','p0')).toThrow();});
it('competing offers change decisions without leaking exact rival offers',async()=>{const t=await setup(),a=start(t),b=start(t,'user1');negotiationAction(t,'user1',{type:'OFFER_FREE_AGENT',sessionId:b.id,amountUnits:80},5000);negotiationAction(t,'user0',{type:'OFFER_FREE_AGENT',sessionId:a.id,amountUnits:40},5000);expect(['WAIT','CONSIDER']).toContain(t.negotiation!.offers.at(-1)!.decision);expect(publicNegotiations(t,'team0').sessions[0]!.competition).toEqual({count:1,higherOffer:true});t.negotiation!.rules.visibility='PRIVATE';expect(publicNegotiations(t,'team0').sessions[0]!.competition).toEqual({count:1});t.negotiation!.rules.visibility='TRANSPARENT';expect(publicNegotiations(t,'team0').sessions[0]!.competition.highestOfferUnits).toBe(80);expect(publicNegotiations(t,'team0').sessions).toHaveLength(1);});
it('pauses accepted sessions, restores them and signs exactly once with atomic draft budget',async()=>{const t=await setup(),a=start(t),b=start(t,'user1');for(const s of [a,b])negotiationAction(t,s.managerUserId,{type:'OFFER_FREE_AGENT',sessionId:s.id,amountUnits:80},5000);expect(a.status).toBe('ACCEPTED');t.transferWindowOpen=false;synchronizeWindow(t);expect(a.status).toBe('PAUSED_WINDOW_CLOSED');expect(()=>negotiationAction(t,'user0',{type:'CONFIRM_SIGNING',sessionId:a.id},6000)).toThrow();t.transferWindowOpen=true;synchronizeWindow(t);expect(a.status).toBe('ACCEPTED');negotiationAction(t,'user0',{type:'CONFIRM_SIGNING',sessionId:a.id},7000);expect(t.teams[0]!.transferBudgetUnits).toBe(120);expect(b.status).toBe('CLOSED_LOST_PLAYER');expect(t.transactions.filter(x=>x.type==='FREE_AGENT_SIGNING')).toHaveLength(1);expect(()=>negotiationAction(t,'user1',{type:'CONFIRM_SIGNING',sessionId:b.id},7000)).toThrow();expect(()=>negotiationAction(t,'user0',{type:'CONFIRM_SIGNING',sessionId:a.id},7000)).toThrow();});
it('revalidates remaining budget at confirmation and restricts rule changes to host',async()=>{const t=await setup(),s=start(t);negotiationAction(t,'user0',{type:'OFFER_FREE_AGENT',sessionId:s.id,amountUnits:80},5000);t.teams[0]!.transferBudgetUnits=70;expect(()=>negotiationAction(t,'user0',{type:'CONFIRM_SIGNING',sessionId:s.id})).toThrow();expect(t.players.find(p=>p.id==='p192')!.currentTeamId).toBeNull();expect(()=>negotiationAction(t,'user1',{type:'TRANSFER_RULES',difficulty:'HARD',visibility:'PRIVATE',walkAwayCooldownMs:10000})).toThrow();});
const context:DialogueContext={player:{name:'Player',position:'CM',overall:80},personality:'BALANCED',emotion:'HESITANT',decision:'COUNTER',counterUnits:40,offerUnits:30,club:{name:'Team'},competition:{count:1},fallback:'I need a better proposal.'};
it('provider failures and invalid model decisions fall back without changing mechanics',async()=>{const provider=new SafeDialogueProvider(new LLMNegotiationDialogueProvider('https://dialogue.example','test'));vi.stubGlobal('fetch',vi.fn().mockRejectedValue(Error('timeout')));expect((await provider.generateResponse(context)).message).toBe(context.fallback);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({message:'I accept ₹999 Cr.',tone:'HESITANT',decisionAcknowledged:'COUNTER'})));expect((await provider.generateResponse(context)).message).toBe(context.fallback);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({message:'I would need ₹20 Cr.',tone:'HESITANT',decisionAcknowledged:'COUNTER'})));expect((await provider.generateResponse(context)).message).toBe('I would need ₹20 Cr.');});

it('persists opaque idempotency fingerprints instead of private action JSON',async()=>{const room=source(),repo=new MemoryManagerRepository(),service=new ManagerModeService(repo,async()=>room);const state=await service.create(room.id,'user0',{addUnusedAuctionPurse:false,name:'Receipt test'});await service.mutate(state.id,'user1','receipt-id',{type:'INVITATION',accept:true});const stored=(await repo.find(state.id))!;expect(stored.receipts['user1:receipt-id']!.fingerprint).toMatch(/^[a-f0-9]{64}$/);expect((await service.mutate(state.id,'user1','receipt-id',{type:'INVITATION',accept:true})).sequence).toBe(stored.sequence);});

it('commits and broadcasts the decision before waiting for dialogue',async()=>{
 const room=source();for(const p of room.players.filter(p=>p.status==='UNSOLD'))p.subPosition='CB';
 const repo=new MemoryManagerRepository();let release!:()=>void,entered!:()=>void;
 const gate=new Promise<void>(resolve=>{release=resolve;}),started=new Promise<void>(resolve=>{entered=resolve;});
 const service=new ManagerModeService(repo,async()=>room,undefined,undefined,{async generateResponse(c){entered();await gate;throw Error('Groq unavailable');}});
 const state=await service.create(room.id,'user0',{addUnusedAuctionPurse:false,name:'Commit order'});
 await repo.mutate(state.id,t=>{t.status='ACTIVE';t.transferWindowOpen=true;});
 const opened=await service.mutate(state.id,'user0',randomUUID(),{type:'START_NEGOTIATION',playerId:'p192'}),sessionId=opened.negotiation.sessions[0]!.id;
 const snapshots:string[]=[];service.subscribe(t=>{snapshots.push(t.negotiation!.sessions[0]!.status);});
 const pending=service.mutate(state.id,'user0',randomUUID(),{type:'OFFER_FREE_AGENT',sessionId,amountUnits:80});
 await started;const committed=(await repo.find(state.id))!;expect(committed.negotiation!.offers).toHaveLength(1);expect(snapshots).toHaveLength(1);expect(committed.teams[0]!.transferBudgetUnits).toBe(200);
 // A second repository mutation can complete while the provider is still waiting.
 await repo.mutate(state.id,t=>{t.updatedAt++;});release();const final=await pending;expect(final.negotiation.sessions[0]!.status).toBe(committed.negotiation!.sessions[0]!.status);expect(final.negotiation.sessions[0]!.messages.at(-1)!.provider).toBe('TEMPLATE');
});
