import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {source} from './squad.test.js';
import {MemoryManagerRepository} from '../src/modules/manager-mode/manager.repository.js';
import {ManagerModeService} from '../src/modules/manager-mode/manager.service.js';
import {heroCatalog} from '../src/modules/manager-mode/heroes/hero.catalog.js';
import {ManagerReportService} from '../src/modules/manager-mode/reports/report.service.js';
import {buildApp} from '../src/app.js';
import {StaticTokenAuthService} from '../src/modules/auth-context/auth.service.js';
import type {WebSocket} from 'ws';
import type {TournamentState} from '../src/modules/manager-mode/manager.types.js';
function nextState(socket:WebSocket){return new Promise<TournamentState>((resolve,reject)=>{const timer=setTimeout(()=>{socket.off('message',onMessage);reject(Error('Missing manager state'));},3000);function onMessage(raw:Buffer){const e=JSON.parse(raw.toString());if(e.type==='MANAGER_MODE_STATE'){clearTimeout(timer);socket.off('message',onMessage);resolve(e.payload as TournamentState);}}socket.on('message',onMessage);});}
async function setup(){const repo=new MemoryManagerRepository(),room=source(),service=new ManagerModeService(repo,async()=>room);const created=await service.create(room.id,'user0',{name:'Hero league',addUnusedAuctionPurse:false});const act=(user:string,a:Parameters<typeof service.mutate>[3],id=randomUUID())=>service.mutate(created.id,user,id,a);for(let i=1;i<8;i++)await act('user'+i,{type:'INVITATION',accept:true});await act('user0',{type:'GENERATE_FIXTURES'});const state=await act('user0',{type:'WINDOW',open:true});return {repo,service,act,state,id:state.id};}
it('exposes every opaque slot in stable randomized order without private identity or attributes',async()=>{const f=await setup(),s=f.state.secretPlayers!;expect(s.slots).toHaveLength(54);expect(new Set(s.slots.map(x=>x.secretSlotId)).size).toBe(54);expect(s.slots).toEqual((await f.service.state(f.id,'user1')).secretPlayers!.slots);for(const slot of s.slots)expect(Object.keys(slot).sort()).toEqual(['displayNumber','priceUnits','secretSlotId','status']);const json=JSON.stringify(f.state);for(const hero of heroCatalog)expect(json).not.toContain(hero.name);expect(json).not.toContain('secretHeroes');const saved=await f.repo.find(f.id);expect(saved!.secretHeroes!.map(h=>h.identity.name)).not.toEqual(heroCatalog.map(h=>h.name));});
it('first committed buyer owns the selected slot, with one debit and idempotent retries',async()=>{const f=await setup(),secretSlotId=f.state.secretPlayers!.slots[7]!.secretSlotId,request=randomUUID();const events:string[]=[];f.service.subscribe((_t,event)=>events.push(event));const results=await Promise.allSettled([f.act('user0',{type:'BUY_SECRET_PLAYER',secretSlotId},request),f.act('user1',{type:'BUY_SECRET_PLAYER',secretSlotId})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results[1]).toMatchObject({status:'rejected',reason:{code:'SECRET_PLAYER_ALREADY_CLAIMED'}});const retry=await f.act('user0',{type:'BUY_SECRET_PLAYER',secretSlotId},request);expect(retry.teams.find(t=>t.id==='team0')!.transferBudgetUnits).toBe(110);expect(retry.transactions.filter(t=>t.type==='SECRET_HERO_PURCHASE')).toHaveLength(1);expect(retry.secretPlayers!.availableCount).toBe(53);expect(events).toContain('SECRET_PLAYER_POOL_UPDATED');await expect(f.act('user0',{type:'BUY_SECRET_PLAYER',secretSlotId:retry.secretPlayers!.slots[0]!.secretSlotId})).rejects.toMatchObject({code:'SECRET_PLAYER_ALREADY_USED'});});
it('reveal reads a completed purchase, is owner-only, survives reconnect and cannot charge',async()=>{const f=await setup();const s=await f.act('user0',{type:'BUY_SECRET_PLAYER',secretSlotId:f.state.secretPlayers!.slots[0]!.secretSlotId});const purchase=s.secretPlayers!.purchaseId!;const player=await f.service.reveal(f.id,'user0',purchase);expect(player.overall).toBeNull();expect(player.stats).toEqual({});expect(player.isSellable).toBe(false);expect((await f.service.state(f.id,'user1')).players.some(p=>p.id===player.id)).toBe(false);await expect(f.service.reveal(f.id,'user1',purchase)).rejects.toMatchObject({code:'SECRET_PURCHASE_NOT_FOUND'});const recovered=await new ManagerModeService(f.repo,async()=>source()).state(f.id,'user0');expect(recovered.secretPlayers!.purchaseId).toBe(purchase);expect(await f.service.reveal(f.id,'user0',purchase)).toEqual(player);await f.act('user0',{type:'REVEAL_SECRET_PLAYER'});expect((await f.service.state(f.id,'user1')).players.find(p=>p.id===player.id)?.name).toBe(player.name);expect((await f.service.state(f.id,'user0')).teams[0]!.transferBudgetUnits).toBe(110);});
it('blocks all outgoing Hero transfers, retains season entitlement and reconciles window audit',async()=>{const f=await setup();const s=await f.act('user0',{type:'BUY_SECRET_PLAYER',secretSlotId:f.state.secretPlayers!.slots[0]!.secretSlotId});const player=await f.service.reveal(f.id,'user0',s.secretPlayers!.purchaseId!);for(const action of [{type:'SELL_PLAYER',playerId:player.id,ownershipToken:'initial',expectedSaleUnits:45},{type:'TRADE',offeredPlayerId:player.id,requestedPlayerId:'p24'}] as const)await expect(f.act('user0',action)).rejects.toMatchObject({code:'HERO_UNTRADEABLE'});await expect(f.act('user1',{type:'BUYOUT',targetPlayerId:player.id,offerType:'CASH',cashAmountUnits:100})).rejects.toMatchObject({code:'HERO_UNTRADEABLE'});await expect(f.act('user0',{type:'BUYOUT',targetPlayerId:'p24',offerType:'CASH_PLUS_PLAYER',includedPlayerId:player.id,cashAmountUnits:10})).rejects.toMatchObject({code:'HERO_UNTRADEABLE'});await f.act('user0',{type:'WINDOW',open:false});const report=await new ManagerReportService(f.repo).audit(f.id,'user0',s.transferWindows![0]!.id);expect(report.teams.find(t=>t.teamId==='team0')!.spentUnits).toBe(90);expect(report.teams.find(t=>t.teamId==='team0')!.bought[0]!.type).toBe('Secret Player');expect(JSON.stringify(report)).not.toContain(player.name);await f.act('user0',{type:'END_CURRENT_SEASON',confirmation:'END SEASON'});const next=await f.act('user0',{type:'START_NEXT_SEASON'});expect(next.secretPlayers!.teamEligible).toBe(false);});
it('rejects closed windows, unknown slots, outsiders and insufficient budgets',async()=>{const f=await setup(),secretSlotId=f.state.secretPlayers!.slots[0]!.secretSlotId;await expect(f.act('outsider',{type:'BUY_SECRET_PLAYER',secretSlotId})).rejects.toMatchObject({code:'NOT_TOURNAMENT_MEMBER'});await expect(f.act('user0',{type:'BUY_SECRET_PLAYER',secretSlotId:randomUUID()})).rejects.toMatchObject({code:'SECRET_PLAYER_NOT_FOUND'});await f.repo.mutate(f.id,t=>{t.teams[0]!.transferBudgetUnits=89;});await expect(f.act('user0',{type:'BUY_SECRET_PLAYER',secretSlotId})).rejects.toMatchObject({code:'INSUFFICIENT_BUDGET'});await f.act('user0',{type:'WINDOW',open:false});await expect(f.act('user1',{type:'BUY_SECRET_PLAYER',secretSlotId})).rejects.toMatchObject({code:'TRANSFER_WINDOW_CLOSED'});});
it('connects authenticated REST purchases to realtime pool removal and independent reveal reads',async()=>{
 const f=await setup();const {app}=await buildApp({managerRepository:f.repo,logger:false,timersEnabled:false,authService:new StaticTokenAuthService(new Map(['user0','user1'].map(userId=>[userId,{userId}])))});let socket:WebSocket|undefined;
 try{await app.ready();socket=await app.injectWS('/ws?token=user1',{headers:{origin:'http://localhost:3000'}});const initial=nextState(socket);socket.send(JSON.stringify({type:'SUBSCRIBE_MANAGER_MODE',payload:{tournamentId:f.id}}));expect((await initial).secretPlayers!.availableCount).toBe(54);
 const updated=nextState(socket),secretSlotId=f.state.secretPlayers!.slots[0]!.secretSlotId;const requestId=randomUUID();const response=await app.inject({method:'POST',url:'/api/manager-mode/'+f.id+'/actions',headers:{authorization:'Bearer user0'},payload:{requestId,action:{type:'BUY_SECRET_PLAYER',secretSlotId}}});expect(response.statusCode).toBe(200);const purchased=response.json() as TournamentState;const peer=await updated;expect(peer.secretPlayers!.availableCount).toBe(53);expect(peer.secretPlayers!.slots.some(s=>s.secretSlotId===secretSlotId)).toBe(false);expect(peer.players.some(p=>p.source==='SECRET_HERO')).toBe(false);
 const path='/api/manager-mode/'+f.id+'/secret-player-purchases/'+purchased.secretPlayers!.purchaseId+'/reveal';expect((await app.inject({url:path})).statusCode).toBe(401);expect((await app.inject({url:path,headers:{authorization:'Bearer user1'}})).statusCode).toBe(404);const reveal=await app.inject({url:path,headers:{authorization:'Bearer user0'}});expect(reveal.statusCode).toBe(200);expect(reveal.headers['cache-control']).toBe('private, no-store');expect(reveal.json().source).toBe('SECRET_HERO');
 }finally{socket?.terminate();await app.close();}
});
