import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import type {Room} from '../src/domain/types.js';
import {settingsSchema} from '../src/schemas/settings.js';
import {MemoryManagerRepository} from '../src/modules/manager-mode/manager.repository.js';
import {ManagerModeService} from '../src/modules/manager-mode/manager.service.js';
export function source(): Room { const teams = Array.from({ length: 8 }, (_, i) => ({ id: 'team' + i, userId: 'user' + i, name: 'Team ' + i, startingBudgetUnits: 400, spentUnits: 48, playerIds: Array.from({ length: 24 }, (_, j) => 'p' + (i * 24 + j)) })); return { id: 'auction-id', code: 'ABC234', hostUserId: 'user0', auctionName: 'Acceptance League', status: 'COMPLETED', createdAt: 1, settings: settingsSchema.parse({ numberOfTeams: 8, startingBudgetCr: 200, maxSquadSize: 24 }), teams, players: Array.from({ length: 212 }, (_, i) => ({ id: 'p' + i, name: 'Player ' + i, position: 'MID', subPosition: ['GK','LW','ST','RW','CM','CDM','CM','LB','CB','CB','RB','CM','LW'][i%24]??'CM', ovr: 80, stats: { passing: 80 }, basePriceUnits: 2, potId: 'gold', status: i < 192 ? 'SOLD' : 'UNSOLD', round: 1 })), purchases: teams.flatMap(t => t.playerIds.map(playerId => ({ id: randomUUID(), playerId, teamId: t.id, priceUnits: 2, bidCount: 1, at: 1, durationMs: 1000 }))), active: null, playerQueue: [], bids: [], sequence: 50, nextPlayerAt: null, receipts: {} }; }


async function setup(){const repo=new MemoryManagerRepository(),room=source(),service=new ManagerModeService(repo,async()=>room);const initial=await service.create(room.id,'user0',{name:'Squad test',addUnusedAuctionPurse:false});const act=(user:string,a:Parameters<typeof service.mutate>[3],id=randomUUID())=>service.mutate(initial.id,user,id,a);for(let i=1;i<8;i++)await act('user'+i,{type:'INVITATION',accept:true});const state=await act('user0',{type:'GENERATE_FIXTURES'});return {repo,service,state,act};}
const sheet=(start=0)=>({type:'SAVE_TEAM_SHEET',formation:'4-3-3',slots:[...Array.from({length:10},(_,i)=>'p'+(start+i+1)),'p'+start],bench:['p'+(start+11)],captainId:'p'+(start+1)} as const);
it('saves own sheet and rejects foreign, duplicate, invalid goalkeeper or captain assignments',async()=>{const f=await setup();const s=await f.act('user0',{...sheet(),slots:[...sheet().slots],bench:[...sheet().bench]});expect(s.squadData!.sheets[0]!.slots).toHaveLength(11);for(const bad of [{...sheet(),slots:['p24',...sheet().slots.slice(1)]},{...sheet(),slots:['p2',...sheet().slots.slice(1)]},{...sheet(),slots:['p0',...sheet().slots.slice(1,10),'p1']},{...sheet(),captainId:'p12'}])await expect(f.act('user0',{...bad,slots:[...bad.slots],bench:[...bad.bench]})).rejects.toThrow();await expect(f.act('user1',{...sheet(),slots:[...sheet().slots],bench:[...sheet().bench]})).rejects.toMatchObject({code:'INVALID_OWNERSHIP'});});
it('captures starters, supports braces, keeps snapshots on corrections and resets stats with reset result',async()=>{const f=await setup();await f.act('user0',{...sheet(),slots:[...sheet().slots],bench:[...sheet().bench]});const match=f.state.fixtures.find(x=>x.homeTeamId==='team0'||x.awayTeamId==='team0')!;const home=match.homeTeamId==='team0';let s=await f.act('user0',{type:'SCORE',fixtureId:match.id,homeScore:home?3:0,awayScore:home?0:3,scorers:{team0:[{playerId:'p1',goals:2},{playerId:'p1',goals:1}]}});expect(s.playerStats!.p1).toEqual({matchesPlayed:1,goals:3});expect(s.playerStats!.p11).toBeUndefined();const snapshot=s.squadData!.lineups.find(x=>x.teamId==='team0')!;await f.act('user0',{...sheet(),slots:['p12',...sheet().slots.slice(1)],bench:[...sheet().bench],captainId:null});s=await f.act('user0',{type:'SCORE',fixtureId:match.id,homeScore:home?2:0,awayScore:home?0:2,scorers:{team0:[{playerId:'p1',goals:2}]}});expect(s.playerStats!.p1).toEqual({matchesPlayed:1,goals:2});expect(s.squadData!.lineups.find(x=>x.teamId==='team0')!.starters).toEqual(snapshot.starters);await expect(f.act('user0',{type:'SCORE',fixtureId:match.id,homeScore:0,awayScore:0})).rejects.toMatchObject({code:'SCORER_TOTAL_EXCEEDS_SCORE'});s=await f.act('user0',{type:'RESET_SCORE',fixtureId:match.id});expect(s.playerStats!.p1).toBeUndefined();expect(s.squadData!.lineups).toHaveLength(0);});
it('rejects rival scorers, records no fictional appearances without sheet, scopes stats to seasons',async()=>{const f=await setup();const match=f.state.fixtures[0]!;await expect(f.act('user1',{type:'SCORE',fixtureId:match.id,homeScore:1,awayScore:0})).rejects.toMatchObject({code:'HOST_ONLY'});const foreign=f.state.players.find(p=>p.currentTeamId!==match.homeTeamId&&p.currentTeamId!==null)!;await expect(f.act('user0',{type:'SCORE',fixtureId:match.id,homeScore:1,awayScore:0,scorers:{[match.homeTeamId]:[{playerId:foreign.id,goals:1}]}})).rejects.toMatchObject({code:'INVALID_SCORER'});let s=await f.act('user0',{type:'SCORE',fixtureId:match.id,homeScore:1,awayScore:0});expect(s.playerStats).toEqual({});expect(s.squadData!.lineups.every(l=>!l.lineupAvailable)).toBe(true);await f.act('user0',{type:'END_CURRENT_SEASON',confirmation:'END SEASON'});s=await f.act('user0',{type:'START_NEXT_SEASON'});expect(s.playerStats).toEqual({});expect(s.squadData!.lineups).toHaveLength(2);});
it('renews once per request without charging budget; sales prune the sheet and old contract',async()=>{const f=await setup();await f.act('user0',{...sheet(),slots:[...sheet().slots],bench:[...sheet().bench]});const id=randomUUID();let s=await f.act('user0',{type:'RENEW_CONTRACT',playerId:'p1'},id);const contract=s.squadData!.contracts[0]!;expect(contract.renewalCount).toBe(1);expect(contract.contractEnd).toBeGreaterThan(contract.contractStart);s=await f.act('user0',{type:'RENEW_CONTRACT',playerId:'p1'},id);expect(s.squadData!.contracts[0]!.renewalCount).toBe(1);expect(s.teams[0]!.transferBudgetUnits).toBe(200);await expect(f.act('user1',{type:'RENEW_CONTRACT',playerId:'p1'})).rejects.toMatchObject({code:'INVALID_OWNERSHIP'});await f.act('user0',{type:'WINDOW',open:true});const q=s.saleQuotes!.p1!;s=await f.act('user0',{type:'SELL_PLAYER',playerId:'p1',ownershipToken:q.ownershipToken,expectedSaleUnits:q.saleValueUnits});expect(s.squadData!.sheets[0]!.slots).not.toContain('p1');expect(s.squadData!.contracts).toHaveLength(0);await f.act('user0',{type:'END_MANAGER_MODE',confirmation:'END MANAGER MODE'});await expect(f.act('user0',{type:'RENEW_CONTRACT',playerId:'p2'})).rejects.toMatchObject({code:'MANAGER_MODE_ENDED'});});

