import {build} from '../../backend/node_modules/esbuild/lib/main.js';
import {chromium,expect} from '@playwright/test';
import {fileURLToPath} from 'node:url';
import {mkdirSync,readFileSync,readdirSync} from 'node:fs';

const root=fileURLToPath(new URL('../',import.meta.url));
const bundle=await build({stdin:{contents:`
import React from 'react'; import {createRoot} from 'react-dom/client'; import {ManagerCommandCenter} from './src/components/manager-mode/ManagerCommandCenter';
const teams=[['a','Alpha FC','Host'],['b','Beta FC','Manager B'],['c','City FC','Manager C'],['d','Delta FC','Manager D']].map(([id,name,managerUsername])=>({id,name,managerUsername,logoUrl:'',logoEmoji:'⚽',transferBudgetUnits:85,invitation:'JOINED'}));
const player=(id,name,team,position)=>({id,name,currentTeamId:team,position,overall:82,category:'MID',secondaryPositions:'',club:'Test',nationality:'Test',imageUrl:'',stats:{},tier:'',source:'AUCTION_SQUAD',ownershipStatus:'OWNED',availability:'SIGNED',auctionPurchasePriceUnits:null,acquisitionType:'AUCTION_PURCHASE',acquisitionPriceUnits:20,metadata:{}});
const state={id:'t1',myTeamId:'a',teams,players:[player('p1','Alpha Striker','a','ST'),player('p2','Beta Star','b','ST'),player('p3','City Forward','c','ST')],standings:[{teamId:'a',position:1,played:4,won:3,drawn:1,lost:0,gf:10,ga:3,gd:7,points:10},{teamId:'b',position:2,played:4,won:3,drawn:0,lost:1,gf:8,ga:4,gd:4,points:9},{teamId:'c',position:3,played:4,won:2,drawn:1,lost:1,gf:6,ga:4,gd:2,points:7},{teamId:'d',position:4,played:4,won:0,drawn:0,lost:4,gf:2,ga:15,gd:-13,points:0}],fixtures:[{id:'old',matchday:4,homeTeamId:'a',awayTeamId:'b',homeScore:2,awayScore:1,status:'COMPLETED',scheduledAt:null,completedAt:10},{id:'next',matchday:5,homeTeamId:'c',awayTeamId:'a',homeScore:null,awayScore:null,status:'SCHEDULED',scheduledAt:null,completedAt:null}],seasonData:{currentSeasonId:'s1',seasons:[{id:'s1',number:2,status:'ACTIVE',championTeamId:null,startedAt:1,completedAt:null,endedEarly:false,bonusesAwardedAt:null,finalStandings:[]}]},cupData:{competitions:[{id:'cup',seasonId:'s1',settings:{enabled:true,name:'Supa Del Copa',qualifiedTeams:4,groupStage:true,groupMeetings:1,semiFinalLegs:1,finalLegs:1,thirdPlace:false},status:'WAITING_FOR_LEAGUE',qualified:[],groups:[],fixtures:[],ties:[],lineups:[],drawnAt:null,completedAt:null,championTeamId:null,finishes:{}}],trophies:[]},squadData:{sheets:[{teamId:'a',formation:'4-3-3',slots:['p1',null,null,null,null,null,null,null,null,null,null],bench:[],captainId:'p1',updatedAt:1}],lineups:[],contracts:[]},playerStats:{p1:{goals:5,matchesPlayed:4},p2:{goals:4,matchesPlayed:4},p3:{goals:3,matchesPlayed:4}},transactions:[],transferWindowOpen:true,notifications:[{id:'n1',title:'Fixture completed',message:'Alpha FC beat Beta FC 2–1.',read:false}],status:'ACTIVE',modeStatus:'ACTIVE'};
createRoot(document.getElementById('root')).render(<main className="mx-auto max-w-7xl p-4"><ManagerCommandCenter state={state}/></main>);
`,resolveDir:root,loader:'tsx'},bundle:true,write:false,outfile:'overview.js',platform:'browser',jsx:'automatic',alias:{'@':root+'src'},define:{'process.env.NODE_ENV':'"test"'},plugins:[{name:'platform',setup(b){b.onResolve({filter:/^next\/dynamic$/},()=>({path:'dynamic',namespace:'dynamic'}));b.onLoad({filter:/.*/,namespace:'dynamic'},()=>({resolveDir:root,contents:'import React from "react";export default loader=>React.lazy(loader);',loader:'js'}));b.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'link'}));b.onLoad({filter:/.*/,namespace:'link'},()=>({contents:'import React from "react";export default ({href,children,...props})=>React.createElement("a",{href,...props},children);',loader:'js'}));}}]});
const css=(bundle.outputFiles.find(f=>f.path.endsWith('.css'))?.text??'')+readdirSync(root+'.next/static/css').filter(f=>f.endsWith('.css')).map(f=>readFileSync(root+'.next/static/css/'+f,'utf8')).join('\n');
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.route('https://overview.test/',route=>route.fulfill({contentType:'text/html',body:`<meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><body style="background:#060e1a;color:white"><div id="root"></div><script src="/overview.js"></script></body>`}));
 await page.route('https://overview.test/overview.js',route=>route.fulfill({contentType:'application/javascript',body:bundle.outputFiles.find(f=>f.path.endsWith('.js')).text}));
 await page.route('https://overview.test/models/trophies/league-shield.glb',route=>route.fulfill({contentType:'model/gltf-binary',body:readFileSync(root+'public/models/trophies/league-shield.glb')}));
 await page.goto('https://overview.test/');
 await expect(page.getByRole('heading',{name:'Alpha FC'})).toBeVisible();await expect(page.getByText('The race for the shield',{exact:true})).toBeVisible();await expect(page.locator('canvas')).toHaveCount(1);await expect(page.getByText('Top scorers',{exact:true})).toBeVisible();await expect(page.getByText('Supa Del Copa',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:/View full standings/})).toHaveAttribute('href','/manager-mode/t1/standings');
 mkdirSync(root+'test-results',{recursive:true});await page.screenshot({path:root+'test-results/overview-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:root+'test-results/overview-mobile.png',fullPage:true});expect(errors).toEqual([]);
 console.log('PASS: command-center desktop/mobile hierarchy, authoritative overview data, links, Cup status, and League Shield viewer.');
} finally { await browser.close(); }
