import type {Db} from '../auction-snapshot.repository.js';
import type {Tournament} from '../manager.types.js';
import type {SquadData,Formation} from './squad.types.js';
import type {Json} from '../../../types/database.generated.js';
import {ensureSquad} from './squad.engine.js';
const json=(db:Db,value:unknown)=>db.json(JSON.parse(JSON.stringify(value)) as Json);
export async function loadSquad(db:Db,id:string):Promise<SquadData>{const [sheets,lineups,contracts]=await Promise.all([db`select * from public.manager_team_sheets where tournament_id=${id} order by team_id`,db`select * from public.manager_match_lineups where tournament_id=${id} order by fixture_id,team_id`,db`select * from public.manager_player_contracts where tournament_id=${id} order by player_id`]);return {sheets:sheets.map(s=>({teamId:s.team_id,formation:s.formation as Formation,slots:s.slots,bench:s.bench,captainId:s.captain_id,updatedAt:new Date(s.updated_at).getTime()})),lineups:lineups.map(s=>({fixtureId:s.fixture_id,teamId:s.team_id,starters:s.starters,bench:s.bench,eligiblePlayerIds:s.eligible_player_ids,scorers:s.scorers,capturedAt:new Date(s.captured_at).getTime(),lineupAvailable:s.lineup_available})),contracts:contracts.map(c=>({playerId:c.player_id,teamId:c.team_id,ownershipToken:c.ownership_token,contractStart:new Date(c.contract_start).getTime(),contractEnd:new Date(c.contract_end).getTime(),renewalCount:c.renewal_count}))};}
export async function persistSquad(db:Db,t:Tournament,before:Tournament){const data=ensureSquad(t),old=ensureSquad(before);
 for(const s of data.sheets){if(JSON.stringify(s)===JSON.stringify(old.sheets.find(x=>x.teamId===s.teamId)))continue;await db`insert into public.manager_team_sheets(tournament_id,team_id,formation,slots,bench,captain_id,updated_at) values(${t.id},${s.teamId},${s.formation},${json(db,s.slots)},${json(db,s.bench)},${s.captainId},${new Date(s.updatedAt)}) on conflict(team_id) do update set formation=excluded.formation,slots=excluded.slots,bench=excluded.bench,captain_id=excluded.captain_id,updated_at=excluded.updated_at`;}
 for(const l of old.lineups)if(!data.lineups.some(x=>x.fixtureId===l.fixtureId&&x.teamId===l.teamId))await db`delete from public.manager_match_lineups where tournament_id=${t.id} and fixture_id=${l.fixtureId} and team_id=${l.teamId}`;
 for(const l of data.lineups){if(JSON.stringify(l)===JSON.stringify(old.lineups.find(x=>x.fixtureId===l.fixtureId&&x.teamId===l.teamId)))continue;await db`insert into public.manager_match_lineups(tournament_id,fixture_id,team_id,starters,bench,eligible_player_ids,scorers,captured_at,lineup_available) values(${t.id},${l.fixtureId},${l.teamId},${json(db,l.starters)},${json(db,l.bench)},${json(db,l.eligiblePlayerIds)},${json(db,l.scorers)},${new Date(l.capturedAt)},${l.lineupAvailable}) on conflict(fixture_id,team_id) do update set scorers=excluded.scorers`;}
 for(const c of old.contracts)if(!data.contracts.some(x=>x.playerId===c.playerId))await db`delete from public.manager_player_contracts where tournament_id=${t.id} and player_id=${c.playerId}`;
 for(const c of data.contracts){if(JSON.stringify(c)===JSON.stringify(old.contracts.find(x=>x.playerId===c.playerId)))continue;await db`insert into public.manager_player_contracts(tournament_id,player_id,team_id,ownership_token,contract_start,contract_end,renewal_count) values(${t.id},${c.playerId},${c.teamId},${c.ownershipToken},${new Date(c.contractStart)},${new Date(c.contractEnd)},${c.renewalCount}) on conflict(player_id) do update set team_id=excluded.team_id,ownership_token=excluded.ownership_token,contract_start=excluded.contract_start,contract_end=excluded.contract_end,renewal_count=excluded.renewal_count`;}
}
