'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Trophy} from 'lucide-react';
import {api} from '@/services/api';
import {webSocketService} from '@/services/websocket.service';
import {useConnectionStore} from '@/stores/connection.store';
import {PlayerImage} from '@/components/shared/PlayerImage';
import {FixtureMatchCard} from './FixtureMatchCard';
import type {TournamentState,Fixture} from '@/types/manager-mode';
import type {ManagerAction} from '@/services/manager-mode.service';
import type {GoldenBootState} from '@/types/manager-golden-boot';

const button='rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:border-amber-500/50 focus-visible:outline-2 focus-visible:outline-amber-400 disabled:opacity-40';
export function StandingsWithGoldenBoot({state,leagueTable,action,busy}:{state:TournamentState;leagueTable:ReactNode;action:(a:ManagerAction)=>Promise<void>;busy:boolean}){
 const [tab,setTab]=useState<'table'|'boot'>('table');
 return <div className="space-y-6"><div className="flex gap-2" aria-label="Standings sections">{(['table','boot'] as const).map(t=><button key={t} aria-pressed={tab===t} className={button+(tab===t?' border-amber-500/60 bg-amber-500/10 text-amber-200':'')} onClick={()=>setTab(t)}>{t==='table'?'Standings':'Golden Boot'}</button>)}</div>{tab==='table'?leagueTable:<GoldenBoot state={state} action={action} busy={busy}/>}</div>;
}
export function GoldenBoot({state,action,busy}:{state:TournamentState;action:(a:ManagerAction)=>Promise<void>;busy:boolean}){
 const [selected,setSelected]=useState(''),[data,setData]=useState<GoldenBootState|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true);
 const connection=useConnectionStore(s=>s.status),seasonId=selected||state.seasonData?.currentSeasonId;
 useEffect(()=>webSocketService.subscribe(e=>{if(e.type==='PLAYER_STATS_UPDATED'&&e.payload.tournamentId===state.id)setRevision(n=>n+1);}),[state.id]);
 useEffect(()=>{if(!seasonId)return;const abort=new AbortController();let live=true;setLoading(true);setError('');const timer=setTimeout(()=>{
  void api.get<GoldenBootState>(`/manager-mode/${state.id}/seasons/${seasonId}/stats/golden-boot`,{signal:AbortSignal.any([abort.signal,AbortSignal.timeout(20000)])}).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(e instanceof Error?e.message:'Unable to load Golden Boot.');}).finally(()=>{if(live)setLoading(false);});
 },150);return()=>{live=false;clearTimeout(timer);abort.abort();};},[state.id,seasonId,revision,connection]);
 const season=state.seasonData?.seasons.find(s=>s.id===seasonId);
 return <section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="flex items-center gap-3 text-2xl font-bold text-white"><Trophy className="text-amber-300" size={26}/>Golden Boot</h2><p className="mt-2 text-sm text-slate-400">Every recorded goal. Season {season?.number??''}.</p></div><label className="text-xs text-slate-400">Season<select className="mt-1 block rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm text-white" value={seasonId} onChange={e=>setSelected(e.target.value)}>{state.seasonData?.seasons.map(s=><option key={s.id} value={s.id}>Season {s.number} · {s.status}</option>)}</select></label></div>
 {error?<div role="alert" className="text-red-300">{error} <button className={button} onClick={()=>setRevision(n=>n+1)}>Retry</button></div>:loading?<p role="status" className="py-12 text-slate-400">Loading recorded goals…</p>:data&&<>
 {data.missingScorerFixtures>0&&<div className="rounded-xl border border-amber-800/50 bg-amber-950/15 p-4 text-sm text-amber-200"><strong>Goalscorer data incomplete</strong><p className="mt-1">{data.missingScorerFixtures} completed fixtures do not yet have all goalscorers recorded. Totals include recorded goals only.</p></div>}
 {!data.rows.length?<div className="border-y border-slate-800 py-14 text-center"><h3 className="text-lg text-white">No goals recorded yet.</h3><p className="mt-2 text-sm text-slate-400">Complete fixtures and assign goalscorers to start the leaderboard.</p></div>:<>
 <div className="grid gap-3 sm:grid-cols-3">{data.rows.slice(0,3).map((row,i)=><article key={row.playerId} className={'relative overflow-hidden rounded-2xl border p-5 '+(i===0?'border-amber-500/50 bg-amber-950/20':'border-slate-700 bg-[#0a1628]')}><div className="flex items-center justify-between"><span className={i===0?'text-lg font-bold text-amber-300':'text-lg font-bold text-slate-400'}>#{row.rank}</span><span className="rounded border border-white/10 px-2 py-1 text-xs text-slate-400">{row.position}</span></div><PlayerImage player={state.players.find(p=>p.id===row.playerId)??{id:row.playerId,imageUrl:row.imageUrl}} className="mx-auto h-32 w-32 rounded-xl"/><h3 className="mt-2 truncate text-lg font-bold text-white">{row.name}</h3><p className="truncate text-sm text-slate-400">{row.teamName}</p><div className="mt-5 flex items-baseline justify-between border-t border-white/10 pt-4"><span className={'text-4xl font-bold tabular-nums '+(i===0?'text-amber-200':'text-white')}>{row.goals} <span className="text-xs font-normal text-slate-400">goals</span></span><span className="text-xs text-slate-400">{row.matchesPlayed} MP · {row.goalsPerMatch.toFixed(2)} G/M</span></div></article>)}</div>
 <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left text-sm"><caption className="sr-only">Season {season?.number} Golden Boot leaderboard</caption><thead className="bg-slate-900 text-xs text-slate-400"><tr>{['Rank','Player','Team','MP','Goals','G/M'].map(h=><th key={h} scope="col" className="whitespace-nowrap px-4 py-3">{h}</th>)}</tr></thead><tbody>{data.rows.map(row=><tr key={row.playerId} className="border-t border-slate-800/70"><td className="px-4 py-3 text-amber-200">{row.rank}</td><td className="px-4 py-3"><div className="flex min-w-40 items-center gap-3"><PlayerImage player={state.players.find(p=>p.id===row.playerId)??{id:row.playerId,imageUrl:row.imageUrl}} className="h-10 w-10 rounded-full"/><div className="text-white">{row.name}<p className="text-xs text-slate-500">{row.position}</p></div></div></td><td className="min-w-36 px-4 py-3 text-slate-300">{row.teamName}<p className="mt-1 text-xs text-slate-500">Scored for {row.scoringTeams.map(t=>`${t.teamName} (${t.goals})`).join(', ')}</p></td><td className="px-4 py-3 tabular-nums text-slate-300">{row.matchesPlayed}</td><td className="px-4 py-3 font-bold tabular-nums text-white">{row.goals}</td><td className="px-4 py-3 tabular-nums text-slate-400">{row.goalsPerMatch.toFixed(2)}</td></tr>)}</tbody></table></div></>}
 {data.missingLineupFixtures>0&&<p className="text-xs text-slate-400">MP counts known saved starting-XI appearances only. {data.missingLineupFixtures} completed fixtures have incomplete historical lineup data; no appearances are estimated.</p>}
 </>}
 {state.isHost&&seasonId&&<HistoricalScorers state={state} seasonId={seasonId} action={action} busy={busy} revision={revision}/>}
 </section>;
}
function HistoricalScorers({state,seasonId,action,busy,revision}:{state:TournamentState;seasonId:string;action:(a:ManagerAction)=>Promise<void>;busy:boolean;revision:number}){
 const [open,setOpen]=useState(false),[offset,setOffset]=useState(0),[error,setError]=useState(''),[page,setPage]=useState<{items:Fixture[];lineups:NonNullable<TournamentState['squadData']>['lineups'];nextOffset:number|null}|null>(null);
 useEffect(()=>{setOffset(0);setPage(null);},[seasonId]);
 useEffect(()=>{if(!open)return;let live=true;setPage(null);setError('');void api.get<NonNullable<typeof page>>(`/manager-mode/${state.id}/seasons/${seasonId}/fixtures?offset=${offset}`).then(p=>{if(live)setPage(p);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[state.id,seasonId,open,offset,revision]);
 return <div className="border-t border-slate-800 pt-5"><button className={button} aria-expanded={open} onClick={()=>setOpen(x=>!x)}>{open?'Hide':'Manage'} recorded goals</button>{open&&<div className="mt-4 space-y-4"><p className="text-sm text-slate-400">Add or correct scorers for this season. Scorer-only edits preserve the result and standings.</p>{error&&<p role="alert">{error}</p>}{!page&&!error&&<p role="status">Loading fixtures…</p>}<div className="grid gap-3 lg:grid-cols-2">{page?.items.filter(f=>f.status==='COMPLETED').map(f=><FixtureMatchCard key={f.id} fixture={f} state={{...state,squadData:{sheets:state.squadData?.sheets??[],contracts:state.squadData?.contracts??[],lineups:page.lineups}}} onAction={action} busy={busy}/>)}</div>{page&&!page.items.some(f=>f.status==='COMPLETED')&&<p className="text-sm text-slate-400">No completed fixtures on this page.</p>}<div className="flex gap-2">{offset>0&&<button className={button} onClick={()=>setOffset(n=>Math.max(0,n-50))}>Previous fixtures</button>}{page?.nextOffset!==null&&page?.nextOffset!==undefined&&<button className={button} onClick={()=>setOffset(page.nextOffset!)}>More fixtures</button>}</div></div>}</div>;
}
