'use client';
import {useState} from 'react';
import {Download} from 'lucide-react';
import type {TournamentState} from '@/types/manager-mode';
import {api,normalizeError} from '@/services/api';
const button='inline-flex min-h-10 items-center gap-2 rounded-xl border border-emerald-800 bg-emerald-950 px-3 py-2 text-sm text-emerald-100 disabled:opacity-40';
export function HostReports({state}:{state:TournamentState}){
 const [pending,setPending]=useState<string|null>(null),[error,setError]=useState('');
 if(!state.isHost)return null;
 async function download(path:string,name:string){if(pending)return;setPending(path);setError('');try{const blob=await api.pdf(`/manager-mode/${encodeURIComponent(state.id)}/${path}`),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(normalizeError(e).message);}finally{setPending(null);}}
 return <section className="space-y-5 rounded-2xl border border-slate-700 bg-slate-950/60 p-5"><h3 className="text-lg font-bold text-white">Host PDF reports</h3>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}<div><h4 className="mb-2 font-semibold text-slate-200">Team Sheets</h4><p className="mb-3 text-sm text-slate-400">Download the latest saved lineup for every team. Teams that have not saved a lineup are marked in the report.</p><button className={button} disabled={pending!==null} onClick={()=>void download('team-sheets/report.pdf','All-Teams-Lineups.pdf')}><Download size={16}/>{pending==='team-sheets/report.pdf'?'Preparing PDF…':'Download All Teams Lineups PDF'}</button></div><div><h4 className="mb-3 font-semibold text-slate-200">Transfer Window History</h4>{!state.transferWindows?.length&&<p className="text-sm text-slate-400">No transfer windows have opened yet.</p>}<div className="space-y-3">{state.transferWindows?.slice().reverse().map(window=><article key={window.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 p-3"><div><p className="text-sm font-semibold text-white">Transfer Window {window.number} · {window.status}</p><p className="text-xs text-slate-400">{window.seasonNumber?'Season '+window.seasonNumber+' · ':''}{new Date(window.openedAt).toLocaleString()}</p>{!window.auditAvailable&&<p className="mt-1 text-xs text-amber-300">Predates budget snapshots; a verified audit is unavailable.</p>}</div>{window.status==='CLOSED'?<button className={button} disabled={pending!==null||!window.auditAvailable} onClick={()=>void download(`transfer-windows/${window.id}/report.pdf`,`Transfer-Window-${window.number}-Audit.pdf`)}><Download size={16}/>{pending?.includes(window.id)?'Preparing PDF…':'Download Transfer Audit PDF'}</button>:<p className="text-xs text-emerald-300">Close this window to enable its audit.</p>}</article>)}</div></div></section>;
}
