'use client';
import Link from 'next/link';
import {ArrowRight,CalendarDays,Medal,ShieldCheck,Trophy,UsersRound} from 'lucide-react';
import type {TournamentState,Fixture,Standing} from '@/types/manager-mode';
import {formatCrore} from '@/lib/money';
import {getFormation} from '@/lib/formations';
import {CupTrophy3D} from './trophies/CupTrophy3D';
import styles from './ManagerCommandCenter.module.css';

const surface='rounded-2xl border border-white/10 bg-[#0a1628]/80 p-5';
const link='inline-flex items-center gap-1 text-sm font-semibold text-emerald-300 hover:text-emerald-200 focus-visible:outline-2 focus-visible:outline-emerald-300';
const outcome=(fixture:Fixture,teamId:string)=>{const mine=fixture.homeTeamId===teamId?fixture.homeScore:fixture.awayScore,other=fixture.homeTeamId===teamId?fixture.awayScore:fixture.homeScore;if(mine===null||other===null)return null;return mine===other?'D':mine>other?'W':'L';};
const outcomeClass=(value:string)=>value==='W'?'bg-emerald-400/15 text-emerald-200':value==='D'?'bg-amber-300/15 text-amber-100':'bg-red-400/15 text-red-200';

export function ManagerCommandCenter({state}:{state:TournamentState}){
 const mine=state.teams.find(t=>t.id===state.myTeamId)!;
 const standing=state.standings.find(s=>s.teamId===mine.id);
 const season=state.seasonData?.seasons.find(s=>s.id===state.seasonData?.currentSeasonId);
 const fixtures=[...state.fixtures], completed=fixtures.filter(f=>f.status==='COMPLETED'), mineFixtures=fixtures.filter(f=>f.homeTeamId===mine.id||f.awayTeamId===mine.id);
 const next=fixtures.filter(f=>f.status==='SCHEDULED').filter(f=>f.homeTeamId===mine.id||f.awayTeamId===mine.id).sort((a,b)=>(a.scheduledAt??Infinity)-(b.scheduledAt??Infinity)||a.matchday-b.matchday)[0];
 const form:('W'|'D'|'L')[]=mineFixtures.filter(f=>f.status==='COMPLETED').sort((a,b)=>(b.completedAt??0)-(a.completedAt??0)).slice(0,5).reverse().map(f=>outcome(f,mine.id)).filter((x):x is 'W'|'D'|'L'=>x!==null);
 const opponent=next&&state.teams.find(t=>t.id===(next.homeTeamId===mine.id?next.awayTeamId:next.homeTeamId));
 const totalMatchdays=Math.max(0,...fixtures.map(f=>f.matchday));
 const cup=state.cupData?.competitions.find(c=>c.seasonId===state.seasonData?.currentSeasonId&&c.settings.enabled);
 const trophies=[...(state.cupData?.trophies??[])];
 for(const s of state.seasonData?.seasons??[])if(s.championTeamId&&!trophies.some(t=>t.seasonId===s.id&&t.type==='LEAGUE_SHIELD'))trophies.push({id:`league-${s.id}`,seasonId:s.id,teamId:s.championTeamId,type:'LEAGUE_SHIELD',competitionId:null,name:'League Shield',wonAt:s.completedAt});
 const mineTrophies=trophies.filter(t=>t.teamId===mine.id),shields=mineTrophies.filter(t=>t.type==='LEAGUE_SHIELD').length,cups=mineTrophies.filter(t=>t.type==='CUP').length;
 const owned=state.players.filter(p=>p.currentTeamId===mine.id),sheet=state.squadData?.sheets.find(s=>s.teamId===mine.id),formation=sheet?getFormation(sheet.formation):null;
 const leaders=Object.entries(state.playerStats??{}).map(([id,stat])=>({player:state.players.find(p=>p.id===id),goals:stat.goals})).filter((x):x is {player:NonNullable<typeof x.player>;goals:number}=>!!x.player&&x.goals>0).sort((a,b)=>b.goals-a.goals||a.player.name.localeCompare(b.player.name)).slice(0,3);
 const transferDeals=state.transactions.filter(t=>t.toTeamId===mine.id&&t.type!=='AUCTION_PURCHASE'),sales=state.transactions.filter(t=>t.fromTeamId===mine.id&&['RELEASE','BUYOUT'].includes(t.type));
 const champion=season?.championTeamId===mine.id;
 return <main className="space-y-6">
  <section className={styles.hero}>
   <div className="grid lg:grid-cols-[minmax(0,1fr)_minmax(310px,35%)]">
    <div className={styles.heroCopy}><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Manager Mode · Season {season?.number??1}</p><div className="mt-5 flex min-w-0 items-center gap-4">{mine.logoUrl?<img src={mine.logoUrl} alt="" className="h-16 w-16 rounded-xl object-contain"/>:<span className="grid h-16 w-16 place-items-center rounded-xl bg-white/5 text-4xl">{mine.logoEmoji}</span>}<div className="min-w-0"><h2 className="truncate text-3xl font-extrabold tracking-[-.03em] text-white">{mine.name}</h2><p className="mt-1 text-sm text-slate-300">Managed by {mine.managerUsername??'your manager'}</p></div></div>
     <div className="mt-8 flex flex-wrap gap-x-8 gap-y-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Current position</p><p className="mt-1 text-4xl font-extrabold tabular-nums text-amber-200">{standing?`${standing.position}${standing.position===1?'st':standing.position===2?'nd':standing.position===3?'rd':'th'}`:'—'}</p></div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">League points</p><p className="mt-1 text-4xl font-extrabold tabular-nums text-white">{standing?.points??0}</p></div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Goal difference</p><p className="mt-1 text-4xl font-extrabold tabular-nums text-emerald-300">{standing?`${standing.gd>=0?'+':''}${standing.gd}`:'—'}</p></div></div>
     <p className="mt-7 text-sm text-slate-300">{season?.status==='COMPLETED'?'Season complete':`League matchday ${next?.matchday??Math.min(totalMatchdays,(standing?.played??0)+1)} / ${totalMatchdays||'—'}`}</p>
    </div>
    <div className={styles.showcase}><CupTrophy3D variant="LEAGUE_SHIELD" size="compact"/><div className={styles.showcaseMeta}><strong className="block text-amber-200">{champion?'League champions':'The race for the shield'}</strong><span>{champion?mine.name:`Position ${standing?.position??'—'} · ${standing?.points??0} points`}</span></div></div>
   </div>
  </section>
  <section className="grid grid-cols-2 divide-x divide-y divide-white/8 overflow-hidden rounded-2xl border border-white/10 bg-[#091523] sm:grid-cols-4 lg:grid-cols-8">{[['Matches',standing?.played??0],['Wins',standing?.won??0],['Draws',standing?.drawn??0],['Losses',standing?.lost??0],['Goals',standing?.gf??0],['GA',standing?.ga??0],['GD',standing?`${standing.gd>=0?'+':''}${standing.gd}`:'—'],['Points',standing?.points??0]].map(([label,value])=><div key={String(label)} className="px-4 py-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-xl font-bold tabular-nums text-white">{value}</p></div>)}</section>
  <section className="grid gap-6 lg:grid-cols-2"><article className={surface}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Next fixture</p><h3 className="mt-2 text-lg font-bold text-white">{next?`Matchday ${next.matchday}`:season?.status==='COMPLETED'?'Season complete':'No upcoming fixture'}</h3></div><CalendarDays className="text-emerald-300" size={22}/></div>{next?<><div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><Club teamId={next.homeTeamId} state={state}/><strong className="text-xs tracking-widest text-slate-500">VS</strong><Club teamId={next.awayTeamId} state={state}/></div><p className="mt-5 text-center text-sm text-slate-400">{next.homeTeamId===mine.id?'Home':'Away'}{next.scheduledAt?` · ${new Date(next.scheduledAt).toLocaleDateString()}`:''}</p></>:<p className="mt-7 text-sm leading-6 text-slate-400">{season?.status==='COMPLETED'?'The league schedule is complete.':'Fixtures will appear here when the host creates the league schedule.'}</p>}<Link href={`/manager-mode/${state.id}/fixtures`} className={link+' mt-6'}>View fixtures <ArrowRight size={15}/></Link></article>
   <article className={surface}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Recent form</p><h3 className="mt-2 text-lg font-bold text-white">Last five league matches</h3></div><Medal className="text-amber-200" size={22}/></div><div className="mt-8">{form.length?<div className={styles.form}>{form.map((result,index)=><span key={`${result}-${index}`} className={outcomeClass(result)}>{result}</span>)}</div>:<p className="text-sm text-slate-400">No completed league matches yet.</p>}</div><p className="mt-6 text-sm text-slate-400">{standing?`W ${standing.won} · D ${standing.drawn} · L ${standing.lost}`:'League table pending'}</p><Link href={`/manager-mode/${state.id}/fixtures`} className={link+' mt-6'}>Review form <ArrowRight size={15}/></Link></article></section>
  <section className="grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,1fr)]"><article className={surface}><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">The league race</p><h3 className="mt-2 text-xl font-bold text-white">Table leaders</h3></div><ShieldCheck className="text-amber-200" size={24}/></div><div className="mt-5">{state.standings.slice(0,5).map(row=><RaceRow key={row.teamId} row={row} state={state}/>)}</div><Link href={`/manager-mode/${state.id}/standings`} className={link+' mt-5'}>View full standings <ArrowRight size={15}/></Link></article>
   <article className={surface}><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Golden Boot race</p><h3 className="mt-2 text-xl font-bold text-white">Top scorers</h3></div><Trophy className="text-amber-200" size={24}/></div><div className="mt-5 space-y-3">{leaders.length?leaders.map((entry,index)=><div key={entry.player.id} className="flex items-center gap-3 border-t border-white/5 pt-3 first:border-t-0 first:pt-0"><span className="w-5 text-sm font-bold text-amber-200">{index+1}</span><span className="min-w-0 flex-1 truncate text-sm font-semibold text-white">{entry.player.name}</span><span className="text-sm font-bold tabular-nums text-emerald-300">{entry.goals}</span></div>):<p className="text-sm text-slate-400">No recorded goals yet.</p>}</div><Link href={`/manager-mode/${state.id}/standings`} className={link+' mt-5'}>View Golden Boot <ArrowRight size={15}/></Link></article></section>
  <section className="grid gap-6 xl:grid-cols-3"><article className={surface}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Squad</p><h3 className="mt-2 text-xl font-bold text-white">{owned.length} players</h3></div><UsersRound className="text-emerald-300" size={23}/></div>{formation&&sheet?<div className={styles.formation+' mt-5'} aria-label={`${sheet.formation} formation`}>{formation.slots.map((slot,index)=><span key={`${slot.role}-${index}`} className={styles.spot} style={{left:`${slot.x}%`,top:`${slot.y}%`}}>{slot.role}</span>)}</div>:<p className="mt-6 text-sm leading-6 text-slate-400">Team sheet not set. Set a formation to see your match structure here.</p>}<Link href={`/manager-mode/${state.id}/squad`} className={link+' mt-5'}>{formation?'Open squad':'Set team sheet'} <ArrowRight size={15}/></Link></article>
   <article className={surface}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Transfer window</p><h3 className={`mt-2 text-xl font-bold ${state.transferWindowOpen?'text-emerald-300':'text-slate-300'}`}>{state.transferWindowOpen?'Open':'Closed'}</h3><dl className="mt-6 space-y-3 text-sm"><Data label="Transfer budget" value={formatCrore(mine.transferBudgetUnits)}/><Data label="Players bought" value={String(transferDeals.length)}/><Data label="Players sold" value={String(sales.length)}/></dl><Link href={`/manager-mode/${state.id}/transfers`} className={link+' mt-5'}>Open transfers <ArrowRight size={15}/></Link></article>
   <article className={surface}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{cup?.settings.name??'Cup'}</p><h3 className={`mt-2 text-xl font-bold ${cup?'text-amber-200':'text-slate-300'}`}>{cup?cup.status.replaceAll('_',' '):'Not enabled'}</h3><p className="mt-5 text-sm leading-6 text-slate-400">{cup?cup.fixtures.find(f=>f.status==='SCHEDULED')?`${teamName(cup.fixtures.find(f=>f.status==='SCHEDULED')!.homeTeamId,state)} vs ${teamName(cup.fixtures.find(f=>f.status==='SCHEDULED')!.awayTeamId,state)}`:'Qualification and results stay synchronized with the competition.':'The host has not enabled a Cup for this season.'}</p>{cup&&<Link href={`/manager-mode/${state.id}/cup`} className={link+' mt-5'}>Open Cup <ArrowRight size={15}/></Link>}</article></section>
  <section className="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(0,1fr)]"><article className={surface}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Club honours</p><h3 className="mt-2 text-xl font-bold text-white">A record that lasts</h3><div className="mt-5 space-y-3"><Data label="League Shields" value={`×${shields}`}/><Data label="Cup trophies" value={`×${cups}`}/></div><Link href={`/manager-mode/${state.id}/trophies`} className={link+' mt-5'}>View trophy gallery <ArrowRight size={15}/></Link></article><article className={surface}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Recent club activity</p><h3 className="mt-2 text-xl font-bold text-white">Latest updates</h3><div className="mt-5 space-y-3">{state.notifications.slice(0,4).map(n=><div key={n.id} className="border-t border-white/5 pt-3 first:border-t-0 first:pt-0"><p className="text-sm font-semibold text-slate-200">{n.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-400">{n.message}</p></div>)}{!state.notifications.length&&<p className="text-sm text-slate-400">No club activity has been recorded yet.</p>}</div><Link href={`/manager-mode/${state.id}/notifications`} className={link+' mt-5'}>View activity <ArrowRight size={15}/></Link></article></section>
  <nav className="flex flex-wrap gap-2" aria-label="Manager Mode quick actions">{[['Squad','squad'],['Fixtures','fixtures'],['Transfers','transfers'],['Standings','standings'],...(cup?[['Cup','cup']]:[])].map(([label,path])=><Link key={path} href={`/manager-mode/${state.id}/${path}`} className="rounded-lg border border-white/15 px-4 py-2 text-sm font-semibold text-slate-200 hover:border-emerald-300/60 hover:text-emerald-200 focus-visible:outline-2 focus-visible:outline-emerald-300">{label}</Link>)}</nav>
 </main>;
}
function Club({teamId,state}:{teamId:string;state:TournamentState}){const team=state.teams.find(t=>t.id===teamId);return <div className="min-w-0"><p className="truncate text-base font-bold text-white">{team?.name??'Club'}</p><p className="mt-1 text-xs text-slate-500">{teamId===state.myTeamId?'Your club':'Opponent'}</p></div>;}
function RaceRow({row,state}:{row:Standing;state:TournamentState}){const team=state.teams.find(t=>t.id===row.teamId),mine=row.teamId===state.myTeamId;return <div className={`${styles.raceRow} ${mine?'text-emerald-200':''}`}><span className="font-bold tabular-nums text-slate-400">{row.position}</span><span className="truncate text-sm font-semibold">{team?.name??row.teamId}{mine&&<span className="ml-2 text-[10px] uppercase tracking-wider text-emerald-300">You</span>}</span><span className="font-bold tabular-nums text-white">{row.points}</span></div>;}
function Data({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-4 border-t border-white/5 pt-3 first:border-t-0 first:pt-0"><dt className="text-sm text-slate-400">{label}</dt><dd className="text-sm font-bold tabular-nums text-white">{value}</dd></div>;}
function teamName(teamId:string,state:TournamentState){return state.teams.find(t=>t.id===teamId)?.name??'Club';}
