'use client';
import {memo} from 'react';
import {useEffect,useState} from 'react';
import {ArrowDownToLine,Save,Shirt,Users,Wallet,ChevronDown} from 'lucide-react';
import type {TournamentState,ManagerPlayer} from '@/types/manager-mode';
import type {ManagerAction} from '@/services/manager-mode.service';
import {TeamSheetEditor} from './TeamSheetEditor';
import {PlayerImage} from '@/components/shared/PlayerImage';
import {formatCrore} from '@/lib/money';
import {downloadTeamSheetPdf} from '@/lib/pdf/managerTeamSheetPdf';
const button='inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-emerald-800 bg-emerald-950/70 px-4 py-2 text-sm font-semibold text-emerald-200 hover:bg-emerald-900 disabled:opacity-40 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-emerald-300';
const field='min-h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100 focus-visible:outline-2 focus-visible:outline-emerald-300';
const surface='rounded-2xl border border-slate-800 bg-[#0a1628]';
type Props={state:TournamentState;action:(a:ManagerAction)=>Promise<void>;busy:boolean};
function ManagerSquadView({state,action,busy}:Props){
 const [tab,setTab]=useState<'sheet'|'view'|'actions'>('view'),[group,setGroup]=useState(''),[role,setRole]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('overall');
 const [selected,setSelected]=useState<{id:string;action:'details'|'sell'|'renew'}|null>(null);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement|null;const trap=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);return;}if(e.key!=='Tab')return;const nodes=Array.from(document.querySelectorAll<HTMLElement>('[role="dialog"] button:not([disabled]),[role="dialog"] input:not([disabled]),[role="dialog"] select:not([disabled])'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus();};},[selected]);
 const mine=state.teams.find(t=>t.id===state.myTeamId)!;const owned=state.players.filter(p=>p.currentTeamId===mine.id);const saved=state.squadData?.sheets.find(s=>s.teamId===mine.id);
 const locked=busy||state.modeStatus==='ENDED';const roleOf=(id:string)=>saved?.slots.includes(id)?'Starting XI':saved?.bench.includes(id)?'Bench':'Reserve';
 const player=owned.find(p=>p.id===selected?.id),quote=player?state.saleQuotes?.[player.id]:undefined;
 const contract=player?state.squadData?.contracts.find(c=>c.playerId===player.id&&c.teamId===mine.id):undefined;
 const filtered=owned.filter(p=>(!group||p.category===group||group==='ATT'&&p.category==='FWD')&&(!role||roleOf(p.id)===role)&&p.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='goals'?(state.playerStats?.[b.id]?.goals??0)-(state.playerStats?.[a.id]?.goals??0):sort==='matches'?(state.playerStats?.[b.id]?.matchesPlayed??0)-(state.playerStats?.[a.id]?.matchesPlayed??0):sort==='price'?(b.acquisitionPriceUnits??0)-(a.acquisitionPriceUnits??0):b.overall-a.overall);
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold text-white">{mine.name} squad</h2><p className="mt-1 text-sm text-slate-300">{owned.length} players · {mine.managerUsername??'Your club'} · {formatCrore(mine.transferBudgetUnits)} available</p></div><p className="text-sm text-slate-400">Season {state.seasonData?.seasons.find(s=>s.id===state.seasonData?.currentSeasonId)?.number??1} player statistics</p></div>
 <div role="tablist" aria-label="Squad sections" className="flex gap-2 overflow-x-auto border-b border-slate-800 pb-3">{([['sheet','Team Sheet',Shirt],['view','Squad View',Users],['actions','Squad Actions',Wallet]] as const).map(([id,label,Icon])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)} className={button+(tab===id?' !bg-emerald-400 !text-slate-950 !border-emerald-400':'')}><Icon size={16}/>{label}</button>)}</div>
 {tab==='sheet'?<TeamSheetEditor key={mine.id} state={state} action={action} busy={locked}/>:<>
 {tab==='actions'&&<Finance state={state} owned={owned}/>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="text-sm text-slate-300">Search players<input className={field} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Player name"/></label><label className="text-sm text-slate-300">Position group<select className={field} value={group} onChange={e=>setGroup(e.target.value)}><option value="">All positions</option>{['GK','DEF','MID','ATT'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-slate-300">Squad role<select className={field} value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option>{['Starting XI','Bench','Reserve'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-slate-300">Sort by<select className={field} value={sort} onChange={e=>setSort(e.target.value)}>{[['overall','Overall'],['name','Name'],['goals','Goals'],['matches','Matches Played'],['price','Acquisition Price']].map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label></div>
 {tab==='actions'&&<p className="text-sm text-slate-300">Renew contracts or sell players from their individual cards. Sales require an open transfer window.</p>}
 {!filtered.length&&<p className={surface+' p-8 text-slate-300'}>No players match these filters.</p>}
 <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{filtered.map(p=>{const stats=state.playerStats?.[p.id];const c=state.squadData?.contracts.find(c=>c.playerId===p.id&&c.teamId===mine.id);return <article key={p.id} className={surface+' overflow-hidden'}><div className="flex items-center gap-4 p-5"><PlayerImage player={p} className="h-24 w-20 shrink-0 object-contain"/><div className="min-w-0 flex-1"><p className="text-sm text-emerald-300">{p.position} · {roleOf(p.id)}</p><h3 className="text-lg font-bold text-white">{p.name}</h3><p className="text-xs text-slate-300">{[p.club,p.nationality].filter(Boolean).join(' · ')}</p></div><strong className="text-3xl tabular-nums text-emerald-300" aria-label={'Overall '+p.overall}>{p.overall}</strong></div><div className="grid grid-cols-6 gap-1 border-y border-slate-800 px-4 py-3">{[['PAC','pace'],['SHO','shooting'],['PAS','passing'],['DRI','dribbling'],['DEF','defending'],['PHY','physical']].map(([label,key])=><div className="text-center" key={key}><p className="text-xs text-slate-400">{label}</p><p className="font-semibold tabular-nums text-white">{p.stats[key!]??'—'}</p></div>)}</div><div className="space-y-3 p-4"><dl className="grid grid-cols-2 gap-2 text-sm"><div><dt className="text-slate-400">Matches played</dt><dd className="text-white tabular-nums">{stats?.matchesPlayed??0}</dd></div><div><dt className="text-slate-400">Goals</dt><dd className="text-white tabular-nums">{stats?.goals??0}</dd></div><div><dt className="text-slate-400">Acquired via</dt><dd className="text-slate-200">{p.acquisitionType?.replaceAll('_',' ')??'Unrecorded'}</dd></div><div><dt className="text-slate-400">Acquisition value</dt><dd className="text-slate-200">{p.acquisitionPriceUnits===null?'No cash fee':formatCrore(p.acquisitionPriceUnits)}</dd></div></dl><p className="text-xs text-slate-300">Contract: {c?(c.contractEnd>Date.now()?'Active until ':'Expired ')+new Date(c.contractEnd).toLocaleDateString():'Not set'}{c?' · '+c.renewalCount+' renewals':''}</p><details><summary className={button+' cursor-pointer'}>Actions for {p.name}<ChevronDown size={14}/></summary><div className="mt-3 flex flex-wrap gap-2"><button className={button} onClick={()=>setSelected({id:p.id,action:'details'})}>View details</button><button className={button} disabled={locked} onClick={()=>setSelected({id:p.id,action:'renew'})}>Renew contract</button><button className={button} disabled={locked||!state.transferWindowOpen} onClick={()=>setSelected({id:p.id,action:'sell'})}>Sell player</button></div></details></div></article>;})}</div><p className="text-xs text-slate-400">Appearances count saved starters when a result is first recorded. Older matches without a lineup snapshot do not invent appearances. Goals reflect recorded scorers.</p></>}
 {player&&selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-label={selected.action==='sell'?'Sell Player':selected.action==='renew'?'Renew Contract':'Player details'} className={surface+' max-h-[85vh] w-full max-w-lg overflow-auto p-6 space-y-4'} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}}><div className="flex items-center gap-4"><PlayerImage player={player} className="h-20 w-20 object-contain"/><div><h3 className="text-xl font-bold text-white">{player.name}</h3><p className="text-slate-300">{player.position} · {player.overall} OVR</p></div></div>{selected.action==='sell'?<><p className="text-slate-300">Acquisition / resale basis: {quote?formatCrore(quote.basisUnits):'Unavailable'}</p><p className="text-emerald-300 text-lg">You will receive {quote?formatCrore(quote.saleValueUnits):'Unavailable'}</p><p className="text-sm text-slate-300">After selling, this player will be released into the Manager Mode Free Agent pool and may be signed by another team. Your club must wait before re-signing them.</p><button className={button} disabled={locked||!state.transferWindowOpen||!quote} onClick={()=>{if(quote)void action({type:'SELL_PLAYER',playerId:player.id,ownershipToken:quote.ownershipToken,expectedSaleUnits:quote.saleValueUnits});setSelected(null);}}>Confirm Sale</button></>:selected.action==='renew'?<><p className="text-slate-300">Current contract: {contract?new Date(contract.contractEnd).toLocaleDateString():'Not set'}. Add one year from the later of today or the current end date.</p><p className="text-sm text-slate-300">No fee is charged. Contract expiry is informational and does not transfer ownership.</p><button className={button} disabled={locked} onClick={()=>{void action({type:'RENEW_CONTRACT',playerId:player.id});setSelected(null);}}>Confirm renewal</button></>:<><p className="text-slate-300">{player.club} · {player.nationality}</p><p className="text-slate-300">Secondary positions: {player.secondaryPositions||'None listed'}</p><p className="text-slate-300">Current resale basis: {quote?formatCrore(quote.basisUnits):'Unavailable'}</p></>}<button autoFocus className={button+' ml-2'} onClick={()=>setSelected(null)}>Cancel</button></section></div>}
 </div>;
}
function Finance({state,owned}:{state:TournamentState;owned:ManagerPlayer[]}){
 const groups=['GK','DEF','MID','ATT'],colors=['#34d399','#38bdf8','#a78bfa','#fbbf24'];const amounts=groups.map(g=>owned.filter(p=>p.category===g||g==='ATT'&&p.category==='FWD').reduce((n,p)=>n+(p.acquisitionPriceUnits??0),0)),total=amounts.reduce((a,b)=>a+b,0);let consumed=0;
 const value=owned.reduce((n,p)=>n+(state.saleQuotes?.[p.id]?.basisUnits??p.acquisitionPriceUnits??0),0);const recovered=state.teamSaleReturns?.[state.myTeamId]??state.transactions.filter(t=>t.fromTeamId===state.myTeamId&&['RELEASE','BUYOUT'].includes(t.type)).reduce((n,t)=>n+t.amountUnits,0);const mine=state.teams.find(t=>t.id===state.myTeamId)!;
 return <section className={surface+' p-5'}><h3 className="text-xl font-bold text-white">Finance tracker</h3><p className="mt-1 text-sm text-slate-300">Cash invested in the current squad, grouped by position.</p><div className="mt-5 grid items-center gap-6 md:grid-cols-[180px_1fr]"><svg viewBox="0 0 120 120" role="img" aria-label={total?'Squad acquisition spending by position':'No cash acquisition spending recorded'} className="mx-auto w-44 -rotate-90"><circle cx="60" cy="60" r="42" fill="none" stroke="#1e293b" strokeWidth="22"/>{amounts.map((n,i)=>{const share=total?n/total*263.894:0;const offset=consumed;consumed+=share;return <circle key={groups[i]} cx="60" cy="60" r="42" fill="none" stroke={colors[i]} strokeWidth="22" strokeDasharray={`${share} ${263.894-share}`} strokeDashoffset={-offset}/>;})}</svg><div className="grid gap-3 sm:grid-cols-2">{groups.map((g,i)=><p className="flex items-center gap-2 text-sm text-slate-200" key={g}><span className="h-3 w-3 rounded-sm" style={{background:colors[i]}}/>{g} · {owned.filter(p=>p.category===g||g==='ATT'&&p.category==='FWD').length} players · {formatCrore(amounts[i]!)}</p>)}</div></div><dl className="mt-6 grid grid-cols-2 gap-5 border-t border-slate-800 pt-5 lg:grid-cols-5">{[['Squad value basis',formatCrore(value)],['Current squad spend',formatCrore(total)],['Recovered from sales',formatCrore(recovered)],['Transfer budget',formatCrore(mine.transferBudgetUnits)],['Average OVR',owned.length?(owned.reduce((n,p)=>n+p.overall,0)/owned.length).toFixed(1):'—']].map(([label,v])=><div key={label}><dt className="text-xs text-slate-300">{label}</dt><dd className="mt-1 text-lg font-semibold tabular-nums text-white">{v}</dd></div>)}</dl><p className="mt-3 text-xs text-slate-400">Value basis uses the server’s resale basis. Zero-cash trades do not inflate cash spending. Recovered sales include releases and cash received from buyouts.</p></section>;
}

export const ManagerSquad=memo(ManagerSquadView,(a,b)=>a.action===b.action&&a.busy===b.busy&&(["id","name","myTeamId","players","teams","squadData","playerStats","saleQuotes","teamSaleReturns","transactions","seasonData","status","modeStatus","transferWindowOpen"] as const).every(key=>a.state[key]===b.state[key]));

