'use client';
import {useManagerHistory} from '@/hooks/useManagerHistory';
import {HistoryMore} from './HistoryMore';
import {OfferReview} from './OfferReview';
import {useState} from 'react';
import type {TournamentState} from '@/types/manager-mode';
import type {BuyoutOffer} from '@/types/manager-buyout';
import type {ManagerAction} from '@/services/manager-mode.service';
import {formatCrore,croreToUnits} from '@/lib/money';
import {button,field,panel} from './ManagerSetup';
type Props={state:TournamentState;action:(a:ManagerAction)=>Promise<void>;busy:boolean};
export function BuyoutForm({state,action,busy,counter,onClose}:Props&{counter?:BuyoutOffer;onClose?:()=>void}){
 const [targetTeam,setTargetTeam]=useState(counter?.toTeamId??''),[target,setTarget]=useState(counter?.targetPlayerId??'');
 const [kind,setKind]=useState<'CASH'|'CASH_PLUS_PLAYER'>(counter?.offerType??'CASH'),[cash,setCash]=useState(counter?String(counter.cashAmountUnits/2):''),[included,setIncluded]=useState(counter?.includedPlayerId??''),[error,setError]=useState('');
 const buyer=state.teams.find(t=>t.id===(counter?.fromTeamId??state.myTeamId))!;
 const player=state.players.find(p=>p.id===target);const enabled=state.status==='ACTIVE'&&state.transferWindowOpen;
 async function submit(){setError('');try{if(!cash.trim())throw Error('Enter a cash amount.');const units=croreToUnits(Number(cash));if(units<0||kind==='CASH'&&units===0)throw Error('Cash-only offers require a positive amount.');if(units>buyer.transferBudgetUnits)throw Error('The buying team cannot afford this offer.');if(!target||kind==='CASH_PLUS_PLAYER'&&!included)throw Error('Select the target and included player.');const terms={offerType:kind,cashAmountUnits:units,includedPlayerId:kind==='CASH_PLUS_PLAYER'?included:null};await action(counter?{type:'BUYOUT_COUNTER',buyoutId:counter.id,...terms}:{type:'BUYOUT',targetPlayerId:target,...terms});}catch(e){setError(e instanceof Error?e.message:'Invalid offer.');}}
 return <form className={panel+' space-y-4'} onSubmit={e=>{e.preventDefault();void submit();}}><h2 className="text-xl">{counter?'Counter buyout offer':'Buyout offer'}</h2><p className="text-sm text-slate-400">Manager-to-manager offers. Cash is paid to the selling club only after acceptance.</p>{error&&<p role="alert" className="text-red-300">{error}</p>}<div className="grid sm:grid-cols-2 gap-4"><label>Target team<select className={field} required disabled={Boolean(counter)||busy} value={targetTeam} onChange={e=>{setTargetTeam(e.target.value);setTarget('');}}><option value="">Choose team</option>{state.teams.filter(t=>t.id!==buyer.id&&t.invitation==='JOINED').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Target player<select className={field} required disabled={Boolean(counter)||busy} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose player</option>{state.players.filter(p=>p.currentTeamId===targetTeam).map(p=><option key={p.id} value={p.id}>{p.name} · {p.position} · {p.overall} OVR</option>)}</select></label><label>Offer type<select className={field} value={kind} disabled={busy} onChange={e=>setKind(e.target.value as typeof kind)}><option value="CASH">Cash</option><option value="CASH_PLUS_PLAYER">Cash + Player</option></select></label><label>Cash offer (Cr)<input className={field} type="number" step="0.5" min={kind==='CASH'?'.5':'0'} required value={cash} onChange={e=>setCash(e.target.value)}/></label>{kind==='CASH_PLUS_PLAYER'&&<label>Include player<select className={field} required value={included} onChange={e=>setIncluded(e.target.value)}><option value="">Choose player from {buyer.name}</option>{state.players.filter(p=>p.currentTeamId===buyer.id).map(p=><option key={p.id} value={p.id}>{p.name} · {p.position} · {p.overall} OVR</option>)}</select></label>}</div>{player&&<p>{player.name} · {player.position} · {player.overall} OVR</p>}<p>{buyer.name} budget: {formatCrore(buyer.transferBudgetUnits)}</p><button className={button} disabled={busy||!enabled}>{counter?'Send counter offer':'Send buyout offer'}</button>{onClose&&<button type="button" className={button+' ml-2'} onClick={onClose}>Close counter</button>}{!enabled&&<p>Transfer window closed. New offers and acceptance are unavailable.</p>}</form>;
}
export function BuyoutCards({state,action,busy,filter}:Props&{filter:'incoming'|'outgoing'|'completed'|'closed'}){
 const [counterId,setCounterId]=useState<string|null>(null),myTeam=state.teams.find(t=>t.id===state.myTeamId)!;
 const history=useManagerHistory<BuyoutOffer>(state.id,'buyouts',state.historyCursors?.buyouts);const rows=[...new Map([...history.rows,...(state.buyouts??[])].map(o=>[o.id,o])).values()].filter(o=>(o.fromTeamId===myTeam.id||o.toTeamId===myTeam.id)&&(filter==='incoming'?o.respondingTeamId===myTeam.id&&o.status==='PENDING':filter==='outgoing'?o.createdBy===myTeam.managerUserId&&o.status==='PENDING':filter==='completed'?o.status==='ACCEPTED':['REJECTED','COUNTERED','CANCELLED','EXPIRED'].includes(o.status)));
 return <div className="space-y-4">{!rows.length&&<p className="text-sm text-slate-400">No {filter} buyouts.</p>}{rows.map(o=><article key={o.id} className={panel+' space-y-3'}><OfferReview state={state} kind="buyout" id={o.id} action={action}/><p className="font-semibold">{state.teams.find(t=>t.id===o.fromTeamId)?.name} wants {state.players.find(p=>p.id===o.targetPlayerId)?.name} from {state.teams.find(t=>t.id===o.toTeamId)?.name}</p><p>Offer: {formatCrore(o.cashAmountUnits)}{o.includedPlayerId&&' + '+state.players.find(p=>p.id===o.includedPlayerId)?.name}</p><p>{o.status}{o.parentBuyoutId?' · Linked counter offer':''}</p>{o.status==='PENDING'&&<div className="flex flex-wrap gap-2">{o.respondingTeamId===myTeam.id?<><button className={button} disabled={busy||!state.transferWindowOpen} onClick={()=>void action({type:'BUYOUT_RESPONSE',buyoutId:o.id,response:'ACCEPT'})}>Accept buyout</button><button className={button} disabled={busy||!state.transferWindowOpen} onClick={()=>setCounterId(o.id)}>Counter buyout</button><button className={button} disabled={busy} onClick={()=>void action({type:'BUYOUT_RESPONSE',buyoutId:o.id,response:'REJECT'})}>Reject buyout</button></>:o.createdBy===myTeam.managerUserId&&<button className={button} disabled={busy} onClick={()=>void action({type:'BUYOUT_RESPONSE',buyoutId:o.id,response:'CANCEL'})}>Cancel buyout</button>}</div>}{counterId===o.id&&o.status==='PENDING'&&<BuyoutForm key={o.id} state={state} action={action} busy={busy} counter={o} onClose={()=>setCounterId(null)}/>}</article>)}<HistoryMore history={history}/></div>;
}
