'use client';
import {useEffect,useRef,useState} from 'react';
import type {TournamentState,Standing} from '@/types/manager-mode';
import type {ManagerAction} from '@/services/manager-mode.service';
import type {CupCompetition,CupSettings,Trophy} from '@/types/manager-cup';
import type {ClubHistory} from '@/types/manager-club-history';
import {api} from '@/services/api';
import {formatCrore} from '@/lib/money';
import {CupHero,CupProgress} from './cups/CupHero';
import {CupBracket} from './cups/CupBracket';
import {TrophyDetail} from './trophies/TrophyDetail';
import styles from './cups/CupHub.module.css';
import {FixtureMatchCard} from './FixtureMatchCard';

type Props={state:TournamentState;action:(a:ManagerAction)=>Promise<void>;busy:boolean};
const panel='rounded-2xl border border-white/10 bg-[#0a1628] p-5 sm:p-6';
const input='mt-2 w-full rounded-lg border border-slate-600 bg-slate-950 p-2.5 text-white';
const button='rounded-lg border border-emerald-500/40 bg-emerald-500/10 px-4 py-2.5 text-sm font-semibold text-emerald-300 hover:bg-emerald-500/20 disabled:opacity-40';
const defaults:CupSettings={enabled:false,name:'Manager Mode Cup',qualifiedTeams:6,groupStage:true,groupMeetings:1,semiFinalLegs:2,finalLegs:1,thirdPlace:false};
function CupIcon(){return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="h-9 w-9"><path d="M7 3h10v6a5 5 0 0 1-10 0V3ZM7 5H3v3a4 4 0 0 0 4 4m10-7h4v3a4 4 0 0 1-4 4M12 14v6m-5 1h10" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
function useResource<T>(path:string,sequence:number){
 const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setError('');void api.get<T>(path,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to load data.');});},150);return()=>{clearTimeout(timer);controller.abort();};},[path,sequence,retry]);
 return {data,error,retry:()=>setRetry(n=>n+1)};
}
export function CupSettingsPanel({state,action,busy}:Props){
 const cup=state.cupData?.competitions.find(c=>c.seasonId===state.seasonData?.currentSeasonId);
 const [settings,setSettings]=useState<CupSettings>(cup?.settings??{...defaults,qualifiedTeams:Math.max(4,Math.min(6,state.teams.length-state.teams.length%2))}),[error,setError]=useState('');
 useEffect(()=>{setSettings(cup?.settings??{...defaults,qualifiedTeams:Math.max(4,Math.min(6,state.teams.length-state.teams.length%2))});},[cup?.settings,state.seasonData?.currentSeasonId,state.teams.length]);
 if(!state.isHost)return null;
 const locked=busy||state.modeStatus==='ENDED'||state.status!=='ACTIVE'||!!cup?.drawnAt;
 const field=(key:'groupMeetings'|'semiFinalLegs'|'finalLegs',label:string)=><label className="text-sm text-slate-300">{label}<select className={input} value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:Number(e.target.value) as 1|2}))}><option value={1}>1 {key==='groupMeetings'?'meeting':'leg'}</option><option value={2}>2 {key==='groupMeetings'?'meetings':'legs'}</option></select></label>;
 return <form className={panel+' mb-6'} onSubmit={async e=>{e.preventDefault();setError('');try{await action({type:'CUP_SETTINGS',settings});}catch(e){setError(e instanceof Error?e.message:'Unable to save Cup settings.');}}}>
  <h3 className="text-xl font-bold text-white">Cup competition</h3><p className="mt-2 text-sm text-slate-400">An optional competition after the league. Settings apply only to this season and lock when the draw is made.</p>
  <fieldset disabled={locked} className="mt-5 space-y-5 disabled:opacity-60"><label className="flex items-center gap-3 text-white"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings(s=>({...s,enabled:e.target.checked}))} className="h-5 w-5 accent-emerald-400"/>Cup competition {settings.enabled?'ON':'OFF'}</label>
  {settings.enabled&&<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm text-slate-300">Cup name<input className={input} required minLength={2} maxLength={80} value={settings.name} onChange={e=>setSettings(s=>({...s,name:e.target.value}))}/></label><label className="text-sm text-slate-300">Qualified teams<select className={input} value={settings.qualifiedTeams} onChange={e=>setSettings(s=>({...s,qualifiedTeams:Number(e.target.value)}))}>{Array.from({length:Math.max(0,Math.floor(Math.min(32,state.teams.length)/2)-1)},(_,i)=>4+i*2).map(n=><option key={n}>{n}</option>)}</select></label><label className="text-sm text-slate-300">Group stage<select className={input} value={String(settings.groupStage)} onChange={e=>setSettings(s=>({...s,groupStage:e.target.value==='true',...(e.target.value==='false'?{qualifiedTeams:4}:{})}))}><option value="true">Two seeded groups</option><option value="false">No groups · 4 qualifiers</option></select></label>{settings.groupStage&&field('groupMeetings','Matches per group opponent')}{field('semiFinalLegs','Semi-final legs')}{field('finalLegs','Final legs')}<label className="flex items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={settings.thirdPlace} onChange={e=>setSettings(s=>({...s,thirdPlace:e.target.checked}))}/>Third-place match</label></div>}
  {state.teams.length<4&&<p className="text-sm text-amber-300">At least four teams are required to enable a Cup.</p>}<button className={button} disabled={settings.enabled&&state.teams.length<4}>Save Cup settings</button></fieldset>{cup?.drawnAt&&<p className="mt-3 text-sm text-amber-300">Draw locked. Finish the Cup before starting a new season.</p>}{error&&<p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}
 {cup?.settings.enabled&&!cup.drawnAt&&<div className="mt-5 border-t border-white/10 pt-5"><p className="text-sm text-amber-200">{cup.qualified.length?`${cup.qualified.length} teams qualified`: 'Waiting for league completion'}</p>{['QUALIFIED','DRAW_READY'].includes(cup.status)&&<button type="button" className={button+' mt-3'} disabled={busy} onClick={async()=>{setError('');try{await action({type:'CUP_DRAW'});}catch(e){setError(e instanceof Error?e.message:'Unable to generate draw.');}}}>Generate Cup Draw</button>}</div>}
 </form>;
}
type CupView=CupCompetition&{standings:{name:string;rows:Standing[]}[]};
export function ManagerCup({state,action,busy}:Props){
 const {data,error,retry}=useResource<CupView[]>(`/manager-mode/${state.id}/cups`,state.sequence);
 const [tab,setTab]=useState('Overview'),[season,setSeason]=useState(state.seasonData?.currentSeasonId??'');
 const previousDraw=useRef<number|null|undefined>(undefined),[drawNotice,setDrawNotice]=useState(false);
 const c=data?.find(c=>c.seasonId===season),name=(id:string)=>state.teams.find(t=>t.id===id)?.name??'Team';
 useEffect(()=>{if(!c)return;if(previousDraw.current===null&&c.drawnAt){setDrawNotice(true);setTab(c.settings.groupStage?'Groups':'Knockouts');}previousDraw.current=c.drawnAt;},[c]);
 useEffect(()=>{previousDraw.current=undefined;setDrawNotice(false);},[season]);
 const cupState=c?{...state,squadData:{sheets:state.squadData?.sheets??[],contracts:state.squadData?.contracts??[],lineups:c.lineups}}:state;
 return <div className="space-y-6"><div className="flex justify-end"><label className="flex items-center gap-3 text-sm text-slate-400">Season<select className={input+' !mt-0 !w-auto'} value={season} onChange={e=>setSeason(e.target.value)}>{state.seasonData?.seasons.map(s=><option key={s.id} value={s.id}>Season {s.number}</option>)}</select></label></div>
 {c?.settings.enabled&&<CupHero cup={c} state={state} action={action} busy={busy}/>}
 {error&&<p role="alert" className="text-red-300">{error} <button className={button} onClick={retry}>Retry</button></p>}{!data&&!error&&<p role="status" className="text-slate-400">Loading Cup…</p>}
 {drawNotice&&<p role="status" className="rounded-xl border border-amber-300/20 bg-amber-300/5 px-5 py-4 text-sm text-amber-200">Cup draw complete. The road to the trophy is set.</p>}
 <div className="flex gap-2 overflow-x-auto" role="tablist" aria-label="Cup sections">{['Overview','Groups','Fixtures','Knockouts','History'].map(x=><button key={x} role="tab" aria-selected={tab===x} onClick={()=>setTab(x)} className={'rounded-lg px-4 py-2 text-sm '+(tab===x?'bg-emerald-500/15 text-emerald-300':'text-slate-400 hover:text-white')}>{x}</button>)}</div>
 {tab==='History'?<div className="space-y-3">{data?.filter(x=>x.settings.enabled).map(x=><button key={x.id} className={panel+' block w-full text-left text-slate-300'} onClick={()=>{setSeason(x.seasonId);setTab('Overview');}}>{x.settings.name} · Season {state.seasonData?.seasons.find(s=>s.id===x.seasonId)?.number}<span className="mt-2 block text-sm text-amber-300">{x.championTeamId?'Champion: '+name(x.championTeamId):x.status.replaceAll('_',' ')}</span></button>)}{data&&!data.some(x=>x.settings.enabled)&&<p className="text-slate-400">No Cups have been enabled yet.</p>}</div>:!c?.settings.enabled?data&&<p className={panel+' text-slate-400'}>Cup competition is off for this season. The host can enable it in Host Control.</p>:<>
 {tab==='Overview'&&<><CupProgress cup={c}/><section className={panel}><h3 className="mb-4 text-lg font-bold text-white">Cup qualified</h3>{c.qualified.length?<ol className="grid gap-3 sm:grid-cols-2">{c.qualified.map((r,i)=><li key={r.teamId} className="flex justify-between gap-3 border-b border-white/5 pb-3 text-slate-200"><span>{r.position}. {name(r.teamId)}</span><span className="text-sm text-slate-500">Pot {Math.floor(i/2)+1}</span></li>)}</ol>:<p className="text-slate-400">Top {c.settings.qualifiedTeams} qualify after the league.</p>}</section><section className={panel}><h3 className="mb-4 text-lg font-bold text-white">Next on the road</h3>{c.fixtures.filter(f=>f.status!=='COMPLETED').slice(0,4).map(f=><div key={f.id} className="flex flex-wrap justify-between gap-3 border-t border-white/5 py-3 text-sm"><span className="text-slate-200">{name(f.homeTeamId)} vs {name(f.awayTeamId)}</span><span className="text-slate-500">{f.stage.replaceAll('_',' ')} / Leg {f.leg}</span></div>)}{!c.fixtures.some(f=>f.status!=='COMPLETED')&&<p className="text-sm text-slate-400">{c.status==='COMPLETED'?'Every match is in the books.':'Fixtures appear after the host generates the draw.'}</p>}</section></>}
 {tab==='Groups'&&<div className="grid gap-5 xl:grid-cols-2">{c.standings.map(g=><section key={g.name} className={panel+' min-w-0 '+styles.draw}><h3 className="mb-4 text-lg font-bold text-white">Group {g.name}</h3><div className="overflow-x-auto"><table className="w-full text-sm text-slate-300"><thead><tr>{['Club','P','W','D','L','GF','GA','GD','PTS'].map(h=><th key={h} className="px-2 py-3 text-left text-xs text-slate-500">{h}</th>)}</tr></thead><tbody>{g.rows.map(r=><tr key={r.teamId} className="border-t border-white/5"><td className="min-w-32 py-3 pr-3">{name(r.teamId)}<span className="ml-2 text-[10px] text-amber-200/60">P{Math.floor(c.qualified.findIndex(q=>q.teamId===r.teamId)/2)+1}</span></td>{[r.played,r.won,r.drawn,r.lost,r.gf,r.ga,r.gd,r.points].map((n,i)=><td key={i} className={'px-2 py-3 tabular-nums '+(i===7?'text-emerald-300 font-bold':'')}>{n}</td>)}</tr>)}</tbody></table></div></section>)}{!c.groups.length&&<p className="text-slate-400">{c.settings.groupStage?'Groups appear when the host generates the draw.':'This Cup starts at the semi-finals.'}</p>}<p className="text-xs text-slate-500 xl:col-span-2">Top two advance. Ties: points, goal difference, goals scored, then stable team ID.</p></div>}
 {tab==='Fixtures'&&<div className="grid gap-4 xl:grid-cols-2">{c.fixtures.map(f=><div key={f.id} className="min-w-0"><p className="mb-2 text-xs text-slate-400">{f.stage==='GROUP'?`Group ${f.group} · Matchday ${f.matchday}`:`${f.stage.replaceAll('_',' ')} · Leg ${f.leg}`}</p><FixtureMatchCard fixture={f} cup={c} state={cupState} onAction={action} busy={busy}/></div>)}{!c.fixtures.length&&<p className="text-slate-400">The draw will create Cup fixtures.</p>}</div>}
 {tab==='Knockouts'&&<CupBracket cup={c} state={state} action={action} busy={busy}/>}
 </>}</div>;
}
export function TrophyGallery({state,clubId}:{state:TournamentState;clubId?:string}){
 const {data,error,retry}=useResource<ClubHistory>(`/manager-mode/${state.id}/club-history`,state.sequence);
 const [view,setView]=useState<'all'|'mine'>('all'),[selected,setSelected]=useState<string|null>(clubId??null),[trophy,setTrophy]=useState<Trophy|null>(null);
 const rows=data?.filter(r=>clubId?r.teamId===clubId:view==='all'||r.teamId===state.myTeamId),detail=data?.find(r=>r.teamId===selected);
 return <div className="space-y-6"><div><h2 className="text-3xl font-bold text-white">{clubId||view==='mine'?'Trophy cabinet':'Trophy Gallery'}</h2><p className="mt-2 text-slate-400">The silverware, seasons and transfers behind every club.</p></div>{!clubId&&<div className="flex gap-3">{(['all','mine'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setSelected(null);}} className={view===v?button:'px-4 py-2 text-slate-400'}>{v==='all'?'All clubs':'My club'}</button>)}</div>}
 {error&&<p role="alert" className="text-red-300">{error} <button className={button} onClick={retry}>Retry</button></p>}{!data&&!error&&<p role="status" className="text-slate-400">Loading club history…</p>}
 <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rows?.map(r=>{const team=state.teams.find(t=>t.id===r.teamId)!;return <article key={r.teamId} className={panel}><div className="flex items-center gap-3">{team.logoUrl&&<img src={team.logoUrl} alt="" className="h-10 w-10 rounded-lg object-contain"/>}<div><h3 className="text-xl font-bold text-white">{team.name}</h3><p className="text-xs text-slate-500">{team.managerUsername??'Manager'}</p></div></div><div className="my-5 flex items-center gap-4 text-amber-300"><CupIcon/><p className="text-lg font-bold">{r.trophies.length} total {r.trophies.length===1?'trophy':'trophies'}</p></div><p className="text-sm text-slate-300">League Shields: {r.trophies.filter(t=>t.type==='LEAGUE_SHIELD').length} · Cups: {r.trophies.filter(t=>t.type==='CUP').length}</p>{(clubId||view==='mine')&&<div className="mt-4 space-y-2">{[...new Set(r.trophies.map(t=>t.name))].map(title=><p key={title} className="text-sm text-amber-100">{title} ×{r.trophies.filter(t=>t.name===title).length}</p>)}</div>}{!r.trophies.length?<p className="my-4 text-sm text-slate-500">No major trophies yet</p>:<ul className="my-4 space-y-2">{r.trophies.map(t=><li key={t.id} className="border-t border-amber-700/20 pt-2 text-sm text-amber-200">{<button className="text-left underline decoration-amber-300/30 underline-offset-4 hover:text-amber-100" onClick={()=>setTrophy(t)} aria-label={`Inspect ${t.name}`}>{t.name}</button>}<span className="ml-2 text-slate-500">Season {state.seasonData?.seasons.find(s=>s.id===t.seasonId)?.number}</span></li>)}</ul>}<button className={button+' mt-3'} onClick={()=>setSelected(r.teamId)}>View {team.name} history</button></article>;})}</div>
 {detail&&<section className={panel}><h3 className="text-2xl font-bold text-white">{state.teams.find(t=>t.id===detail.teamId)?.name} · Club history</h3><p className="mt-2 text-xs text-slate-400">Match record includes league and Cup. Transfer spending includes the original auction acquisitions.</p><dl className="my-6 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-4">{Object.entries({'Players bought':detail.playersBought,'Players sold / released':detail.playersSold,'Players traded out':detail.playersTraded,'Transfer income':formatCrore(detail.transferIncomeUnits),'Transfer spending':formatCrore(detail.transferSpendingUnits),'Net spend':formatCrore(detail.netSpendUnits),'Performance bonuses':formatCrore(detail.bonusUnits),'Current budget':formatCrore(detail.currentBudgetUnits),'Matches played':detail.record.played,'Wins':detail.record.won,'Draws':detail.record.drawn,'Losses':detail.record.lost,'Goals scored':detail.record.gf,'Goals conceded':detail.record.ga}).map(([label,value])=><div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-lg font-semibold text-white">{value}</dd></div>)}</dl><div className="overflow-x-auto"><table className="w-full text-left text-sm text-slate-300"><thead><tr>{['Season','League finish','Shield','Cup finish','Bonus'].map(x=><th key={x} className="p-3 text-slate-500">{x}</th>)}</tr></thead><tbody>{detail.seasons.map(s=><tr key={s.seasonId} className="border-t border-white/10"><td className="p-3">{s.number}</td><td className="p-3">{s.leaguePosition??'In progress'}</td><td className="p-3">{s.leagueWinner?'Winner':'—'}</td><td className="p-3">{s.cupFinish}</td><td className="p-3">{formatCrore(s.bonusUnits)}</td></tr>)}</tbody></table></div></section>}
 {trophy&&<TrophyDetail trophy={trophy} winner={state.teams.find(t=>t.id===trophy.teamId)?.name??'Club'} season={state.seasonData?.seasons.find(s=>s.id===trophy.seasonId)?.number} onClose={()=>setTrophy(null)}/>}
 </div>;
}
