'use client';
import {useState} from 'react';
import type {TournamentState} from '@/types/manager-mode';
import type {ManagerAction} from '@/services/manager-mode.service';
import {formatCrore,croreToUnits} from '@/lib/money';
import {panel,button,field} from './ManagerSetup';
type Props={state:TournamentState;action:(a:ManagerAction)=>Promise<void>;busy:boolean};
export function SeasonPanel({state,action,busy,controls=false}:Props&{controls?:boolean}){
 const [selected,setSelected]=useState(''),[confirm,setConfirm]=useState<'season'|'mode'|null>(null),[phrase,setPhrase]=useState('');
 const data=state.seasonData;if(!data)return null;const season=data.seasons.find(s=>s.id===(selected||data.currentSeasonId))??data.seasons.at(-1)!;
 const current=data.seasons.find(s=>s.id===data.currentSeasonId)!;const fixtures=state.seasonFixturesById?.[season.id]??state.fixtures;const table=season.status==='ACTIVE'?state.standings:season.finalStandings;const bonuses=data.bonuses.filter(b=>b.seasonId===season.id);
 const expected=confirm==='season'?'END SEASON':'END MANAGER MODE';
 return <section className={panel+' space-y-4'}><h2 className="text-xl">{controls?'Season management':'Season history'}</h2><label>Season<select className={field} value={season.id} onChange={e=>setSelected(e.target.value)}>{data.seasons.map(s=><option key={s.id} value={s.id}>Season {s.number} · {s.status}</option>)}</select></label><p>Season {season.number} · {season.status} · {fixtures.filter(f=>f.status==='COMPLETED').length}/{fixtures.length} fixtures completed</p>{season.championTeamId&&<div className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4"><h3 className="text-amber-300 text-lg">🏆 LEAGUE SHIELD WINNER</h3><strong className="text-2xl">{state.teams.find(t=>t.id===season.championTeamId)?.name}</strong><p>Season {season.number} Champion</p></div>}{season.status!=='ACTIVE'&&<><p>{season.endedEarly?'Closed early. Only completed matches count. Unplayed results were not fabricated.':'Season complete.'}</p><div className="overflow-x-auto"><table className="w-full text-sm"><caption>Final table · Season {season.number}</caption><thead><tr>{['Pos','Team','P','W','D','L','GF','GA','GD','PTS'].map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{table.map(row=><tr key={row.teamId}><td>{row.position}</td><td>{state.teams.find(t=>t.id===row.teamId)?.name}</td>{[row.played,row.won,row.drawn,row.lost,row.gf,row.ga,row.gd,row.points].map((n,i)=><td className="p-2" key={i}>{n}</td>)}</tr>)}</tbody></table></div><h3>Season rewards</h3>{bonuses.length?bonuses.map(b=><p key={b.teamId}>{b.position}. {state.teams.find(t=>t.id===b.teamId)?.name} · +{formatCrore(b.amountUnits)}</p>):<p>No rewards awarded for this archived season.</p>}<details><summary>Historical fixtures and results (read only)</summary>{fixtures.map(f=><p key={f.id}>Matchday {f.matchday}: {state.teams.find(t=>t.id===f.homeTeamId)?.name} {f.status==='COMPLETED'?`${f.homeScore} – ${f.awayScore}`:'Unplayed'} {state.teams.find(t=>t.id===f.awayTeamId)?.name}</p>)}</details></>}
 <details><summary>League shields by team</summary>{state.teams.map(t=><p key={t.id}>{t.name} — {data.seasons.filter(s=>s.championTeamId===t.id).length}</p>)}</details>
 {state.isHost&&state.modeStatus!=='ENDED'&&(controls||current.status==='COMPLETED')&&<div className="flex gap-2 flex-wrap">{current.status==='ACTIVE'&&state.status==='ACTIVE'&&<button className={button} disabled={busy} onClick={()=>{setConfirm('season');setPhrase('');}}>End current season</button>}{current.status==='COMPLETED'&&<button className={button} disabled={busy} onClick={()=>void action({type:'START_NEXT_SEASON'})}>Start next season</button>}<button className={button} disabled={busy} onClick={()=>{setConfirm('mode');setPhrase('');}}>End Manager Mode</button></div>}
 {confirm&&<div role="dialog" aria-modal="true" aria-label={confirm==='season'?'End Season Early?':'End Manager Mode?'} className="rounded-xl border border-red-500/50 bg-red-950/40 p-5 space-y-3"><h3>{confirm==='season'?'End Season Early?':'End Manager Mode?'}</h3><p>{confirm==='season'?'Unplayed fixtures will remain unplayed. Current standings become final and bonuses are awarded once. This season cannot be resumed.':'This permanently closes Manager Mode. All seasons, squads and history stay available read-only. An active season is archived without a League Shield or bonuses; end the season first if you want to award rewards.'}</p><label>Type {expected}<input className={field} value={phrase} onChange={e=>setPhrase(e.target.value)}/></label><button className={button} disabled={busy||phrase!==expected} onClick={()=>{void action(confirm==='season'?{type:'END_CURRENT_SEASON',confirmation:'END SEASON'}:{type:'END_MANAGER_MODE',confirmation:'END MANAGER MODE'});setConfirm(null);}}>Confirm {confirm==='season'?'end season':'end Manager Mode'}</button> <button className={button} onClick={()=>setConfirm(null)}>Cancel</button></div>}
 </section>;
}
export function SeasonSettings({state,action,busy}:Props){const [rate,setRate]=useState(String(state.seasonData?.settings.resalePercent??50)),[bonuses,setBonuses]=useState(state.teams.map((_,i)=>String((state.seasonData?.settings.bonusUnits[i]??0)/2))),[error,setError]=useState('');return <form className={panel} onSubmit={e=>{e.preventDefault();try{const units=bonuses.map(x=>croreToUnits(Number(x)));setError('');void action({type:'SEASON_SETTINGS',resalePercent:Number(rate),bonusUnits:units});}catch{setError('Use bonuses in ₹0.5 Cr steps.');}}}><h3>Season rewards and resale settings</h3><label>Resale percentage<input className={field} type="number" min="40" max="60" step="1" required value={rate} onChange={e=>setRate(e.target.value)}/></label><p className="text-sm text-slate-400">Every team receives a positive bonus based on final position, from first to last. Changes affect future awards and sale quotes; awarded bonuses remain unchanged.</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{bonuses.map((value,i)=><label key={i}>Position {i+1} bonus (Cr)<input className={field} type="number" step="0.5" min="0.5" required value={value} onChange={e=>setBonuses(bonuses.map((x,n)=>n===i?e.target.value:x))}/></label>)}</div>{error&&<p role="alert">{error}</p>}<button className={button} disabled={busy||state.modeStatus==='ENDED'}>Save season settings</button></form>;}
