'use client';
import {useEffect,useState,type DragEvent} from 'react';
import {ArrowDownToLine,Save,Shirt} from 'lucide-react';
import {formationIds,canonicalFormation,getFormation,canPlay,remapLineup,type Formation} from '@/lib/formations';
import type {TournamentState,ManagerPlayer} from '@/types/manager-mode';
import type {ManagerAction} from '@/services/manager-mode.service';
import {PlayerImage} from '@/components/shared/PlayerImage';
import {downloadTeamSheetPdf} from '@/lib/pdf/managerTeamSheetPdf';
const button='min-h-10 rounded-xl border border-emerald-800 bg-emerald-950 px-3 py-2 text-sm text-emerald-100 disabled:opacity-40';
const field='min-h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100';
export function TeamSheetEditor({state,action,busy}:{state:TournamentState;action:(a:ManagerAction)=>Promise<void>;busy:boolean}){
 const owned=state.players.filter(p=>p.currentTeamId===state.myTeamId),saved=state.squadData?.sheets.find(s=>s.teamId===state.myTeamId);
 const [formation,setFormation]=useState<Formation>(saved?.formation??'4-3-3 Holding'),[slots,setSlots]=useState<(string|null)[]>(saved?.slots??Array(11).fill(null)),[bench,setBench]=useState<string[]>(saved?.bench??[]),[captain,setCaptain]=useState<string|null>(saved?.captainId??null),[error,setError]=useState(''),[pdfBusy,setPdfBusy]=useState(false),[query,setQuery]=useState('');
 const savedKey=JSON.stringify(saved),rosterKey=owned.map(p=>p.id).sort().join(',');
 useEffect(()=>{setFormation(saved?.formation??'4-3-3 Holding');setSlots(saved?.slots??Array(11).fill(null));setBench(saved?.bench??[]);setCaptain(saved?.captainId??null);},[savedKey,rosterKey]);
 const layout=getFormation(formation),dirty=JSON.stringify({formation,slots,bench,captainId:captain})!==JSON.stringify({formation:saved?.formation,slots:saved?.slots,bench:saved?.bench,captainId:saved?.captainId});
 function changeFormation(next:Formation){const mapped=remapLineup(owned,slots,bench,next);setFormation(next);setSlots(mapped.slots);setBench(mapped.bench);if(captain&&!mapped.slots.includes(captain))setCaptain(null);setError('');}
 function assign(index:number,id:string|null){
  if(busy)return;setError('');const p=owned.find(p=>p.id===id);
  if(id&&(!p||!canPlay(p,layout.slots[index]!.role))){setError('Choose a player with a compatible primary or secondary position.');return;}
  const next=[...slots],oldIndex=id?next.indexOf(id):-1,displaced=next[index];
  let nextBench=bench.filter(x=>x!==id);
  if(oldIndex>=0){const other=owned.find(p=>p.id===displaced);next[oldIndex]=other&&canPlay(other,layout.slots[oldIndex]!.role)?other.id:null;if(other&&!next[oldIndex]&&!nextBench.includes(other.id))nextBench.push(other.id);}
  else if(displaced&&displaced!==id&&!nextBench.includes(displaced))nextBench.push(displaced);
  next[index]=id;nextBench=nextBench.filter(x=>!next.includes(x));setSlots(next);setBench(nextBench.slice(0,12));if(captain&&!next.includes(captain))setCaptain(null);
 }
 function move(id:string,destination:'bench'|'reserve'){
  if(busy||!owned.some(p=>p.id===id))return;
  if(destination==='bench'&&!bench.includes(id)&&bench.length>=12){setError('The substitutes list has twelve players. Move one to reserves first.');return;}
  setSlots(slots.map(x=>x===id?null:x));setBench(destination==='bench'?[...new Set([...bench,id])]:bench.filter(x=>x!==id));if(captain===id)setCaptain(null);setError('');
 }
 function drop(e:DragEvent,destination:number|'bench'|'reserve'){e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(typeof destination==='number')assign(destination,id);else move(id,destination);}
 const chip=(p:ManagerPlayer,destination:'bench'|'reserve')=><div key={p.id} draggable={!busy} onDragStart={e=>e.dataTransfer.setData('text/plain',p.id)} className="flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-900 p-2"><PlayerImage player={p} className="h-14 w-12 shrink-0 object-contain"/><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-white">{p.name}</p><p className="text-xs text-slate-300">{p.position} · {p.overall} OVR</p><button className="mt-1 text-xs text-emerald-300 underline disabled:opacity-40" disabled={busy} onClick={()=>move(p.id,destination)}>{destination==='bench'?'Add to substitutes':'Move to reserves'}</button></div></div>;
 return <div className="space-y-5"><div className="flex flex-wrap items-end gap-3"><div className="w-full sm:w-64"><label className="text-sm text-slate-300">Search formations<input className={field} value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. 4-3-3 or Holding"/></label><label className="mt-2 block text-sm text-slate-300">Formation<select aria-label="Formation" className={field} disabled={busy} value={canonicalFormation(formation)} onChange={e=>changeFormation(e.target.value as Formation)}>{['3','4','5'].map(group=><optgroup key={group} label={group+' BACK'}>{formationIds.filter(id=>id.startsWith(group)&&(id.toLowerCase().includes(query.toLowerCase())||id===canonicalFormation(formation))).map(id=><option key={id}>{id}</option>)}</optgroup>)}</select></label></div><label className="text-sm text-slate-300">Captain<select className={field} value={captain??''} disabled={busy} onChange={e=>setCaptain(e.target.value||null)}><option value="">Not assigned</option>{slots.filter((id):id is string=>!!id).map(id=><option key={id} value={id}>{owned.find(p=>p.id===id)?.name}</option>)}</select></label><button className={button+' flex items-center gap-2'} disabled={busy||!dirty} onClick={()=>void action({type:'SAVE_TEAM_SHEET',formation,slots,bench,captainId:captain})}><Save size={16}/>Save team sheet</button><button className={button+' flex items-center gap-2'} disabled={!saved||dirty||pdfBusy} onClick={()=>{if(saved){setPdfBusy(true);void downloadTeamSheetPdf(state,saved).catch(()=>setError('PDF could not be generated. Please try again.')).finally(()=>setPdfBusy(false));}}}><ArrowDownToLine size={16}/>{pdfBusy?'Preparing PDF…':'Download Team Sheet PDF'}</button></div>
 <p className="text-sm text-slate-300">Drag players between the pitch, substitutes and reserves. Each slot also has a selector for touch and keyboard. Formation changes keep compatible starters; remaining players return to substitutes or reserves.</p>{error&&<p role="alert" className="text-red-300">{error}</p>}
 <div className="overflow-x-auto rounded-2xl border border-emerald-700"><div className="relative min-w-[620px] bg-[#073d31]" style={{height:760}} aria-label="Starting eleven pitch"><svg className="pointer-events-none absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="#a7f3d055" strokeWidth="0.25"><rect x="2" y="2" width="96" height="96"/><path d="M2 50H98 M25 2V18H75V2 M38 2V8H62V2 M25 98V82H75V98 M38 98V92H62V98"/><ellipse cx="50" cy="50" rx="12" ry="10"/></g></svg>{layout.slots.map((slot,i)=>{const p=owned.find(p=>p.id===slots[i]);return <div key={i} style={{left:slot.x+'%',top:slot.y+'%',transform:'translate(-50%,-50%)',width:'17%'}} className="absolute text-center" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,i)}><div draggable={!busy&&!!p} onDragStart={e=>{if(p)e.dataTransfer.setData('text/plain',p.id);}} className="mx-auto w-20 rounded-xl border border-emerald-200/30 bg-emerald-950/90 p-1">{p?<PlayerImage player={p} className="mx-auto h-12 w-14 object-contain"/>:<Shirt className="mx-auto h-12 text-emerald-200/50"/>}<p className="text-[11px] text-emerald-100">{slot.role}{p?' · '+p.overall+' OVR':''}{p?.id===captain?' · C':''}</p></div><select aria-label={'Slot '+(i+1)+' '+slot.role} className="mt-1 w-full rounded border border-emerald-700 bg-emerald-950 px-1 py-1 text-xs text-white" value={slots[i]??''} disabled={busy} onChange={e=>assign(i,e.target.value||null)}><option value="">Empty {slot.role}</option>{owned.filter(player=>canPlay(player,slot.role)||player.id===slots[i]).map(player=><option key={player.id} value={player.id}>{player.name}</option>)}</select></div>;})}</div></div>
 <p className="text-xs text-slate-300">{slots.filter(Boolean).length}/11 starters · {dirty?'Unsaved changes':'Saved'} · On smaller screens, scroll the pitch sideways.</p>
 <section className="rounded-2xl border border-slate-700 bg-slate-950 p-4" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,'bench')}><h3 className="mb-3 font-semibold text-white">Substitutes · {bench.length}/12</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{bench.map(id=>owned.find(p=>p.id===id)).filter((p):p is ManagerPlayer=>!!p).map(p=>chip(p,'reserve'))}</div>{!bench.length&&<p className="text-sm text-slate-400">Drop players here or add them from reserves.</p>}</section>
 <section className="rounded-2xl border border-slate-700 bg-slate-950 p-4" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,'reserve')}><h3 className="mb-3 font-semibold text-white">Reserves</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{owned.filter(p=>!slots.includes(p.id)&&!bench.includes(p.id)).map(p=>chip(p,'bench'))}</div></section>
 </div>;
}

